# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rspec", "~> 3.12"
gem "rubocop", "~> 1.75", group: :development
gem "sorbet", group: :development
gem "tapioca", group: :development
gem "rubocop-sorbet", group: :development
