-- Auto-generated by scripts/generate-tests.py — DO NOT EDIT
-- AceSerializer-3.0 test suite — busted spec

dofile("shim.lua")
dofile("deps/AceSerializer-3.0.lua")

local AceSerializer = LibStub:GetLibrary("AceSerializer-3.0")

local function ser(v)
  return AceSerializer:Serialize(v)
end

local function deser(s)
  local ok, val = AceSerializer:Deserialize(s)
  assert(ok, "Deserialize failed: " .. tostring(val))
  return val
end

local function roundtrip(v)
  return deser(ser(v))
end

local function contains(str, sub)
  return string.find(str, sub, 1, true) ~= nil
end

local function count_occurrences(str, sub)
  local c = 0
  local i = 1
  while true do
    local found = string.find(str, sub, i, true)
    if not found then break end
    c = c + 1
    i = found + 1
  end
  return c
end

------------------------------------------------------------------------
describe("AceSerializer", function()
------------------------------------------------------------------------

  describe("A. String Escaping", function()
    it("A1: NUL (0x00) → ~@", function()
      assert.truthy(contains(ser(string.char(0)), "~@"))
    end)

    it("A2a: control 0x01 → ~A", function()
      assert.truthy(contains(ser(string.char(1)), "~A"))
    end)

    it("A2b: control 0x0A (LF) → ~J", function()
      assert.truthy(contains(ser(string.char(10)), "~J"))
    end)

    it("A2c: control 0x1D → ~]", function()
      assert.truthy(contains(ser(string.char(29)), "~]"))
    end)

    it("A3: byte 30 (0x1E) → ~z (special case)", function()
      assert.truthy(contains(ser(string.char(30)), "~z"))
    end)

    it("A4: byte 31 (0x1F) → ~_", function()
      assert.truthy(contains(ser(string.char(31)), "~_"))
    end)

    it("A5: space (0x20) → ~`", function()
      assert.truthy(contains(ser(" "), "~`"))
    end)

    it("A6: caret ^ (0x5E) → ~}", function()
      assert.truthy(contains(ser("^"), "~}"))
    end)

    it("A7: tilde ~ (0x7E) → ~|", function()
      assert.truthy(contains(ser("~"), "~|"))
    end)

    it("A8: DEL (0x7F) → ~{", function()
      assert.truthy(contains(ser(string.char(127)), "~{"))
    end)

    it("A9: single-pass — no double-escaping", function()
      local wire = ser(string.char(94, 126, 127))
      assert.truthy(contains(wire, "~}"))
      assert.truthy(contains(wire, "~|"))
      assert.truthy(contains(wire, "~{"))
    end)

    it("A10: printable ASCII passes through", function()
      assert.truthy(contains(ser("hello"), "^Shello"))
    end)

  end)

  describe("B. String Unescaping", function()
    it("B11: ~@ → NUL (0x00)", function()
      assert.are.equal(deser("^1^S~@^^"), string.char(0))
    end)

    it("B12a: ~A → chr(1)", function()
      assert.are.equal(deser("^1^S~A^^"), string.char(1))
    end)

    it("B12b: ~J → chr(10)", function()
      assert.are.equal(deser("^1^S~J^^"), string.char(10))
    end)

    it("B13: ~z → byte 30 (0x1E)", function()
      assert.are.equal(deser("^1^S~z^^"), string.char(30))
    end)

    it("B14: ~{ → DEL (0x7F)", function()
      assert.are.equal(deser("^1^S~{^^"), string.char(127))
    end)

    it("B15: ~| → tilde (~)", function()
      assert.are.equal(deser("^1^S~|^^"), "~")
    end)

    it("B16: ~} → caret (^)", function()
      assert.are.equal(deser("^1^S~}^^"), "^")
    end)

    it("B17: round-trip all escapable bytes", function()
      local input = string.char(0, 1, 10, 29, 30, 31, 32, 94, 127, 126)
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("C. Number Serialization", function()
    it("C18: positive integer → ^N42", function()
      assert.truthy(contains(ser(42), "^N42"))
    end)

    it("C19: negative integer → ^N-42", function()
      assert.truthy(contains(ser(-42), "^N-42"))
    end)

    it("C20: zero → ^N0", function()
      assert.truthy(contains(ser(0), "^N0"))
    end)

    it("C21: large integer", function()
      assert.truthy(contains(ser(1000000), "^N1000000"))
    end)

    it("C22: non-integer float uses ^N (tonumber/tostring check)", function()
      assert.truthy(contains(ser(3.14), "^N3.14"))
    end)

    it("C23: 3.14 exact wire format", function()
      assert.are.equal(ser(3.14), "^1^N3.14^^")
    end)

    it("C24a: 0.1 wire format", function()
      assert.are.equal(ser(0.1), "^1^N0.1^^")
    end)

    it("C24b: -99.99 wire format", function()
      assert.are.equal(ser(-99.99), "^1^N-99.99^^")
    end)

    it("C24c: 1e-10 wire format", function()
      assert.are.equal(ser(1e-10), "^1^N1e-10^^")
    end)

    it("C25: positive infinity → ^N1.#INF or ^Ninf", function()
      local wire = ser(math.huge)
      local found = false
      if contains(wire, "1.#INF") then found = true end
      if contains(wire, "inf") then found = true end
      assert.truthy(found)
    end)

    it("C26: negative infinity → ^N-1.#INF or ^N-inf", function()
      local wire = ser(-math.huge)
      local found = false
      if contains(wire, "-1.#INF") then found = true end
      if contains(wire, "-inf") then found = true end
      assert.truthy(found)
    end)

  end)

  describe("D. Number Deserialization", function()
    it("D27: ^N42 → 42", function()
      assert.are.equal(deser("^1^N42^^"), 42)
    end)

    it("D28: ^N-42 → -42", function()
      assert.are.equal(deser("^1^N-42^^"), -42)
    end)

    it("D29: ^N3.14 → 3.14", function()
      local result = deser("^1^N3.14^^")
      assert.truthy(math.abs(result - 3.14) < 1e-10)
    end)

    it("D30: ^N1.#INF → Infinity", function()
      assert.are.equal(deser("^1^N1.#INF^^"), math.huge)
    end)

    it("D31: ^N-1.#INF → -Infinity", function()
      assert.are.equal(deser("^1^N-1.#INF^^"), -math.huge)
    end)

    it("D32: ^Ninf → Infinity (alternate)", function()
      assert.are.equal(deser("^1^Ninf^^"), math.huge)
    end)

    it("D33: ^N-inf → -Infinity (alternate)", function()
      assert.are.equal(deser("^1^N-inf^^"), -math.huge)
    end)

    it("D34: ^F<m>^f<e> → correct float", function()
      local result = deser("^1^F4503599627370496^f-53^^")
      assert.truthy(math.abs(result - 0.5) < 1e-10)
    end)

  end)

  describe("E. Float Round-trips", function()
    it("E35: round-trip 3.14", function()
      local input = 3.14
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E36: round-trip 0.1", function()
      local input = 0.1
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E37: round-trip 123.456", function()
      local input = 123.456
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E38: round-trip -99.99", function()
      local input = -99.99
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E39: round-trip 1e-10", function()
      local input = 1e-10
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E40: round-trip very small float (min normal)", function()
      local input = 2.2250738585072014e-308
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("E41: round-trip very large float", function()
      local input = 1.7976931348623157e+308
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

  end)

  describe("F. Boolean", function()
    it("F42: true → ^B", function()
      assert.truthy(contains(ser(true), "^B"))
    end)

    it("F43: false → ^b", function()
      assert.truthy(contains(ser(false), "^b"))
    end)

    it("F44: ^B → true", function()
      assert.are.equal(deser("^1^B^^"), true)
    end)

    it("F45: ^b → false", function()
      assert.are.equal(deser("^1^b^^"), false)
    end)

  end)

  describe("G. Nil", function()
    it("G46: nil → ^Z", function()
      assert.truthy(contains(ser(nil), "^Z"))
    end)

    it("G47: ^Z → nil", function()
      -- Lua AceSerializer-3.0 does not store nil in tables; skip null-in-table tests
      pending("Lua AceSerializer-3.0 does not support nil values inside tables")
    end)

  end)

  describe("H. Table Serialization", function()
    it("H48: empty table → ^T^t", function()
      assert.truthy(contains(ser({  }), "^T^t"))
    end)

    it("H49: single string key-value pair", function()
      local wire = ser({ ["a"] = 1 })
      assert.truthy(contains(wire, "^T"))
      assert.truthy(contains(wire, "^Sa"))
      assert.truthy(contains(wire, "^N1"))
      assert.truthy(contains(wire, "^t"))
    end)

    it("H50: multiple key-value pairs", function()
      local wire = ser({ ["a"] = 1, ["b"] = 2 })
      assert.truthy(contains(wire, "^T"))
      assert.truthy(contains(wire, "^t"))
    end)

    it("H51: nested table", function()
      local wire = ser({ ["inner"] = { ["x"] = 1 } })
      assert.are.equal(count_occurrences(wire, "^T"), 2)
    end)

    it("H52: array → 1-based integer keys", function()
      local wire = ser({ "a", "b", "c" })
      assert.truthy(contains(wire, "^N1"))
      assert.truthy(contains(wire, "^Sa"))
      assert.truthy(contains(wire, "^N2"))
      assert.truthy(contains(wire, "^Sb"))
      assert.truthy(contains(wire, "^N3"))
      assert.truthy(contains(wire, "^Sc"))
    end)

    it("H53: mixed table (integer + string keys)", function()
      local wire = ser({ [1] = "a", ["x"] = "b" })
      assert.truthy(contains(wire, "^T"))
      assert.truthy(contains(wire, "^t"))
    end)

  end)

  describe("I. Array Detection", function()
    it("I54: sequential 1-based keys → array", function()
      local input = { [1] = "a", [2] = "b", [3] = "c" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "a")
      assert.are.equal(result[2], "b")
      assert.are.equal(result[3], "c")
    end)

    it("I55: non-sequential keys → object", function()
      local input = { [1] = "a", [3] = "c" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "a")
      assert.are.equal(result[3], "c")
    end)

    it("I56: string keys → object", function()
      local input = { ["x"] = 1, ["y"] = 2 }
      local result = roundtrip(input)
      assert.are.equal(result["x"], 1)
      assert.are.equal(result["y"], 2)
    end)

    it("I57: single element", function()
      local input = { [1] = "only" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "only")
    end)

    it("I58: empty table → empty", function()
      local result = roundtrip({  })
      assert.are.equal(next(result), nil)
    end)

  end)

  describe("J. Framing", function()
    it("J59: output starts with ^1 and ends with ^^", function()
      local wire = ser("hello")
      assert.truthy(string.sub(wire, 1, #"^1") == "^1")
      assert.truthy(string.sub(wire, -#"^^") == "^^")
    end)

    it("J62: control chars stripped from input", function()
      assert.are.equal(deser("^1\9\10^Shello\13\10^^"), "hello")
    end)

  end)

  describe("K. Error Handling", function()
    it("J60: missing ^1 prefix → error", function()
      local ok, _ = AceSerializer:Deserialize("^Shello^^")
      assert.is_false(ok)
    end)

    it("K64: empty string → error", function()
      local ok, _ = AceSerializer:Deserialize("")
      assert.is_false(ok)
    end)

    it("K65: missing ^^ terminator → error", function()
      local ok, _ = AceSerializer:Deserialize("^1^Shello")
      assert.is_false(ok)
    end)

  end)

  describe("L. Round-trips", function()
    it("L66: plain ASCII string", function()
      local input = "hello world test"
      assert.are.equal(roundtrip(input), input)
    end)

    it("L67: all special chars", function()
      local input = string.char(0, 1, 30, 31, 32, 94, 126, 127)
      assert.are.equal(roundtrip(input), input)
    end)

    it("L68: integer", function()
      local input = 12345
      assert.are.equal(roundtrip(input), input)
    end)

    it("L69: float", function()
      local input = 3.14
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("L70: boolean", function()
      assert.are.equal(roundtrip(true), true)
      assert.are.equal(roundtrip(false), false)
    end)

    it("L71: nil", function()
      local input = nil
      assert.is_nil(roundtrip(input))
    end)

    it("L72: nested table/array", function()
      local input = { [1] = 1, [2] = { [1] = 2, [2] = 3 } }
      local result = roundtrip(input)
      assert.are.equal(result[1], 1)
    end)

    it("L73: mixed-type table", function()
      local input = { ["n"] = 42, ["f"] = 3.14, ["b"] = true, ["s"] = "hello" }
      local result = roundtrip(input)
      assert.are.equal(result["n"], 42)
      assert.truthy(math.abs(result["f"] - 3.14) < 1e-10)
      assert.are.equal(result["b"], true)
      assert.are.equal(result["s"], "hello")
    end)

  end)

  describe("L2. Fixture Wire-Format Tests", function()
    it("L74: simple array of two strings — exact wire", function()
      -- Table key order is non-deterministic in Lua; verify via round-trip instead
      local result = deser(ser({ [1] = "a", [2] = "b" }))
      assert.same({ [1] = "a", [2] = "b" }, result)
    end)

    it("L75: simple array of two strings — deserialize", function()
      assert.same({ [1] = "a", [2] = "b" }, deser("^1^T^N1^Sa^N2^Sb^t^^"))
    end)

    it("L76: array of three mixed values — exact wire", function()
      -- Table key order is non-deterministic in Lua; verify via round-trip instead
      local result = deser(ser({ [1] = "hello", [2] = 42, [3] = true }))
      assert.same({ [1] = "hello", [2] = 42, [3] = true }, result)
    end)

    it("L77: array of three mixed values — deserialize", function()
      assert.same({ [1] = "hello", [2] = 42, [3] = true }, deser("^1^T^N1^Shello^N2^N42^N3^B^t^^"))
    end)

    it("L78: nested array — exact wire", function()
      -- Table key order is non-deterministic in Lua; verify via round-trip instead
      local result = deser(ser({ [1] = { [1] = "a", [2] = "b" }, [2] = "c" }))
      assert.same({ [1] = { [1] = "a", [2] = "b" }, [2] = "c" }, result)
    end)

    it("L79: nested array — deserialize", function()
      assert.same({ [1] = { [1] = "a", [2] = "b" }, [2] = "c" }, deser("^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^"))
    end)

    it("L80: array with null values — exact wire", function()
      -- Lua AceSerializer-3.0 skips nil values in tables
      pending("Lua AceSerializer-3.0 does not support nil values inside tables")
    end)

    it("L81: array with null values — deserialize", function()
      -- Lua AceSerializer-3.0 does not store nil in tables; skip null-in-table tests
      pending("Lua AceSerializer-3.0 does not support nil values inside tables")
    end)

    it("L82: nested structure from protocol spec — deserialize only", function()
      -- Lua AceSerializer-3.0 does not store nil in tables; skip null-in-table tests
      pending("Lua AceSerializer-3.0 does not support nil values inside tables")
    end)

    it("L83: mixed table string and integer keys — deserialize only", function()
      assert.same({ ["hello"] = "world", ["n"] = 42 }, deser("^1^T^Shello^Sworld^Sn^N42^t^^"))
    end)

  end)

  describe("M. Float wire format consistency", function()
    it("M84: 3.14 uses ^N path (not ^F)", function()
      assert.truthy(contains(ser(3.14), "^N3.14"))
    end)

    it("M85: very small float 1e-10 uses ^N path", function()
      assert.truthy(contains(ser(1e-10), "^N"))
    end)

    it("M86: 0.5 uses ^N path", function()
      assert.truthy(contains(ser(0.5), "^N0.5"))
    end)

    it("M87: extreme float 2.2250738585072014e-308 round-trips correctly", function()
      local input = 2.2250738585072014e-308
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("M88: extreme float 2.2250738585072014e-308 uses ^F path (%.14g loses precision)", function()
      assert.truthy(contains(ser(2.2250738585072014e-308), "^F"))
    end)

  end)

  describe("N. Escape edge cases", function()
    it("N88a: invalid escape ~> (ord 62, would produce negative byte) is rejected", function()
      local ok, _ = AceSerializer:Deserialize("^1^S~>^^")
      assert.is_false(ok)
    end)

    it("N88b: invalid escape ~# (ord 35, would produce negative byte) is rejected", function()
      local ok, _ = AceSerializer:Deserialize("^1^S~#^^")
      assert.is_false(ok)
    end)

    it("N88c: all control bytes 0x01-0x1D round-trip correctly", function()
      local input = string.char(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)
      assert.are.equal(roundtrip(input), input)
    end)

    it("N89: all escapable bytes combined in one string round-trip", function()
      local input = string.char(0, 1, 10, 29, 30, 31, 32, 94, 126, 127)
      assert.are.equal(roundtrip(input), input)
    end)

    it("N90: high bytes 0x80-0xFF pass through unescaped", function()
      local input = string.char(128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255)
      assert.are.equal(roundtrip(input), input)
    end)

  end)

end)
