-- Auto-generated by testing/generate-tests.py — DO NOT EDIT
-- LibSerialize test suite — busted spec

dofile("shim.lua")
dofile("deps/LibSerialize.lua")

local LibSerialize = LibStub:GetLibrary("LibSerialize")

local function ser(...)
  return LibSerialize:Serialize(...)
end

local function deser(s)
  local ok, val = LibSerialize:Deserialize(s)
  assert(ok, "Deserialize failed: " .. tostring(val))
  return val
end

local function roundtrip(v)
  return deser(ser(v))
end

------------------------------------------------------------------------
describe("LibSerialize", function()
------------------------------------------------------------------------

  describe("A. Nil", function()
    it("A01: serialize nil produces non-empty string", function()
      local s = ser(nil)
      assert.are.equal(type(s), "string")
      assert.truthy(#s > 0)
    end)

    it("A02: nil round-trips to nil", function()
      local s = ser(nil)
      local ok, val = LibSerialize:Deserialize(s)
      assert.are.equal(ok, true)
      assert.is_nil(val)
    end)

    it("A03: Deserialize of serialized nil returns ok=true and nil value", function()
      local s = ser(nil)
      local ok, val = LibSerialize:Deserialize(s)
      assert.are.equal(ok, true)
      assert.is_nil(val)
    end)

  end)

  describe("B. Integer encoding (small embedded)", function()
    it("B01: zero round-trips correctly (embedded 1-byte)", function()
      local input = 0
      assert.are.equal(roundtrip(input), input)
    end)

    it("B02: positive small int 1 round-trips correctly", function()
      local input = 1
      assert.are.equal(roundtrip(input), input)
    end)

    it("B03: small int 127 round-trips correctly (embedded 1-byte max)", function()
      local input = 127
      assert.are.equal(roundtrip(input), input)
    end)

    it("B04: small negative -1 round-trips correctly (embedded 2-byte)", function()
      local input = -1
      assert.are.equal(roundtrip(input), input)
    end)

    it("B05: small negative -4095 round-trips correctly (embedded 2-byte near max)", function()
      local input = -4095
      assert.are.equal(roundtrip(input), input)
    end)

    it("B06: positive 128 round-trips correctly (embedded 2-byte)", function()
      local input = 128
      assert.are.equal(roundtrip(input), input)
    end)

    it("B07: positive 4095 round-trips correctly (embedded 2-byte max)", function()
      local input = 4095
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("C. Integer encoding (multi-byte)", function()
    it("C01: 16-bit positive 4096 round-trips correctly", function()
      local input = 4096
      assert.are.equal(roundtrip(input), input)
    end)

    it("C02: 16-bit positive max 65535 round-trips correctly", function()
      local input = 65535
      assert.are.equal(roundtrip(input), input)
    end)

    it("C03: 16-bit negative -4096 round-trips correctly", function()
      local input = -4096
      assert.are.equal(roundtrip(input), input)
    end)

    it("C04: 24-bit positive 65536 round-trips correctly", function()
      local input = 65536
      assert.are.equal(roundtrip(input), input)
    end)

    it("C05: 24-bit positive max 16777215 round-trips correctly", function()
      local input = 16777215
      assert.are.equal(roundtrip(input), input)
    end)

    it("C06: 32-bit positive 16777216 round-trips correctly", function()
      local input = 16777216
      assert.are.equal(roundtrip(input), input)
    end)

    it("C07: 32-bit positive max 4294967295 round-trips correctly", function()
      local input = 4294967295
      assert.are.equal(roundtrip(input), input)
    end)

    it("C08: 64-bit positive 4294967296 round-trips correctly", function()
      local input = 4294967296
      assert.are.equal(roundtrip(input), input)
    end)

    it("C09: large negative -65536 round-trips correctly", function()
      local input = -65536
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("D. Float encoding", function()
    it("D01: float 3.14 round-trips correctly", function()
      local input = 3.14
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("D02: float 0.1 round-trips correctly", function()
      local input = 0.1
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("D03: float -99.99 round-trips correctly", function()
      local input = -99.99
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("D04: float 1e-10 round-trips correctly", function()
      local input = 1e-10
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("D05: float 0.5 round-trips correctly", function()
      local input = 0.5
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

    it("D06: positive infinity round-trips correctly", function()
      local input = math.huge
      assert.are.equal(roundtrip(input), input)
    end)

    it("D07: negative infinity round-trips correctly", function()
      local input = -math.huge
      assert.are.equal(roundtrip(input), input)
    end)

    it("D08: max exact double integer 2^53 (9007199254740992) round-trips correctly", function()
      local input = 9007199254740992
      assert.are.equal(roundtrip(input), input)
    end)

    it("D09: float 1.5 round-trips correctly (floatstr short path)", function()
      local input = 1.5
      assert.truthy(math.abs(roundtrip(input) - input) < 1e-10)
    end)

  end)

  describe("E. Boolean", function()
    it("E01: true round-trips correctly", function()
      local input = true
      assert.are.equal(roundtrip(input), input)
    end)

    it("E02: false round-trips correctly", function()
      local input = false
      assert.are.equal(roundtrip(input), input)
    end)

    it("E03: true and false produce distinct serializations", function()
      local wires = {}
      wires[#wires + 1] = ser(true)
      wires[#wires + 1] = ser(false)
      for i = 1, #wires do
        for j = i + 1, #wires do
          assert.are_not.equal(wires[i], wires[j])
        end
      end
    end)

  end)

  describe("F. String encoding (embedded)", function()
    it("F01: empty string round-trips correctly", function()
      local input = ""
      assert.are.equal(roundtrip(input), input)
    end)

    it("F02: single char string round-trips correctly", function()
      local input = "a"
      assert.are.equal(roundtrip(input), input)
    end)

    it("F03: two char string round-trips correctly", function()
      local input = "ab"
      assert.are.equal(roundtrip(input), input)
    end)

    it("F04: short 5-char string round-trips correctly", function()
      local input = "hello"
      assert.are.equal(roundtrip(input), input)
    end)

    it("F05: 15-char string (max embedded) round-trips correctly", function()
      local input = "123456789012345"
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("G. String encoding (length-prefixed)", function()
    it("G01: 16-char string (STR_8 path) round-trips correctly", function()
      local input = "1234567890123456"
      assert.are.equal(roundtrip(input), input)
    end)

    it("G02: long 100-char string round-trips correctly", function()
      local input = string.rep("x", 100)
      assert.are.equal(roundtrip(input), input)
    end)

    it("G03: string with all 256 byte values round-trips correctly", function()
      local input = string.char(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199) .. string.char(200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255)
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("H. String refs", function()
    it("H01: repeated string in table round-trips with correct values", function()
      local input = { ["a"] = "hello world", ["b"] = "hello world" }
      local result = roundtrip(input)
      assert.are.equal(result["a"], "hello world")
      assert.are.equal(result["b"], "hello world")
    end)

    it("H02: string repeated 5 times in array round-trips with correct values", function()
      local input = { [1] = "shared_key", [2] = "shared_key", [3] = "shared_key", [4] = "shared_key", [5] = "shared_key" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "shared_key")
      assert.are.equal(result[2], "shared_key")
      assert.are.equal(result[3], "shared_key")
      assert.are.equal(result[4], "shared_key")
      assert.are.equal(result[5], "shared_key")
    end)

    it("H03: short strings (<=2 bytes) not tracked as refs but still round-trip correctly", function()
      local input = { ["a"] = "x", ["b"] = "x", ["c"] = "xy", ["d"] = "xy" }
      local result = roundtrip(input)
      assert.are.equal(result["a"], "x")
      assert.are.equal(result["b"], "x")
      assert.are.equal(result["c"], "xy")
      assert.are.equal(result["d"], "xy")
    end)

  end)

  describe("I. Empty and small tables", function()
    it("I01: empty table round-trips to empty table", function()
      local result = roundtrip({  })
      assert.are.equal(next(result), nil)
    end)

    it("I02: table with 1 key-value pair round-trips correctly", function()
      local input = { ["a"] = 1 }
      local result = roundtrip(input)
      assert.are.equal(result["a"], 1)
    end)

    it("I03: table with 15 entries (embedded max) round-trips all values correctly", function()
      local input = { ["k1"] = 1, ["k2"] = 2, ["k3"] = 3, ["k4"] = 4, ["k5"] = 5, ["k6"] = 6, ["k7"] = 7, ["k8"] = 8, ["k9"] = 9, ["k10"] = 10, ["k11"] = 11, ["k12"] = 12, ["k13"] = 13, ["k14"] = 14, ["k15"] = 15 }
      local result = roundtrip(input)
      assert.are.equal(result["k1"], 1)
      assert.are.equal(result["k2"], 2)
      assert.are.equal(result["k3"], 3)
      assert.are.equal(result["k4"], 4)
      assert.are.equal(result["k5"], 5)
      assert.are.equal(result["k6"], 6)
      assert.are.equal(result["k7"], 7)
      assert.are.equal(result["k8"], 8)
      assert.are.equal(result["k9"], 9)
      assert.are.equal(result["k10"], 10)
      assert.are.equal(result["k11"], 11)
      assert.are.equal(result["k12"], 12)
      assert.are.equal(result["k13"], 13)
      assert.are.equal(result["k14"], 14)
      assert.are.equal(result["k15"], 15)
    end)

  end)

  describe("J. Arrays", function()
    it("J01: single-element array round-trips correctly", function()
      local input = { [1] = "only" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "only")
    end)

    it("J02: simple array [a, b, c] round-trips correctly", function()
      local input = { [1] = "a", [2] = "b", [3] = "c" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "a")
      assert.are.equal(result[2], "b")
      assert.are.equal(result[3], "c")
    end)

    it("J03: integer array [10, 20, 30, 40, 50] round-trips correctly", function()
      local input = { [1] = 10, [2] = 20, [3] = 30, [4] = 40, [5] = 50 }
      local result = roundtrip(input)
      assert.are.equal(result[1], 10)
      assert.are.equal(result[2], 20)
      assert.are.equal(result[3], 30)
      assert.are.equal(result[4], 40)
      assert.are.equal(result[5], 50)
    end)

    it("J04: mixed-type array [str, 42, true, false] round-trips correctly", function()
      local input = { [1] = "str", [2] = 42, [3] = true, [4] = false }
      local result = roundtrip(input)
      assert.are.equal(result[1], "str")
      assert.are.equal(result[2], 42)
      assert.are.equal(result[3], true)
      assert.are.equal(result[4], false)
    end)

    it("J05: 16-element array (ARRAY_8 path) round-trips correctly", function()
      local input = { [1] = 10, [2] = 20, [3] = 30, [4] = 40, [5] = 50, [6] = 60, [7] = 70, [8] = 80, [9] = 90, [10] = 100, [11] = 110, [12] = 120, [13] = 130, [14] = 140, [15] = 150, [16] = 160 }
      local result = roundtrip(input)
      assert.are.equal(result[1], 10)
      assert.are.equal(result[2], 20)
      assert.are.equal(result[3], 30)
      assert.are.equal(result[4], 40)
      assert.are.equal(result[5], 50)
      assert.are.equal(result[6], 60)
      assert.are.equal(result[7], 70)
      assert.are.equal(result[8], 80)
      assert.are.equal(result[9], 90)
      assert.are.equal(result[10], 100)
      assert.are.equal(result[11], 110)
      assert.are.equal(result[12], 120)
      assert.are.equal(result[13], 130)
      assert.are.equal(result[14], 140)
      assert.are.equal(result[15], 150)
      assert.are.equal(result[16], 160)
    end)

  end)

  describe("K. Mixed tables", function()
    it("K01: mixed table with integer and string keys round-trips correctly", function()
      local input = { [1] = "first", [2] = "second", ["x"] = "extra" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "first")
      assert.are.equal(result[2], "second")
      assert.are.equal(result["x"], "extra")
    end)

    it("K02: mixed table with various value types round-trips correctly", function()
      local input = { [1] = "arr1", [2] = "arr2", ["key"] = 99, ["flag"] = true }
      local result = roundtrip(input)
      assert.are.equal(result[1], "arr1")
      assert.are.equal(result[2], "arr2")
      assert.are.equal(result["key"], 99)
      assert.are.equal(result["flag"], true)
    end)

    it("K03: nested table round-trips inner values correctly", function()
      local input = { ["inner"] = { ["x"] = 1, ["y"] = 2 } }
      local result = roundtrip(input)
      -- nested check for inner
      assert.are.equal(result["inner"]["x"], 1)
      assert.are.equal(result["inner"]["y"], 2)
    end)

    it("K04: deeply nested table round-trips leaf value correctly", function()
      local input = { ["a"] = { ["b"] = { ["c"] = { ["d"] = 42 } } } }
      local result = roundtrip(input)
      -- nested check for a
      assert.are.equal(result["a"]["b"]["c"]["d"], 42)
    end)

  end)

  describe("L. Table refs", function()
    it("L01: shared sub-table round-trips with correct values in both references", function()
      local input = { ["a"] = { ["value"] = 99 }, ["b"] = { ["value"] = 99 } }
      local result = roundtrip(input)
      -- nested check for a
      assert.are.equal(result["a"]["value"], 99)
      -- nested check for b
      assert.are.equal(result["b"]["value"], 99)
    end)

    it("L02: deserialized shared table refs point to the same object (mutation test)", function()
      -- Shared table reference identity test
      local shared = { "a", "b" }
      local input = { ["a"] = { ["value"] = 1 }, ["b"] = { ["value"] = 1 } }
      -- In Lua, make both keys point to the same table
      local shared_table = { value = 1 }
      input["a"] = shared_table
      input["b"] = shared_table
      local result = roundtrip(input)
      -- Mutate one, check if both change (same reference)
      result["a"].value = 42
      assert.are.equal(result["b"].value, 42)
    end)

  end)

  describe("M. Variadic Serialize/Deserialize", function()
    it("M01: serialize multiple values (1, hello, true) deserializes all correctly", function()
      local wire = LibSerialize:Serialize(1, "hello", true)
      local ok, v1, v2, v3 = LibSerialize:Deserialize(wire)
      assert.are.equal(ok, true)
      assert.are.equal(v1, 1)
      assert.are.equal(v2, "hello")
      assert.are.equal(v3, true)
    end)

    it("M02: serialize values with nil in middle (1, nil, 3) deserializes all correctly", function()
      local wire = LibSerialize:Serialize(1, nil, 3)
      local ok, v1, v2, v3 = LibSerialize:Deserialize(wire)
      assert.are.equal(ok, true)
      assert.are.equal(v1, 1)
      assert.is_nil(v2)
      assert.are.equal(v3, 3)
    end)

  end)

  describe("N. Error handling", function()
    it("N01: deserializing corrupt data returns a boolean result (ok field)", function()
      local ok, _ = LibSerialize:Deserialize("not valid data \255")
      assert.is_false(ok)
    end)

    it("N02: IsSerializableType returns true for nil, number, string, boolean, table", function()
      assert.truthy(LibSerialize:IsSerializableType(nil))
      assert.truthy(LibSerialize:IsSerializableType(42))
      assert.truthy(LibSerialize:IsSerializableType("hello"))
      assert.truthy(LibSerialize:IsSerializableType(true))
      assert.truthy(LibSerialize:IsSerializableType({  }))
    end)

    it("N03: IsSerializableType returns false for functions", function()
      assert.is_false(LibSerialize:IsSerializableType(function() end))
    end)

  end)

  describe("O. Round-trips (comprehensive)", function()
    it("O01: complex nested structure round-trips all fields correctly", function()
      local input = { ["name"] = "test", ["values"] = { [1] = 1, [2] = 2, [3] = 3 }, ["meta"] = { ["active"] = true, ["count"] = 0 } }
      local result = roundtrip(input)
      assert.are.equal(result["name"], "test")
      -- nested check for meta
      assert.are.equal(result["meta"]["active"], true)
      assert.are.equal(result["meta"]["count"], 0)
    end)

    it("O02: table with boolean keys round-trips correctly", function()
      local input = { [1] = "yes", [0] = "no" }
      local result = roundtrip(input)
      assert.are.equal(result[1], "yes")
      assert.are.equal(result[0], "no")
    end)

    it("O03: table with float key 1.5 round-trips correctly", function()
      local input = { [1.5] = "fractional" }
      local result = roundtrip(input)
      assert.are.equal(result[1.5], "fractional")
    end)

    it("O04: string with embedded null bytes round-trips correctly", function()
      local input = string.char(97, 0, 98, 0, 99)
      assert.are.equal(roundtrip(input), input)
    end)

    it("O05: all 256 byte values in a string round-trip correctly", function()
      local input = string.char(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199) .. string.char(200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255)
      assert.are.equal(roundtrip(input), input)
    end)

  end)

  describe("P. Mixed table + table ref integrity", function()
    it("P01: shared mixed table ref — both keys see array and hash portions", function()
      local hex = "012612621e1529326b65793276616c1261e802"
      local wire = hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end)
      local ok, result = LibSerialize:Deserialize(wire)
      assert.is_true(ok)
      assert.same({ [1] = 10, [2] = 20, ["key"] = "val" }, result["a"])
      assert.same({ [1] = 10, [2] = 20, ["key"] = "val" }, result["b"])
    end)

    it("P02: mixed table then plain table then refs to both — ref indices correct", function()
      local hex = "0146527265665f6d1ec9840c426e616d65526d69786564527265665f7026127905127803126de8021270e803"
      local wire = hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end)
      local ok, result = LibSerialize:Deserialize(wire)
      assert.is_true(ok)
      assert.same({ [1] = 100, [2] = 200, ["name"] = "mixed" }, result["m"])
      assert.same({ ["x"] = 1, ["y"] = 2 }, result["p"])
      assert.same({ [1] = 100, [2] = 200, ["name"] = "mixed" }, result["ref_m"])
      assert.same({ ["x"] = 1, ["y"] = 2 }, result["ref_p"])
    end)

    it("P03: mixed table followed by second table — roundtrip preserves all", function()
      local input = { ["first"] = { [1] = "x", [2] = "y", ["name"] = "mixed1" }, ["second"] = { [1] = "a", [2] = "b", ["name"] = "mixed2" } }
      local result = roundtrip(input)
      -- nested check for first
      assert.are.equal(result["first"][1], "x")
      assert.are.equal(result["first"][2], "y")
      assert.are.equal(result["first"]["name"], "mixed1")
      -- nested check for second
      assert.are.equal(result["second"][1], "a")
      assert.are.equal(result["second"][2], "b")
      assert.are.equal(result["second"]["name"], "mixed2")
    end)

  end)

  describe("Q. Numeric key type preservation", function()
    it("Q01: Lua-serialized array [a,b,c] deserializes with correct values", function()
      local hex = "013a126112621263"
      local wire = hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end)
      local ok, result = LibSerialize:Deserialize(wire)
      assert.is_true(ok)
      assert.are.equal(type(result), "table")
      assert.are.equal("a", result[1])
      assert.are.equal("b", result[2])
      assert.are.equal("c", result[3])
    end)

    it("Q02: Lua-serialized mixed int+string keys deserialize correctly", function()
      local hex = "011e526669727374627365636f6e64426e616d654274657374"
      local wire = hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end)
      local ok, result = LibSerialize:Deserialize(wire)
      assert.is_true(ok)
      assert.are.equal("first", result[1])
      assert.are.equal("second", result[2])
      assert.are.equal("test", result["name"])
    end)

    it("Q03: Lua-serialized table has integer keys not string keys", function()
      local hex = "011e526669727374627365636f6e64426e616d654274657374"
      local wire = hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end)
      local ok, result = LibSerialize:Deserialize(wire)
      assert.is_true(ok)
      assert.are.equal(type(1), "number")
      assert.is_not_nil(result[1])
      assert.are.equal(type(2), "number")
      assert.is_not_nil(result[2])
      assert.is_not_nil(result["name"])
    end)

    it("Q04: mixed integer and string keys roundtrip with correct key types", function()
      local input = { [1] = "first", [2] = "second", ["name"] = "test" }
      local result = roundtrip(input)
      assert.is_not_nil(result[1], "Expected integer key 1")
      assert.is_not_nil(result[2], "Expected integer key 2")
      assert.is_not_nil(result["name"], "Expected string key name")
    end)

    it("Q05: integer-keyed table serializes as array not table-with-string-keys", function()
      local wire = ser({ [1] = "a", [2] = "b" })
      local hex = ""
      for i = 1, #wire do hex = hex .. string.format("%02x", wire:byte(i)) end
      assert.are.equal("012a12611262", hex)
    end)

  end)

  describe("R. Variadic round-trip verification", function()
    it("R01: single value variadic round-trip", function()
      local wire = LibSerialize:Serialize(42)
      local ok, v1 = LibSerialize:Deserialize(wire)
      assert.are.equal(ok, true)
      assert.are.equal(v1, 42)
    end)

    it("R02: four mixed-type values variadic round-trip", function()
      local wire = LibSerialize:Serialize("hello", 42, true, 3.14)
      local ok, v1, v2, v3, v4 = LibSerialize:Deserialize(wire)
      assert.are.equal(ok, true)
      assert.are.equal(v1, "hello")
      assert.are.equal(v2, 42)
      assert.are.equal(v3, true)
      assert.are.equal(v4, 3.14)
    end)

    it("R03: variadic with nil at start and end", function()
      local wire = LibSerialize:Serialize(nil, "hello", nil)
      local ok, v1, v2, v3 = LibSerialize:Deserialize(wire)
      assert.are.equal(ok, true)
      assert.is_nil(v1)
      assert.are.equal(v2, "hello")
      assert.is_nil(v3)
    end)

  end)

  describe("S. Nil wire format", function()
    it("S01: Lua-serialized nil is exactly 01 00", function()
      local wire = ser(nil)
      local hex = ""
      for i = 1, #wire do hex = hex .. string.format("%02x", wire:byte(i)) end
      assert.are.equal("0100", hex)
    end)

  end)

end)
