# Auto-generated by testing/generate-tests.py — DO NOT EDIT
# frozen_string_literal: true

require_relative '../wow_cbor'
require_relative '../pipeline'

RSpec.describe 'WowCbor' do

  describe 'A. Round-trip' do
    it 'A1: string value' do
      input = 'hello world'
      expect(WowCbor.decode(WowCbor.encode(input))).to eq(input)
    end

    it 'A2: integer value' do
      input = 42
      expect(WowCbor.decode(WowCbor.encode(input))).to eq(input)
    end

    it 'A3: boolean true' do
      input = true
      expect(WowCbor.decode(WowCbor.encode(input))).to eq(input)
    end

    it 'A4: null value' do
      input = nil
      expect(WowCbor.decode(WowCbor.encode(input))).to be_nil
    end

    it 'A5: string-keyed object' do
      input = { 'key' => 'value', 'num' => 7 }
      result = WowCbor.decode(WowCbor.encode(input))
      expect(result['key']).to eq('value')
      expect(result['num']).to eq(7)
    end

    it 'A6: array' do
      input = ['a', 'b', 'c']
      expect(WowCbor.decode(WowCbor.encode(input))).to eq(input)
    end

  end

  describe 'B. Byte string conversion' do
    it 'B1: byte string is converted to UTF-8 string' do
      cbor = "\x45hello"
      result = WowCbor.decode(cbor)
      expect(result).to eq('hello')
      expect(result.encoding).to eq(Encoding::UTF_8)
    end

    it 'B2: nested byte string in object is converted' do
      inner = +'world'
      inner.force_encoding(Encoding::BINARY)
      data = { 'key' => inner }
      encoded = WowCbor.encode(data)
      result = WowCbor.decode(encoded)
      expect(result['key']).to eq('world')
    end

    it 'B3: byte strings in list are converted' do
      result = WowCbor.decode(WowCbor.encode(['a', 'b']))
      expect(result).to eq(['a', 'b'])
    end

  end

  describe 'C. Array detection' do
    it 'C1: sequential 1-based int keys converted to array' do
      data = { 1 => 'a', 2 => 'b', 3 => 'c' }
      encoded = WowCbor.encode(data)
      result = WowCbor.decode(encoded)
      expect(result).to eq(['a', 'b', 'c'])
    end

    it 'C2: non-sequential int keys stay as object' do
      data = { 1 => 'a', 3 => 'c' }
      encoded = WowCbor.encode(data)
      result = WowCbor.decode(encoded)
      expect(result).to be_a(Hash)
      expect(result).not_to be_a(Array)
    end

    it 'C3: string-keyed object stays as object' do
      input = { 'a' => 1, 'b' => 2 }
      result = WowCbor.decode(WowCbor.encode(input))
      expect(result).to be_a(Hash)
      expect(result['a']).to eq(1)
      expect(result['b']).to eq(2)
    end

  end

  describe 'D. Plater v2 prefix' do
    it 'D1: encodes with !PLATER:2! prefix' do
      enc = Pipeline.encode(ExportResult.new('plater', 2, { 'x' => 1 }, nil))
      expect(enc).to start_with('!PLATER:2!')
    end

    it 'D2: decodes !PLATER:2! to plater v2' do
      enc = Pipeline.encode(ExportResult.new('plater', 2, { 'x' => 1 }, nil))
      dec = Pipeline.decode(enc)
      expect(dec.addon).to eq('plater')
      expect(dec.version).to eq(2)
    end

    it 'D3: Plater v2 round-trip preserves data' do
      data = { 'profile' => 'Default', 'enabled' => true, 'level' => 5 }
      enc = Pipeline.encode(ExportResult.new('plater', 2, data, nil))
      dec = Pipeline.decode(enc)
      expect(dec.data['profile']).to eq('Default')
      expect(dec.data['enabled']).to eq(true)
      expect(dec.data['level']).to eq(5)
    end

    it 'D4: !PLATER:2! is detected before ! catch-all' do
      enc = Pipeline.encode(ExportResult.new('plater', 2, 'test', nil))
      expect(enc).to start_with('!PLATER:2!')
      dec = Pipeline.decode(enc)
      expect(dec.addon).to eq('plater')
      expect(dec.version).to eq(2)
    end

  end
end
