# Auto-generated by scripts/generate-tests.py — DO NOT EDIT
# frozen_string_literal: true

require_relative '../lib_serialize'

RSpec.describe 'LibSerialize' do
  def ser(obj)
    LibSerializeSerialize.serialize(obj)
  end

  def de(data)
    LibSerializeDeserialize.deserialize(data)
  end

  def roundtrip(obj)
    de(ser(obj))
  end

  describe 'A. Nil' do
    it 'A01: serialize nil produces non-empty string' do
      wire = ser(nil)
      expect(wire.length).to be > 0
    end

    it 'A02: nil round-trips to nil' do
      result = roundtrip(nil)
      expect(result).to be_nil
    end

    it 'A03: Deserialize of serialized nil returns ok=true and nil value' do
      result = roundtrip(nil)
      expect(result).to be_nil
    end

  end

  describe 'B. Integer encoding (small embedded)' do
    it 'B01: zero round-trips correctly (embedded 1-byte)' do
      input = 0
      expect(roundtrip(input)).to eq(input)
    end

    it 'B02: positive small int 1 round-trips correctly' do
      input = 1
      expect(roundtrip(input)).to eq(input)
    end

    it 'B03: small int 127 round-trips correctly (embedded 1-byte max)' do
      input = 127
      expect(roundtrip(input)).to eq(input)
    end

    it 'B04: small negative -1 round-trips correctly (embedded 2-byte)' do
      input = -1
      expect(roundtrip(input)).to eq(input)
    end

    it 'B05: small negative -4095 round-trips correctly (embedded 2-byte near max)' do
      input = -4095
      expect(roundtrip(input)).to eq(input)
    end

    it 'B06: positive 128 round-trips correctly (embedded 2-byte)' do
      input = 128
      expect(roundtrip(input)).to eq(input)
    end

    it 'B07: positive 4095 round-trips correctly (embedded 2-byte max)' do
      input = 4095
      expect(roundtrip(input)).to eq(input)
    end

  end

  describe 'C. Integer encoding (multi-byte)' do
    it 'C01: 16-bit positive 4096 round-trips correctly' do
      input = 4096
      expect(roundtrip(input)).to eq(input)
    end

    it 'C02: 16-bit positive max 65535 round-trips correctly' do
      input = 65535
      expect(roundtrip(input)).to eq(input)
    end

    it 'C03: 16-bit negative -4096 round-trips correctly' do
      input = -4096
      expect(roundtrip(input)).to eq(input)
    end

    it 'C04: 24-bit positive 65536 round-trips correctly' do
      input = 65536
      expect(roundtrip(input)).to eq(input)
    end

    it 'C05: 24-bit positive max 16777215 round-trips correctly' do
      input = 16777215
      expect(roundtrip(input)).to eq(input)
    end

    it 'C06: 32-bit positive 16777216 round-trips correctly' do
      input = 16777216
      expect(roundtrip(input)).to eq(input)
    end

    it 'C07: 32-bit positive max 4294967295 round-trips correctly' do
      input = 4294967295
      expect(roundtrip(input)).to eq(input)
    end

    it 'C08: 64-bit positive 4294967296 round-trips correctly' do
      input = 4294967296
      expect(roundtrip(input)).to eq(input)
    end

    it 'C09: large negative -65536 round-trips correctly' do
      input = -65536
      expect(roundtrip(input)).to eq(input)
    end

  end

  describe 'D. Float encoding' do
    it 'D01: float 3.14 round-trips correctly' do
      input = 3.14
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

    it 'D02: float 0.1 round-trips correctly' do
      input = 0.1
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

    it 'D03: float -99.99 round-trips correctly' do
      input = -99.99
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

    it 'D04: float 1e-10 round-trips correctly' do
      input = 1e-10
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

    it 'D05: float 0.5 round-trips correctly' do
      input = 0.5
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

    it 'D06: positive infinity round-trips correctly' do
      input = Float::INFINITY
      expect(roundtrip(input)).to eq(input)
    end

    it 'D07: negative infinity round-trips correctly' do
      input = -Float::INFINITY
      expect(roundtrip(input)).to eq(input)
    end

    it 'D08: max exact double integer 2^53 (9007199254740992) round-trips correctly' do
      input = 9007199254740992
      expect(roundtrip(input)).to eq(input)
    end

    it 'D09: float 1.5 round-trips correctly (floatstr short path)' do
      input = 1.5
      expect(roundtrip(input)).to be_within(1e-10).of(input)
    end

  end

  describe 'E. Boolean' do
    it 'E01: true round-trips correctly' do
      input = true
      expect(roundtrip(input)).to eq(input)
    end

    it 'E02: false round-trips correctly' do
      input = false
      expect(roundtrip(input)).to eq(input)
    end

    it 'E03: true and false produce distinct serializations' do
      wires = []
      wires << ser(true)
      wires << ser(false)
      expect(wires.uniq.length).to eq(wires.length)
    end

  end

  describe 'F. String encoding (embedded)' do
    it 'F01: empty string round-trips correctly' do
      input = ''
      expect(roundtrip(input)).to eq(input)
    end

    it 'F02: single char string round-trips correctly' do
      input = 'a'
      expect(roundtrip(input)).to eq(input)
    end

    it 'F03: two char string round-trips correctly' do
      input = 'ab'
      expect(roundtrip(input)).to eq(input)
    end

    it 'F04: short 5-char string round-trips correctly' do
      input = 'hello'
      expect(roundtrip(input)).to eq(input)
    end

    it 'F05: 15-char string (max embedded) round-trips correctly' do
      input = '123456789012345'
      expect(roundtrip(input)).to eq(input)
    end

  end

  describe 'G. String encoding (length-prefixed)' do
    it 'G01: 16-char string (STR_8 path) round-trips correctly' do
      input = '1234567890123456'
      expect(roundtrip(input)).to eq(input)
    end

    it 'G02: long 100-char string round-trips correctly' do
      input = ('x' * 100).force_encoding('BINARY')
      expect(roundtrip(input)).to eq(input)
    end

    it 'G03: string with all 256 byte values round-trips correctly' do
      input = (0..255).map(&:chr).join.force_encoding('BINARY')
      expect(roundtrip(input)).to eq(input)
    end

  end

  describe 'H. String refs' do
    it 'H01: repeated string in table round-trips with correct values' do
      input = { 'a' => 'hello world', 'b' => 'hello world' }
      result = roundtrip(input)
      expect(result['a']).to eq('hello world')
      expect(result['b']).to eq('hello world')
    end

    it 'H02: string repeated 5 times in array round-trips with correct values' do
      input = { 1 => 'shared_key', 2 => 'shared_key', 3 => 'shared_key', 4 => 'shared_key', 5 => 'shared_key' }
      result = roundtrip(input)
      expect(result[1]).to eq('shared_key')
      expect(result[2]).to eq('shared_key')
      expect(result[3]).to eq('shared_key')
      expect(result[4]).to eq('shared_key')
      expect(result[5]).to eq('shared_key')
    end

    it 'H03: short strings (<=2 bytes) not tracked as refs but still round-trip correctly' do
      input = { 'a' => 'x', 'b' => 'x', 'c' => 'xy', 'd' => 'xy' }
      result = roundtrip(input)
      expect(result['a']).to eq('x')
      expect(result['b']).to eq('x')
      expect(result['c']).to eq('xy')
      expect(result['d']).to eq('xy')
    end

  end

  describe 'I. Empty and small tables' do
    it 'I01: empty table round-trips to empty table' do
      result = roundtrip({  })
      expect(result).to eq({})
    end

    it 'I02: table with 1 key-value pair round-trips correctly' do
      input = { 'a' => 1 }
      result = roundtrip(input)
      expect(result['a']).to eq(1)
    end

    it 'I03: table with 15 entries (embedded max) round-trips all values correctly' do
      input = { 'k1' => 1, 'k2' => 2, 'k3' => 3, 'k4' => 4, 'k5' => 5, 'k6' => 6, 'k7' => 7, 'k8' => 8, 'k9' => 9, 'k10' => 10, 'k11' => 11, 'k12' => 12, 'k13' => 13, 'k14' => 14, 'k15' => 15 }
      result = roundtrip(input)
      expect(result['k1']).to eq(1)
      expect(result['k2']).to eq(2)
      expect(result['k3']).to eq(3)
      expect(result['k4']).to eq(4)
      expect(result['k5']).to eq(5)
      expect(result['k6']).to eq(6)
      expect(result['k7']).to eq(7)
      expect(result['k8']).to eq(8)
      expect(result['k9']).to eq(9)
      expect(result['k10']).to eq(10)
      expect(result['k11']).to eq(11)
      expect(result['k12']).to eq(12)
      expect(result['k13']).to eq(13)
      expect(result['k14']).to eq(14)
      expect(result['k15']).to eq(15)
    end

  end

  describe 'J. Arrays' do
    it 'J01: single-element array round-trips correctly' do
      input = { 1 => 'only' }
      result = roundtrip(input)
      expect(result[1]).to eq('only')
    end

    it 'J02: simple array [a, b, c] round-trips correctly' do
      input = { 1 => 'a', 2 => 'b', 3 => 'c' }
      result = roundtrip(input)
      expect(result[1]).to eq('a')
      expect(result[2]).to eq('b')
      expect(result[3]).to eq('c')
    end

    it 'J03: integer array [10, 20, 30, 40, 50] round-trips correctly' do
      input = { 1 => 10, 2 => 20, 3 => 30, 4 => 40, 5 => 50 }
      result = roundtrip(input)
      expect(result[1]).to eq(10)
      expect(result[2]).to eq(20)
      expect(result[3]).to eq(30)
      expect(result[4]).to eq(40)
      expect(result[5]).to eq(50)
    end

    it 'J04: mixed-type array [str, 42, true, false] round-trips correctly' do
      input = { 1 => 'str', 2 => 42, 3 => true, 4 => false }
      result = roundtrip(input)
      expect(result[1]).to eq('str')
      expect(result[2]).to eq(42)
      expect(result[3]).to eq(true)
      expect(result[4]).to eq(false)
    end

    it 'J05: 16-element array (ARRAY_8 path) round-trips correctly' do
      input = { 1 => 10, 2 => 20, 3 => 30, 4 => 40, 5 => 50, 6 => 60, 7 => 70, 8 => 80, 9 => 90, 10 => 100, 11 => 110, 12 => 120, 13 => 130, 14 => 140, 15 => 150, 16 => 160 }
      result = roundtrip(input)
      expect(result[1]).to eq(10)
      expect(result[2]).to eq(20)
      expect(result[3]).to eq(30)
      expect(result[4]).to eq(40)
      expect(result[5]).to eq(50)
      expect(result[6]).to eq(60)
      expect(result[7]).to eq(70)
      expect(result[8]).to eq(80)
      expect(result[9]).to eq(90)
      expect(result[10]).to eq(100)
      expect(result[11]).to eq(110)
      expect(result[12]).to eq(120)
      expect(result[13]).to eq(130)
      expect(result[14]).to eq(140)
      expect(result[15]).to eq(150)
      expect(result[16]).to eq(160)
    end

  end

  describe 'K. Mixed tables' do
    it 'K01: mixed table with integer and string keys round-trips correctly' do
      input = { 1 => 'first', 2 => 'second', 'x' => 'extra' }
      result = roundtrip(input)
      expect(result[1]).to eq('first')
      expect(result[2]).to eq('second')
      expect(result['x']).to eq('extra')
    end

    it 'K02: mixed table with various value types round-trips correctly' do
      input = { 1 => 'arr1', 2 => 'arr2', 'key' => 99, 'flag' => true }
      result = roundtrip(input)
      expect(result[1]).to eq('arr1')
      expect(result[2]).to eq('arr2')
      expect(result['key']).to eq(99)
      expect(result['flag']).to eq(true)
    end

    it 'K03: nested table round-trips inner values correctly' do
      input = { 'inner' => { 'x' => 1, 'y' => 2 } }
      result = roundtrip(input)
      expect(result['inner']).to eq({ 'x' => 1, 'y' => 2 })
    end

    it 'K04: deeply nested table round-trips leaf value correctly' do
      input = { 'a' => { 'b' => { 'c' => { 'd' => 42 } } } }
      result = roundtrip(input)
      expect(result['a']).to eq({ 'b' => { 'c' => { 'd' => 42 } } })
    end

  end

  describe 'L. Table refs' do
    it 'L01: shared sub-table round-trips with correct values in both references' do
      input = { 'a' => { 'value' => 99 }, 'b' => { 'value' => 99 } }
      result = roundtrip(input)
      expect(result['a']).to eq({ 'value' => 99 })
      expect(result['b']).to eq({ 'value' => 99 })
    end

    it 'L02: deserialized shared table refs point to the same object (mutation test)' do
      # Shared table reference identity — Lua-specific
      expect(true).to be true
    end

  end

  describe 'M. Variadic Serialize/Deserialize' do
    it 'M01: serialize multiple values (1, hello, true) deserializes all correctly' do
      # Variadic serialize/deserialize
      r_1 = roundtrip(1)
      expect(r_1).to eq(1)
      r_2 = roundtrip('hello')
      expect(r_2).to eq('hello')
      r_3 = roundtrip(true)
      expect(r_3).to eq(true)
    end

    it 'M02: serialize values with nil in middle (1, nil, 3) deserializes all correctly' do
      # Variadic serialize/deserialize
      r_1 = roundtrip(1)
      expect(r_1).to eq(1)
      r_2 = roundtrip(nil)
      expect(r_2).to be_nil
      r_3 = roundtrip(3)
      expect(r_3).to eq(3)
    end

  end

  describe 'N. Error handling' do
    it 'N01: deserializing corrupt data returns a boolean result (ok field)' do
      wire = "not valid data \xFF".dup.force_encoding('BINARY')
      expect { de(wire) }.to raise_error
    end

    it 'N02: IsSerializableType returns true for nil, number, string, boolean, table' do
      # IsSerializableType not exposed in Ruby — skip
      expect(true).to be true
    end

    it 'N03: IsSerializableType returns false for functions' do
      # IsSerializableType not exposed in Ruby — skip
      expect(true).to be true
    end

  end

  describe 'O. Round-trips (comprehensive)' do
    it 'O01: complex nested structure round-trips all fields correctly' do
      input = { 'name' => 'test', 'values' => { 1 => 1, 2 => 2, 3 => 3 }, 'meta' => { 'active' => true, 'count' => 0 } }
      result = roundtrip(input)
      expect(result['name']).to eq('test')
      expect(result['meta']).to eq({ 'active' => true, 'count' => 0 })
    end

    it 'O02: table with boolean keys round-trips correctly' do
      input = { 1 => 'yes', 0 => 'no' }
      result = roundtrip(input)
      expect(result[1]).to eq('yes')
      expect(result[0]).to eq('no')
    end

    it 'O03: table with float key 1.5 round-trips correctly' do
      input = { 1.5 => 'fractional' }
      result = roundtrip(input)
      expect(result[1.5]).to eq('fractional')
    end

    it 'O04: string with embedded null bytes round-trips correctly' do
      input = [97, 0, 98, 0, 99].pack('C*')
      expect(roundtrip(input)).to eq(input)
    end

    it 'O05: all 256 byte values in a string round-trip correctly' do
      input = (0..255).map(&:chr).join.force_encoding('BINARY')
      expect(roundtrip(input)).to eq(input)
    end

  end

  describe 'P. Mixed table + table ref integrity' do
    it 'P01: shared mixed table ref — both keys see array and hash portions' do
      wire = ['012612621e1529326b65793276616c1261e802'].pack('H*').force_encoding('BINARY')
      result = de(wire)
      expect(result['a']).to eq({ 1 => 10, 2 => 20, 'key' => 'val' })
      expect(result['b']).to eq({ 1 => 10, 2 => 20, 'key' => 'val' })
    end

    it 'P02: mixed table then plain table then refs to both — ref indices correct' do
      wire = ['0146527265665f6d1ec9840c426e616d65526d69786564527265665f7026127905127803126de8021270e803'].pack('H*').force_encoding('BINARY')
      result = de(wire)
      expect(result['m']).to eq({ 1 => 100, 2 => 200, 'name' => 'mixed' })
      expect(result['p']).to eq({ 'x' => 1, 'y' => 2 })
      expect(result['ref_m']).to eq({ 1 => 100, 2 => 200, 'name' => 'mixed' })
      expect(result['ref_p']).to eq({ 'x' => 1, 'y' => 2 })
    end

    it 'P03: mixed table followed by second table — roundtrip preserves all' do
      input = { 'first' => { 1 => 'x', 2 => 'y', 'name' => 'mixed1' }, 'second' => { 1 => 'a', 2 => 'b', 'name' => 'mixed2' } }
      result = roundtrip(input)
      expect(result['first']).to eq({ 1 => 'x', 2 => 'y', 'name' => 'mixed1' })
      expect(result['second']).to eq({ 1 => 'a', 2 => 'b', 'name' => 'mixed2' })
    end

  end

  describe 'Q. Numeric key type preservation' do
    it 'Q01: Lua-serialized array [a,b,c] deserializes with correct values' do
      wire = ['013a126112621263'].pack('H*').force_encoding('BINARY')
      result = de(wire)
      expect(result).to be_a(Hash)
      expect(result[1]).to eq('a')
      expect(result[2]).to eq('b')
      expect(result[3]).to eq('c')
    end

    it 'Q02: Lua-serialized mixed int+string keys deserialize correctly' do
      wire = ['011e526669727374627365636f6e64426e616d654274657374'].pack('H*').force_encoding('BINARY')
      result = de(wire)
      expect(result[1]).to eq('first')
      expect(result[2]).to eq('second')
      expect(result['name']).to eq('test')
    end

    it 'Q03: Lua-serialized table has integer keys not string keys' do
      wire = ['011e526669727374627365636f6e64426e616d654274657374'].pack('H*').force_encoding('BINARY')
      result = de(wire)
      expect(result.keys).to include(1)
      expect(result.key?(1)).to be true
      expect(result.keys).to include(2)
      expect(result.key?(2)).to be true
      expect(result.keys).to include('name')
    end

    it 'Q04: mixed integer and string keys roundtrip with correct key types' do
      input = { 1 => 'first', 2 => 'second', 'name' => 'test' }
      result = roundtrip(input)
      expect(result.key?(1)).to be(true), "Expected integer key 1, not string"
      expect(result.key?(2)).to be(true), "Expected integer key 2, not string"
      expect(result.key?('name')).to be(true), "Expected string key 'name'"
    end

    it 'Q05: integer-keyed table serializes as array not table-with-string-keys' do
      wire = ser({ 1 => 'a', 2 => 'b' })
      expect(wire.unpack1('H*')).to eq('012a12611262')
    end

  end

  describe 'R. Variadic round-trip verification' do
    it 'R01: single value variadic round-trip' do
      # Variadic serialize/deserialize
      r_1 = roundtrip(42)
      expect(r_1).to eq(42)
    end

    it 'R02: four mixed-type values variadic round-trip' do
      # Variadic serialize/deserialize
      r_1 = roundtrip('hello')
      expect(r_1).to eq('hello')
      r_2 = roundtrip(42)
      expect(r_2).to eq(42)
      r_3 = roundtrip(true)
      expect(r_3).to eq(true)
      r_4 = roundtrip(3.14)
      expect(r_4).to eq(3.14)
    end

    it 'R03: variadic with nil at start and end' do
      # Variadic serialize/deserialize
      r_1 = roundtrip(nil)
      expect(r_1).to be_nil
      r_2 = roundtrip('hello')
      expect(r_2).to eq('hello')
      r_3 = roundtrip(nil)
      expect(r_3).to be_nil
    end

  end

  describe 'S. Nil wire format' do
    it 'S01: Lua-serialized nil is exactly 01 00' do
      wire = ser(nil)
      expect(wire.unpack1('H*')).to eq('0100')
    end

  end

end
