# Auto-generated by testing/generate-tests.py — DO NOT EDIT
# frozen_string_literal: true

require 'spec_helper'

RSpec.describe 'WowAceSerializer' do
  let(:s) { WowAceSerializer.new }

  describe 'A. String Escaping' do
    it 'A1: NUL (0x00) → ~@' do
      wire = s.serialize(0.chr)
      expect(wire).to include('~@')
    end

    it 'A2a: control 0x01 → ~A' do
      wire = s.serialize(1.chr)
      expect(wire).to include('~A')
    end

    it 'A2b: control 0x0A (LF) → ~J' do
      wire = s.serialize(10.chr)
      expect(wire).to include('~J')
    end

    it 'A2c: control 0x1D → ~]' do
      wire = s.serialize(29.chr)
      expect(wire).to include('~]')
    end

    it 'A3: byte 30 (0x1E) → ~z (special case)' do
      wire = s.serialize(30.chr)
      expect(wire).to include('~z')
    end

    it 'A4: byte 31 (0x1F) → ~_' do
      wire = s.serialize(31.chr)
      expect(wire).to include('~_')
    end

    it 'A5: space (0x20) → ~`' do
      wire = s.serialize(' ')
      expect(wire).to include('~`')
    end

    it 'A6: caret ^ (0x5E) → ~}' do
      wire = s.serialize('^')
      expect(wire).to include('~}')
    end

    it 'A7: tilde ~ (0x7E) → ~|' do
      wire = s.serialize('~')
      expect(wire).to include('~|')
    end

    it 'A8: DEL (0x7F) → ~{' do
      wire = s.serialize(127.chr)
      expect(wire).to include('~{')
    end

    it 'A9: single-pass — no double-escaping' do
      wire = s.serialize([94, 126, 127].pack('C*'))
      expect(wire).to include('~}')
      expect(wire).to include('~|')
      expect(wire).to include('~{')
    end

    it 'A10: printable ASCII passes through' do
      wire = s.serialize('hello')
      expect(wire).to include('^Shello')
    end

  end

  describe 'B. String Unescaping' do
    it 'B11: ~@ → NUL (0x00)' do
      result = s.deserialize('^1^S~@^^')
      expect(result).to eq(0.chr)
    end

    it 'B12a: ~A → chr(1)' do
      result = s.deserialize('^1^S~A^^')
      expect(result).to eq(1.chr)
    end

    it 'B12b: ~J → chr(10)' do
      result = s.deserialize('^1^S~J^^')
      expect(result).to eq(10.chr)
    end

    it 'B13: ~z → byte 30 (0x1E)' do
      result = s.deserialize('^1^S~z^^')
      expect(result).to eq(30.chr)
    end

    it 'B14: ~{ → DEL (0x7F)' do
      result = s.deserialize('^1^S~{^^')
      expect(result).to eq(127.chr)
    end

    it 'B15: ~| → tilde (~)' do
      result = s.deserialize('^1^S~|^^')
      expect(result).to eq('~')
    end

    it 'B16: ~} → caret (^)' do
      result = s.deserialize('^1^S~}^^')
      expect(result).to eq('^')
    end

    it 'B17: round-trip all escapable bytes' do
      input = [0, 1, 10, 29, 30, 31, 32, 94, 127, 126].pack('C*')
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

  end

  describe 'C. Number Serialization' do
    it 'C18: positive integer → ^N42' do
      wire = s.serialize(42)
      expect(wire).to include('^N42')
    end

    it 'C19: negative integer → ^N-42' do
      wire = s.serialize(-42)
      expect(wire).to include('^N-42')
    end

    it 'C20: zero → ^N0' do
      wire = s.serialize(0)
      expect(wire).to include('^N0')
    end

    it 'C21: large integer' do
      wire = s.serialize(1000000)
      expect(wire).to include('^N1000000')
    end

    it 'C22: non-integer float uses ^N (tonumber/tostring check)' do
      wire = s.serialize(3.14)
      expect(wire).to include('^N3.14')
    end

    it 'C23: 3.14 exact wire format' do
      wire = s.serialize(3.14)
      expect(wire).to eq('^1^N3.14^^')
    end

    it 'C24a: 0.1 wire format' do
      wire = s.serialize(0.1)
      expect(wire).to eq('^1^N0.1^^')
    end

    it 'C24b: -99.99 wire format' do
      wire = s.serialize(-99.99)
      expect(wire).to eq('^1^N-99.99^^')
    end

    it 'C24c: 1e-10 wire format' do
      wire = s.serialize(1e-10)
      expect(wire).to eq('^1^N1e-10^^')
    end

    it 'C25: positive infinity → ^N1.#INF or ^Ninf' do
      wire = s.serialize(Float::INFINITY)
      candidates = ["1.#INF", "inf"]
      expect(candidates.any? { |c| wire.include?(c) }).to be true
    end

    it 'C26: negative infinity → ^N-1.#INF or ^N-inf' do
      wire = s.serialize(-Float::INFINITY)
      candidates = ["-1.#INF", "-inf"]
      expect(candidates.any? { |c| wire.include?(c) }).to be true
    end

  end

  describe 'D. Number Deserialization' do
    it 'D27: ^N42 → 42' do
      result = s.deserialize('^1^N42^^')
      expect(result).to eq(42)
    end

    it 'D28: ^N-42 → -42' do
      result = s.deserialize('^1^N-42^^')
      expect(result).to eq(-42)
    end

    it 'D29: ^N3.14 → 3.14' do
      result = s.deserialize('^1^N3.14^^')
      expect(result).to eq(3.14)
    end

    it 'D30: ^N1.#INF → Infinity' do
      result = s.deserialize('^1^N1.#INF^^')
      expect(result).to eq(Float::INFINITY)
    end

    it 'D31: ^N-1.#INF → -Infinity' do
      result = s.deserialize('^1^N-1.#INF^^')
      expect(result).to eq(-Float::INFINITY)
    end

    it 'D32: ^Ninf → Infinity (alternate)' do
      result = s.deserialize('^1^Ninf^^')
      expect(result).to eq(Float::INFINITY)
    end

    it 'D33: ^N-inf → -Infinity (alternate)' do
      result = s.deserialize('^1^N-inf^^')
      expect(result).to eq(-Float::INFINITY)
    end

    it 'D34: ^F<m>^f<e> → correct float' do
      result = s.deserialize('^1^F4503599627370496^f-53^^')
      expect(result).to eq(0.5)
    end

  end

  describe 'E. Float Round-trips' do
    it 'E35: round-trip 3.14' do
      input = 3.14
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E36: round-trip 0.1' do
      input = 0.1
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E37: round-trip 123.456' do
      input = 123.456
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E38: round-trip -99.99' do
      input = -99.99
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E39: round-trip 1e-10' do
      input = 1e-10
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E40: round-trip very small float (min normal)' do
      input = 2.2250738585072014e-308
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'E41: round-trip very large float' do
      input = 1.7976931348623157e+308
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

  end

  describe 'F. Boolean' do
    it 'F42: true → ^B' do
      wire = s.serialize(true)
      expect(wire).to include('^B')
    end

    it 'F43: false → ^b' do
      wire = s.serialize(false)
      expect(wire).to include('^b')
    end

    it 'F44: ^B → true' do
      result = s.deserialize('^1^B^^')
      expect(result).to eq(true)
    end

    it 'F45: ^b → false' do
      result = s.deserialize('^1^b^^')
      expect(result).to eq(false)
    end

  end

  describe 'G. Nil' do
    it 'G46: nil → ^Z' do
      wire = s.serialize(nil)
      expect(wire).to include('^Z')
    end

    it 'G47: ^Z → nil' do
      result = s.deserialize('^1^Z^^')
      expect(result).to eq(nil)
    end

  end

  describe 'H. Table Serialization' do
    it 'H48: empty table → ^T^t' do
      wire = s.serialize({  })
      expect(wire).to include('^T^t')
    end

    it 'H49: single string key-value pair' do
      wire = s.serialize({ 'a' => 1 })
      expect(wire).to include('^T')
      expect(wire).to include('^Sa')
      expect(wire).to include('^N1')
      expect(wire).to include('^t')
    end

    it 'H50: multiple key-value pairs' do
      wire = s.serialize({ 'a' => 1, 'b' => 2 })
      expect(wire).to include('^T')
      expect(wire).to include('^t')
    end

    it 'H51: nested table' do
      wire = s.serialize({ 'inner' => { 'x' => 1 } })
      count = wire.scan('^T').length
      expect(count).to eq(2)
    end

    it 'H52: array → 1-based integer keys' do
      wire = s.serialize(['a', 'b', 'c'])
      expect(wire).to include('^N1')
      expect(wire).to include('^Sa')
      expect(wire).to include('^N2')
      expect(wire).to include('^Sb')
      expect(wire).to include('^N3')
      expect(wire).to include('^Sc')
    end

    it 'H53: mixed table (integer + string keys)' do
      wire = s.serialize({ 1 => 'a', 'x' => 'b' })
      expect(wire).to include('^T')
      expect(wire).to include('^t')
    end

  end

  describe 'I. Array Detection' do
    it 'I54: sequential 1-based keys → array' do
      input = { 1 => 'a', 2 => 'b', 3 => 'c' }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result[1]).to eq('a')
      expect(result[2]).to eq('b')
      expect(result[3]).to eq('c')
    end

    it 'I55: non-sequential keys → object' do
      input = { 1 => 'a', 3 => 'c' }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result[1]).to eq('a')
      expect(result[3]).to eq('c')
    end

    it 'I56: string keys → object' do
      input = { 'x' => 1, 'y' => 2 }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result['x']).to eq(1)
      expect(result['y']).to eq(2)
    end

    it 'I57: single element' do
      input = { 1 => 'only' }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result[1]).to eq('only')
    end

    it 'I58: empty table → empty' do
      input = {  }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq({})
    end

  end

  describe 'J. Framing' do
    it 'J59: output starts with ^1 and ends with ^^' do
      wire = s.serialize('hello')
      expect(wire).to start_with('^1')
      expect(wire).to end_with('^^')
    end

    it 'J62: control chars stripped from input' do
      result = s.deserialize("^1\x09\x0A^Shello\x0D\x0A^^")
      expect(result).to eq('hello')
    end

  end

  describe 'K. Error Handling' do
    it 'J60: missing ^1 prefix → error' do
      expect { s.deserialize('^Shello^^') }.to raise_error
    end

    it 'K64: empty string → error' do
      expect { s.deserialize('') }.to raise_error
    end

    it 'K65: missing ^^ terminator → error' do
      expect { s.deserialize('^1^Shello') }.to raise_error
    end

  end

  describe 'L. Round-trips' do
    it 'L66: plain ASCII string' do
      input = 'hello world test'
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'L67: all special chars' do
      input = [0, 1, 30, 31, 32, 94, 126, 127].pack('C*')
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'L68: integer' do
      input = 12345
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'L69: float' do
      input = 3.14
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'L70: boolean' do
      input_1 = true
      wire_1 = s.serialize(input_1)
      result_1 = s.deserialize(wire_1)
      expect(result_1).to eq(input_1)
      input_2 = false
      wire_2 = s.serialize(input_2)
      result_2 = s.deserialize(wire_2)
      expect(result_2).to eq(input_2)
    end

    it 'L71: nil' do
      input = nil
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'L72: nested table/array' do
      input = { 1 => 1, 2 => { 1 => 2, 2 => 3 } }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result[1]).to eq(1)
    end

    it 'L73: mixed-type table' do
      input = { 'n' => 42, 'f' => 3.14, 'b' => true, 's' => 'hello' }
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result['n']).to eq(42)
      expect(result['f']).to eq(3.14)
      expect(result['b']).to eq(true)
      expect(result['s']).to eq('hello')
    end

  end

  describe 'L2. Fixture Wire-Format Tests' do
    it 'L74: simple array of two strings — exact wire' do
      wire = s.serialize({ 1 => 'a', 2 => 'b' })
      expect(wire).to eq('^1^T^N1^Sa^N2^Sb^t^^')
    end

    it 'L75: simple array of two strings — deserialize' do
      result = s.deserialize('^1^T^N1^Sa^N2^Sb^t^^')
      expect(result).to eq({ 1 => 'a', 2 => 'b' })
    end

    it 'L76: array of three mixed values — exact wire' do
      wire = s.serialize({ 1 => 'hello', 2 => 42, 3 => true })
      expect(wire).to eq('^1^T^N1^Shello^N2^N42^N3^B^t^^')
    end

    it 'L77: array of three mixed values — deserialize' do
      result = s.deserialize('^1^T^N1^Shello^N2^N42^N3^B^t^^')
      expect(result).to eq({ 1 => 'hello', 2 => 42, 3 => true })
    end

    it 'L78: nested array — exact wire' do
      wire = s.serialize({ 1 => { 1 => 'a', 2 => 'b' }, 2 => 'c' })
      expect(wire).to eq('^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^')
    end

    it 'L79: nested array — deserialize' do
      result = s.deserialize('^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^')
      expect(result).to eq({ 1 => { 1 => 'a', 2 => 'b' }, 2 => 'c' })
    end

    it 'L80: array with null values — exact wire' do
      wire = s.serialize({ 1 => nil, 2 => nil, 3 => nil, 4 => 'test' })
      expect(wire).to eq('^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^')
    end

    it 'L81: array with null values — deserialize' do
      result = s.deserialize('^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^')
      expect(result).to eq({ 1 => nil, 2 => nil, 3 => nil, 4 => 'test' })
    end

    it 'L82: nested structure from protocol spec — deserialize only' do
      result = s.deserialize('^1^T^Shello^Sworld^Stest^N123^Snested^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^t^^')
      expect(result).to eq({ 'hello' => 'world', 'test' => 123, 'nested' => { 1 => nil, 2 => nil, 3 => nil, 4 => 'test' } })
    end

    it 'L83: mixed table string and integer keys — deserialize only' do
      result = s.deserialize('^1^T^Shello^Sworld^Sn^N42^t^^')
      expect(result).to eq({ 'hello' => 'world', 'n' => 42 })
    end

  end

  describe 'M. Float wire format consistency' do
    it 'M84: 3.14 uses ^N path (not ^F)' do
      wire = s.serialize(3.14)
      expect(wire).to include('^N3.14')
    end

    it 'M85: very small float 1e-10 uses ^N path' do
      wire = s.serialize(1e-10)
      expect(wire).to include('^N')
    end

    it 'M86: 0.5 uses ^N path' do
      wire = s.serialize(0.5)
      expect(wire).to include('^N0.5')
    end

    it 'M87: extreme float 2.2250738585072014e-308 round-trips correctly' do
      input = 2.2250738585072014e-308
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to be_within(1e-10).of(input)
    end

    it 'M88: extreme float 2.2250738585072014e-308 uses ^F path (%.14g loses precision)' do
      wire = s.serialize(2.2250738585072014e-308)
      expect(wire).to include('^F')
    end

  end

  describe 'N. Escape edge cases' do
    it 'N88a: invalid escape ~> (ord 62, would produce negative byte) is rejected' do
      expect { s.deserialize('^1^S~>^^') }.to raise_error
    end

    it 'N88b: invalid escape ~# (ord 35, would produce negative byte) is rejected' do
      expect { s.deserialize('^1^S~#^^') }.to raise_error
    end

    it 'N88c: all control bytes 0x01-0x1D round-trip correctly' do
      input = (1..29).map(&:chr).join
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'N89: all escapable bytes combined in one string round-trip' do
      input = [0, 1, 10, 29, 30, 31, 32, 94, 126, 127].pack('C*')
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

    it 'N90: high bytes 0x80-0xFF pass through unescaped' do
      input = (128..255).map(&:chr).join
      wire = s.serialize(input)
      result = s.deserialize(wire)
      expect(result).to eq(input)
    end

  end

end
