// Auto-generated by testing/generate-tests.py — DO NOT EDIT
import { test, describe, expect } from "bun:test";
import WowAceSerializer from "../lib/WowAceSerializer.js";
import WowAceDeserializer from "../lib/WowAceDeserializer.js";

describe("A. String Escaping", () => {
  test("A1: NUL (0x00) → ~@", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(0));
    expect(wire.includes("~@")).toBe(true);
  });
  test("A2a: control 0x01 → ~A", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(1));
    expect(wire.includes("~A")).toBe(true);
  });
  test("A2b: control 0x0A (LF) → ~J", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(10));
    expect(wire.includes("~J")).toBe(true);
  });
  test("A2c: control 0x1D → ~]", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(29));
    expect(wire.includes("~]")).toBe(true);
  });
  test("A3: byte 30 (0x1E) → ~z (special case)", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(30));
    expect(wire.includes("~z")).toBe(true);
  });
  test("A4: byte 31 (0x1F) → ~_", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(31));
    expect(wire.includes("~_")).toBe(true);
  });
  test("A5: space (0x20) → ~`", () => {
    const wire = WowAceSerializer.serialize(" ");
    expect(wire.includes("~`")).toBe(true);
  });
  test("A6: caret ^ (0x5E) → ~}", () => {
    const wire = WowAceSerializer.serialize("^");
    expect(wire.includes("~}")).toBe(true);
  });
  test("A7: tilde ~ (0x7E) → ~|", () => {
    const wire = WowAceSerializer.serialize("~");
    expect(wire.includes("~|")).toBe(true);
  });
  test("A8: DEL (0x7F) → ~{", () => {
    const wire = WowAceSerializer.serialize(String.fromCharCode(127));
    expect(wire.includes("~{")).toBe(true);
  });
  test("A9: single-pass — no double-escaping", () => {
    const wire = WowAceSerializer.serialize(
      [94, 126, 127].map((b) => String.fromCharCode(b)).join(""),
    );
    expect(wire.includes("~}")).toBe(true);
    expect(wire.includes("~|")).toBe(true);
    expect(wire.includes("~{")).toBe(true);
  });
  test("A10: printable ASCII passes through", () => {
    const wire = WowAceSerializer.serialize("hello");
    expect(wire.includes("^Shello")).toBe(true);
  });
});

describe("B. String Unescaping", () => {
  test("B11: ~@ → NUL (0x00)", () => {
    const result = new WowAceDeserializer("^1^S~@^^").deserialize();
    expect(result).toEqual(String.fromCharCode(0));
  });
  test("B12a: ~A → chr(1)", () => {
    const result = new WowAceDeserializer("^1^S~A^^").deserialize();
    expect(result).toEqual(String.fromCharCode(1));
  });
  test("B12b: ~J → chr(10)", () => {
    const result = new WowAceDeserializer("^1^S~J^^").deserialize();
    expect(result).toEqual(String.fromCharCode(10));
  });
  test("B13: ~z → byte 30 (0x1E)", () => {
    const result = new WowAceDeserializer("^1^S~z^^").deserialize();
    expect(result).toEqual(String.fromCharCode(30));
  });
  test("B14: ~{ → DEL (0x7F)", () => {
    const result = new WowAceDeserializer("^1^S~{^^").deserialize();
    expect(result).toEqual(String.fromCharCode(127));
  });
  test("B15: ~| → tilde (~)", () => {
    const result = new WowAceDeserializer("^1^S~|^^").deserialize();
    expect(result).toEqual("~");
  });
  test("B16: ~} → caret (^)", () => {
    const result = new WowAceDeserializer("^1^S~}^^").deserialize();
    expect(result).toEqual("^");
  });
  test("B17: round-trip all escapable bytes", () => {
    const input = [0, 1, 10, 29, 30, 31, 32, 94, 127, 126]
      .map((b) => String.fromCharCode(b))
      .join("");
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
});

describe("C. Number Serialization", () => {
  test("C18: positive integer → ^N42", () => {
    const wire = WowAceSerializer.serialize(42);
    expect(wire.includes("^N42")).toBe(true);
  });
  test("C19: negative integer → ^N-42", () => {
    const wire = WowAceSerializer.serialize(-42);
    expect(wire.includes("^N-42")).toBe(true);
  });
  test("C20: zero → ^N0", () => {
    const wire = WowAceSerializer.serialize(0);
    expect(wire.includes("^N0")).toBe(true);
  });
  test("C21: large integer", () => {
    const wire = WowAceSerializer.serialize(1000000);
    expect(wire.includes("^N1000000")).toBe(true);
  });
  test("C22: non-integer float uses ^N (tonumber/tostring check)", () => {
    const wire = WowAceSerializer.serialize(3.14);
    expect(wire.includes("^N3.14")).toBe(true);
  });
  test("C23: 3.14 exact wire format", () => {
    const wire = WowAceSerializer.serialize(3.14);
    expect(wire).toBe("^1^N3.14^^");
  });
  test("C24a: 0.1 wire format", () => {
    const wire = WowAceSerializer.serialize(0.1);
    expect(wire).toBe("^1^N0.1^^");
  });
  test("C24b: -99.99 wire format", () => {
    const wire = WowAceSerializer.serialize(-99.99);
    expect(wire).toBe("^1^N-99.99^^");
  });
  test("C24c: 1e-10 wire format", () => {
    const wire = WowAceSerializer.serialize(1e-10);
    expect(wire).toBe("^1^N1e-10^^");
  });
  test("C25: positive infinity → ^N1.#INF or ^Ninf", () => {
    const wire = WowAceSerializer.serialize(Infinity);
    const candidates = ["1.#INF", "inf"];
    expect(candidates.some((c) => wire.includes(c))).toBe(true);
  });
  test("C26: negative infinity → ^N-1.#INF or ^N-inf", () => {
    const wire = WowAceSerializer.serialize(-Infinity);
    const candidates = ["-1.#INF", "-inf"];
    expect(candidates.some((c) => wire.includes(c))).toBe(true);
  });
});

describe("D. Number Deserialization", () => {
  test("D27: ^N42 → 42", () => {
    const result = new WowAceDeserializer("^1^N42^^").deserialize();
    expect(result).toEqual(42);
  });
  test("D28: ^N-42 → -42", () => {
    const result = new WowAceDeserializer("^1^N-42^^").deserialize();
    expect(result).toEqual(-42);
  });
  test("D29: ^N3.14 → 3.14", () => {
    const result = new WowAceDeserializer("^1^N3.14^^").deserialize();
    expect(result).toEqual(3.14);
  });
  test("D30: ^N1.#INF → Infinity", () => {
    const result = new WowAceDeserializer("^1^N1.#INF^^").deserialize();
    expect(result).toEqual(Infinity);
  });
  test("D31: ^N-1.#INF → -Infinity", () => {
    const result = new WowAceDeserializer("^1^N-1.#INF^^").deserialize();
    expect(result).toEqual(-Infinity);
  });
  test("D32: ^Ninf → Infinity (alternate)", () => {
    const result = new WowAceDeserializer("^1^Ninf^^").deserialize();
    expect(result).toEqual(Infinity);
  });
  test("D33: ^N-inf → -Infinity (alternate)", () => {
    const result = new WowAceDeserializer("^1^N-inf^^").deserialize();
    expect(result).toEqual(-Infinity);
  });
  test("D34: ^F<m>^f<e> → correct float", () => {
    const result = new WowAceDeserializer(
      "^1^F4503599627370496^f-53^^",
    ).deserialize();
    expect(result).toEqual(0.5);
  });
});

describe("E. Float Round-trips", () => {
  test("E35: round-trip 3.14", () => {
    const input = 3.14;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E36: round-trip 0.1", () => {
    const input = 0.1;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E37: round-trip 123.456", () => {
    const input = 123.456;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E38: round-trip -99.99", () => {
    const input = -99.99;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E39: round-trip 1e-10", () => {
    const input = 1e-10;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E40: round-trip very small float (min normal)", () => {
    const input = 2.2250738585072014e-308;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("E41: round-trip very large float", () => {
    const input = 1.7976931348623157e308;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
});

describe("F. Boolean", () => {
  test("F42: true → ^B", () => {
    const wire = WowAceSerializer.serialize(true);
    expect(wire.includes("^B")).toBe(true);
  });
  test("F43: false → ^b", () => {
    const wire = WowAceSerializer.serialize(false);
    expect(wire.includes("^b")).toBe(true);
  });
  test("F44: ^B → true", () => {
    const result = new WowAceDeserializer("^1^B^^").deserialize();
    expect(result).toEqual(true);
  });
  test("F45: ^b → false", () => {
    const result = new WowAceDeserializer("^1^b^^").deserialize();
    expect(result).toEqual(false);
  });
});

describe("G. Nil", () => {
  test("G46: nil → ^Z", () => {
    const wire = WowAceSerializer.serialize(null);
    expect(wire.includes("^Z")).toBe(true);
  });
  test("G47: ^Z → nil", () => {
    const result = new WowAceDeserializer("^1^Z^^").deserialize();
    expect(result).toEqual(null);
  });
});

describe("H. Table Serialization", () => {
  test("H48: empty table → ^T^t", () => {
    const wire = WowAceSerializer.serialize({});
    expect(wire.includes("^T^t")).toBe(true);
  });
  test("H49: single string key-value pair", () => {
    const wire = WowAceSerializer.serialize({ a: 1 });
    expect(wire.includes("^T")).toBe(true);
    expect(wire.includes("^Sa")).toBe(true);
    expect(wire.includes("^N1")).toBe(true);
    expect(wire.includes("^t")).toBe(true);
  });
  test("H50: multiple key-value pairs", () => {
    const wire = WowAceSerializer.serialize({ a: 1, b: 2 });
    expect(wire.includes("^T")).toBe(true);
    expect(wire.includes("^t")).toBe(true);
  });
  test("H51: nested table", () => {
    const wire = WowAceSerializer.serialize({ inner: { x: 1 } });
    const count = wire.split("^T").length - 1;
    expect(count).toBe(2);
  });
  test("H52: array → 1-based integer keys", () => {
    const wire = WowAceSerializer.serialize(["a", "b", "c"]);
    expect(wire.includes("^N1")).toBe(true);
    expect(wire.includes("^Sa")).toBe(true);
    expect(wire.includes("^N2")).toBe(true);
    expect(wire.includes("^Sb")).toBe(true);
    expect(wire.includes("^N3")).toBe(true);
    expect(wire.includes("^Sc")).toBe(true);
  });
  test("H53: mixed table (integer + string keys)", () => {
    const wire = WowAceSerializer.serialize({ 1: "a", x: "b" });
    expect(wire.includes("^T")).toBe(true);
    expect(wire.includes("^t")).toBe(true);
  });
});

describe("I. Array Detection", () => {
  test("I54: sequential 1-based keys → array", () => {
    const input = { 1: "a", 2: "b", 3: "c" };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result[1]).toEqual("a");
    expect(result[2]).toEqual("b");
    expect(result[3]).toEqual("c");
  });
  test("I55: non-sequential keys → object", () => {
    const input = { 1: "a", 3: "c" };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result[1]).toEqual("a");
    expect(result[3]).toEqual("c");
  });
  test("I56: string keys → object", () => {
    const input = { x: 1, y: 2 };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result["x"]).toEqual(1);
    expect(result["y"]).toEqual(2);
  });
  test("I57: single element", () => {
    const input = { 1: "only" };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result[1]).toEqual("only");
  });
  test("I58: empty table → empty", () => {
    const input = {};
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual({});
  });
});

describe("J. Framing", () => {
  test("J59: output starts with ^1 and ends with ^^", () => {
    const wire = WowAceSerializer.serialize("hello");
    expect(wire.startsWith("^1")).toBe(true);
    expect(wire.endsWith("^^")).toBe(true);
  });
  test("J62: control chars stripped from input", () => {
    const result = new WowAceDeserializer(
      "^1\x09\x0a^Shello\x0d\x0a^^",
    ).deserialize();
    expect(result).toEqual("hello");
  });
});

describe("K. Error Handling", () => {
  test("J60: missing ^1 prefix → error", () => {
    expect(() => {
      new WowAceDeserializer("^Shello^^").deserialize();
    }).toThrow();
  });
  test("K64: empty string → error", () => {
    expect(() => {
      new WowAceDeserializer("").deserialize();
    }).toThrow();
  });
  test("K65: missing ^^ terminator → error", () => {
    expect(() => {
      new WowAceDeserializer("^1^Shello").deserialize();
    }).toThrow();
  });
});

describe("L. Round-trips", () => {
  test("L66: plain ASCII string", () => {
    const input = "hello world test";
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("L67: all special chars", () => {
    const input = [0, 1, 30, 31, 32, 94, 126, 127]
      .map((b) => String.fromCharCode(b))
      .join("");
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("L68: integer", () => {
    const input = 12345;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("L69: float", () => {
    const input = 3.14;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("L70: boolean", () => {
    {
      const input = true;
      const wire = WowAceSerializer.serialize(input);
      const result = new WowAceDeserializer(wire).deserialize();
      expect(result).toEqual(input);
    }
    {
      const input = false;
      const wire = WowAceSerializer.serialize(input);
      const result = new WowAceDeserializer(wire).deserialize();
      expect(result).toEqual(input);
    }
  });
  test("L71: nil", () => {
    const input = null;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("L72: nested table/array", () => {
    const input = { 1: 1, 2: { 1: 2, 2: 3 } };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result[1]).toEqual(1);
  });
  test("L73: mixed-type table", () => {
    const input = { n: 42, f: 3.14, b: true, s: "hello" };
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result["n"]).toEqual(42);
    expect(result["f"]).toEqual(3.14);
    expect(result["b"]).toEqual(true);
    expect(result["s"]).toEqual("hello");
  });
});

describe("L2. Fixture Wire-Format Tests", () => {
  test("L74: simple array of two strings — exact wire", () => {
    const wire = WowAceSerializer.serialize({ 1: "a", 2: "b" });
    expect(wire).toBe("^1^T^N1^Sa^N2^Sb^t^^");
  });
  test("L75: simple array of two strings — deserialize", () => {
    const result = new WowAceDeserializer("^1^T^N1^Sa^N2^Sb^t^^").deserialize();
    expect(result).toEqual({ 1: "a", 2: "b" });
  });
  test("L76: array of three mixed values — exact wire", () => {
    const wire = WowAceSerializer.serialize({ 1: "hello", 2: 42, 3: true });
    expect(wire).toBe("^1^T^N1^Shello^N2^N42^N3^B^t^^");
  });
  test("L77: array of three mixed values — deserialize", () => {
    const result = new WowAceDeserializer(
      "^1^T^N1^Shello^N2^N42^N3^B^t^^",
    ).deserialize();
    expect(result).toEqual({ 1: "hello", 2: 42, 3: true });
  });
  test("L78: nested array — exact wire", () => {
    const wire = WowAceSerializer.serialize({ 1: { 1: "a", 2: "b" }, 2: "c" });
    expect(wire).toBe("^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^");
  });
  test("L79: nested array — deserialize", () => {
    const result = new WowAceDeserializer(
      "^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^",
    ).deserialize();
    expect(result).toEqual({ 1: { 1: "a", 2: "b" }, 2: "c" });
  });
  test("L80: array with null values — exact wire", () => {
    const wire = WowAceSerializer.serialize({
      1: null,
      2: null,
      3: null,
      4: "test",
    });
    expect(wire).toBe("^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^");
  });
  test("L81: array with null values — deserialize", () => {
    const result = new WowAceDeserializer(
      "^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^",
    ).deserialize();
    expect(result).toEqual({ 1: null, 2: null, 3: null, 4: "test" });
  });
  test("L82: nested structure from protocol spec — deserialize only", () => {
    const result = new WowAceDeserializer(
      "^1^T^Shello^Sworld^Stest^N123^Snested^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^t^^",
    ).deserialize();
    expect(result).toEqual({
      hello: "world",
      test: 123,
      nested: { 1: null, 2: null, 3: null, 4: "test" },
    });
  });
  test("L83: mixed table string and integer keys — deserialize only", () => {
    const result = new WowAceDeserializer(
      "^1^T^Shello^Sworld^Sn^N42^t^^",
    ).deserialize();
    expect(result).toEqual({ hello: "world", n: 42 });
  });
});

describe("M. Float wire format consistency", () => {
  test("M84: 3.14 uses ^N path (not ^F)", () => {
    const wire = WowAceSerializer.serialize(3.14);
    expect(wire.includes("^N3.14")).toBe(true);
  });
  test("M85: very small float 1e-10 uses ^N path", () => {
    const wire = WowAceSerializer.serialize(1e-10);
    expect(wire.includes("^N")).toBe(true);
  });
  test("M86: 0.5 uses ^N path", () => {
    const wire = WowAceSerializer.serialize(0.5);
    expect(wire.includes("^N0.5")).toBe(true);
  });
  test("M87: extreme float 2.2250738585072014e-308 round-trips correctly", () => {
    const input = 2.2250738585072014e-308;
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("M88: extreme float 2.2250738585072014e-308 uses ^F path (%.14g loses precision)", () => {
    const wire = WowAceSerializer.serialize(2.2250738585072014e-308);
    expect(wire.includes("^F")).toBe(true);
  });
});

describe("N. Escape edge cases", () => {
  test("N88a: invalid escape ~> (ord 62, would produce negative byte) is rejected", () => {
    expect(() => {
      new WowAceDeserializer("^1^S~>^^").deserialize();
    }).toThrow();
  });
  test("N88b: invalid escape ~# (ord 35, would produce negative byte) is rejected", () => {
    expect(() => {
      new WowAceDeserializer("^1^S~#^^").deserialize();
    }).toThrow();
  });
  test("N88c: all control bytes 0x01-0x1D round-trip correctly", () => {
    const input = Array.from({ length: 29 }, (_, i) =>
      String.fromCharCode(i + 1),
    ).join("");
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("N89: all escapable bytes combined in one string round-trip", () => {
    const input = [0, 1, 10, 29, 30, 31, 32, 94, 126, 127]
      .map((b) => String.fromCharCode(b))
      .join("");
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
  test("N90: high bytes 0x80-0xFF pass through unescaped", () => {
    const input = Array.from({ length: 128 }, (_, i) =>
      String.fromCharCode(i + 128),
    ).join("");
    const wire = WowAceSerializer.serialize(input);
    const result = new WowAceDeserializer(wire).deserialize();
    expect(result).toEqual(input);
  });
});
