// Auto-generated by testing/generate-tests.py — DO NOT EDIT
'use strict';
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const WowAceSerializer = require('../lib/WowAceSerializer');
const WowAceDeserializer = require('../lib/WowAceDeserializer');

describe('A. String Escaping', () => {
    test('A1: NUL (0x00) → ~@', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(0));
        assert.ok(wire.includes('~@'), 'Expected wire to contain ~@, got: ' + wire);
    });
    test('A2a: control 0x01 → ~A', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(1));
        assert.ok(wire.includes('~A'), 'Expected wire to contain ~A, got: ' + wire);
    });
    test('A2b: control 0x0A (LF) → ~J', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(10));
        assert.ok(wire.includes('~J'), 'Expected wire to contain ~J, got: ' + wire);
    });
    test('A2c: control 0x1D → ~]', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(29));
        assert.ok(wire.includes('~]'), 'Expected wire to contain ~], got: ' + wire);
    });
    test('A3: byte 30 (0x1E) → ~z (special case)', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(30));
        assert.ok(wire.includes('~z'), 'Expected wire to contain ~z, got: ' + wire);
    });
    test('A4: byte 31 (0x1F) → ~_', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(31));
        assert.ok(wire.includes('~_'), 'Expected wire to contain ~_, got: ' + wire);
    });
    test('A5: space (0x20) → ~`', () => {
        const wire = WowAceSerializer.serialize(' ');
        assert.ok(wire.includes('~`'), 'Expected wire to contain ~`, got: ' + wire);
    });
    test('A6: caret ^ (0x5E) → ~}', () => {
        const wire = WowAceSerializer.serialize('^');
        assert.ok(wire.includes('~}'), 'Expected wire to contain ~}, got: ' + wire);
    });
    test('A7: tilde ~ (0x7E) → ~|', () => {
        const wire = WowAceSerializer.serialize('~');
        assert.ok(wire.includes('~|'), 'Expected wire to contain ~|, got: ' + wire);
    });
    test('A8: DEL (0x7F) → ~{', () => {
        const wire = WowAceSerializer.serialize(String.fromCharCode(127));
        assert.ok(wire.includes('~{'), 'Expected wire to contain ~{, got: ' + wire);
    });
    test('A9: single-pass — no double-escaping', () => {
        const wire = WowAceSerializer.serialize([94, 126, 127].map(b => String.fromCharCode(b)).join(''));
        assert.ok(wire.includes('~}'), 'Expected wire to contain ~}, got: ' + wire);
        assert.ok(wire.includes('~|'), 'Expected wire to contain ~|, got: ' + wire);
        assert.ok(wire.includes('~{'), 'Expected wire to contain ~{, got: ' + wire);
    });
    test('A10: printable ASCII passes through', () => {
        const wire = WowAceSerializer.serialize('hello');
        assert.ok(wire.includes('^Shello'), 'Expected wire to contain ^Shello, got: ' + wire);
    });
});

describe('B. String Unescaping', () => {
    test('B11: ~@ → NUL (0x00)', () => {
        const result = new WowAceDeserializer('^1^S~@^^').deserialize();
        assert.deepStrictEqual(result, String.fromCharCode(0));
    });
    test('B12a: ~A → chr(1)', () => {
        const result = new WowAceDeserializer('^1^S~A^^').deserialize();
        assert.deepStrictEqual(result, String.fromCharCode(1));
    });
    test('B12b: ~J → chr(10)', () => {
        const result = new WowAceDeserializer('^1^S~J^^').deserialize();
        assert.deepStrictEqual(result, String.fromCharCode(10));
    });
    test('B13: ~z → byte 30 (0x1E)', () => {
        const result = new WowAceDeserializer('^1^S~z^^').deserialize();
        assert.deepStrictEqual(result, String.fromCharCode(30));
    });
    test('B14: ~{ → DEL (0x7F)', () => {
        const result = new WowAceDeserializer('^1^S~{^^').deserialize();
        assert.deepStrictEqual(result, String.fromCharCode(127));
    });
    test('B15: ~| → tilde (~)', () => {
        const result = new WowAceDeserializer('^1^S~|^^').deserialize();
        assert.deepStrictEqual(result, '~');
    });
    test('B16: ~} → caret (^)', () => {
        const result = new WowAceDeserializer('^1^S~}^^').deserialize();
        assert.deepStrictEqual(result, '^');
    });
    test('B17: round-trip all escapable bytes', () => {
        const input = [0, 1, 10, 29, 30, 31, 32, 94, 127, 126].map(b => String.fromCharCode(b)).join('');
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
});

describe('C. Number Serialization', () => {
    test('C18: positive integer → ^N42', () => {
        const wire = WowAceSerializer.serialize(42);
        assert.ok(wire.includes('^N42'), 'Expected wire to contain ^N42, got: ' + wire);
    });
    test('C19: negative integer → ^N-42', () => {
        const wire = WowAceSerializer.serialize(-42);
        assert.ok(wire.includes('^N-42'), 'Expected wire to contain ^N-42, got: ' + wire);
    });
    test('C20: zero → ^N0', () => {
        const wire = WowAceSerializer.serialize(0);
        assert.ok(wire.includes('^N0'), 'Expected wire to contain ^N0, got: ' + wire);
    });
    test('C21: large integer', () => {
        const wire = WowAceSerializer.serialize(1000000);
        assert.ok(wire.includes('^N1000000'), 'Expected wire to contain ^N1000000, got: ' + wire);
    });
    test('C22: non-integer float uses ^N (tonumber/tostring check)', () => {
        const wire = WowAceSerializer.serialize(3.14);
        assert.ok(wire.includes('^N3.14'), 'Expected wire to contain ^N3.14, got: ' + wire);
    });
    test('C23: 3.14 exact wire format', () => {
        const wire = WowAceSerializer.serialize(3.14);
        assert.strictEqual(wire, '^1^N3.14^^');
    });
    test('C24a: 0.1 wire format', () => {
        const wire = WowAceSerializer.serialize(0.1);
        assert.strictEqual(wire, '^1^N0.1^^');
    });
    test('C24b: -99.99 wire format', () => {
        const wire = WowAceSerializer.serialize(-99.99);
        assert.strictEqual(wire, '^1^N-99.99^^');
    });
    test('C24c: 1e-10 wire format', () => {
        const wire = WowAceSerializer.serialize(1e-10);
        assert.strictEqual(wire, '^1^N1e-10^^');
    });
    test('C25: positive infinity → ^N1.#INF or ^Ninf', () => {
        const wire = WowAceSerializer.serialize(Infinity);
        const candidates = ["1.#INF", "inf"];
        assert.ok(candidates.some(c => wire.includes(c)), `Expected wire to contain one of ${candidates}, got: ${wire}`);
    });
    test('C26: negative infinity → ^N-1.#INF or ^N-inf', () => {
        const wire = WowAceSerializer.serialize(-Infinity);
        const candidates = ["-1.#INF", "-inf"];
        assert.ok(candidates.some(c => wire.includes(c)), `Expected wire to contain one of ${candidates}, got: ${wire}`);
    });
});

describe('D. Number Deserialization', () => {
    test('D27: ^N42 → 42', () => {
        const result = new WowAceDeserializer('^1^N42^^').deserialize();
        assert.deepStrictEqual(result, 42);
    });
    test('D28: ^N-42 → -42', () => {
        const result = new WowAceDeserializer('^1^N-42^^').deserialize();
        assert.deepStrictEqual(result, -42);
    });
    test('D29: ^N3.14 → 3.14', () => {
        const result = new WowAceDeserializer('^1^N3.14^^').deserialize();
        assert.deepStrictEqual(result, 3.14);
    });
    test('D30: ^N1.#INF → Infinity', () => {
        const result = new WowAceDeserializer('^1^N1.#INF^^').deserialize();
        assert.deepStrictEqual(result, Infinity);
    });
    test('D31: ^N-1.#INF → -Infinity', () => {
        const result = new WowAceDeserializer('^1^N-1.#INF^^').deserialize();
        assert.deepStrictEqual(result, -Infinity);
    });
    test('D32: ^Ninf → Infinity (alternate)', () => {
        const result = new WowAceDeserializer('^1^Ninf^^').deserialize();
        assert.deepStrictEqual(result, Infinity);
    });
    test('D33: ^N-inf → -Infinity (alternate)', () => {
        const result = new WowAceDeserializer('^1^N-inf^^').deserialize();
        assert.deepStrictEqual(result, -Infinity);
    });
    test('D34: ^F<m>^f<e> → correct float', () => {
        const result = new WowAceDeserializer('^1^F4503599627370496^f-53^^').deserialize();
        assert.deepStrictEqual(result, 0.5);
    });
});

describe('E. Float Round-trips', () => {
    test('E35: round-trip 3.14', () => {
        const input = 3.14;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E36: round-trip 0.1', () => {
        const input = 0.1;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E37: round-trip 123.456', () => {
        const input = 123.456;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E38: round-trip -99.99', () => {
        const input = -99.99;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E39: round-trip 1e-10', () => {
        const input = 1e-10;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E40: round-trip very small float (min normal)', () => {
        const input = 2.2250738585072014e-308;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('E41: round-trip very large float', () => {
        const input = 1.7976931348623157e+308;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
});

describe('F. Boolean', () => {
    test('F42: true → ^B', () => {
        const wire = WowAceSerializer.serialize(true);
        assert.ok(wire.includes('^B'), 'Expected wire to contain ^B, got: ' + wire);
    });
    test('F43: false → ^b', () => {
        const wire = WowAceSerializer.serialize(false);
        assert.ok(wire.includes('^b'), 'Expected wire to contain ^b, got: ' + wire);
    });
    test('F44: ^B → true', () => {
        const result = new WowAceDeserializer('^1^B^^').deserialize();
        assert.deepStrictEqual(result, true);
    });
    test('F45: ^b → false', () => {
        const result = new WowAceDeserializer('^1^b^^').deserialize();
        assert.deepStrictEqual(result, false);
    });
});

describe('G. Nil', () => {
    test('G46: nil → ^Z', () => {
        const wire = WowAceSerializer.serialize(null);
        assert.ok(wire.includes('^Z'), 'Expected wire to contain ^Z, got: ' + wire);
    });
    test('G47: ^Z → nil', () => {
        const result = new WowAceDeserializer('^1^Z^^').deserialize();
        assert.deepStrictEqual(result, null);
    });
});

describe('H. Table Serialization', () => {
    test('H48: empty table → ^T^t', () => {
        const wire = WowAceSerializer.serialize({  });
        assert.ok(wire.includes('^T^t'), 'Expected wire to contain ^T^t, got: ' + wire);
    });
    test('H49: single string key-value pair', () => {
        const wire = WowAceSerializer.serialize({ a: 1 });
        assert.ok(wire.includes('^T'), 'Expected wire to contain ^T, got: ' + wire);
        assert.ok(wire.includes('^Sa'), 'Expected wire to contain ^Sa, got: ' + wire);
        assert.ok(wire.includes('^N1'), 'Expected wire to contain ^N1, got: ' + wire);
        assert.ok(wire.includes('^t'), 'Expected wire to contain ^t, got: ' + wire);
    });
    test('H50: multiple key-value pairs', () => {
        const wire = WowAceSerializer.serialize({ a: 1, b: 2 });
        assert.ok(wire.includes('^T'), 'Expected wire to contain ^T, got: ' + wire);
        assert.ok(wire.includes('^t'), 'Expected wire to contain ^t, got: ' + wire);
    });
    test('H51: nested table', () => {
        const wire = WowAceSerializer.serialize({ inner: { x: 1 } });
        const count = wire.split('^T').length - 1;
        assert.strictEqual(count, 2);
    });
    test('H52: array → 1-based integer keys', () => {
        const wire = WowAceSerializer.serialize(['a', 'b', 'c']);
        assert.ok(wire.includes('^N1'), 'Expected wire to contain ^N1, got: ' + wire);
        assert.ok(wire.includes('^Sa'), 'Expected wire to contain ^Sa, got: ' + wire);
        assert.ok(wire.includes('^N2'), 'Expected wire to contain ^N2, got: ' + wire);
        assert.ok(wire.includes('^Sb'), 'Expected wire to contain ^Sb, got: ' + wire);
        assert.ok(wire.includes('^N3'), 'Expected wire to contain ^N3, got: ' + wire);
        assert.ok(wire.includes('^Sc'), 'Expected wire to contain ^Sc, got: ' + wire);
    });
    test('H53: mixed table (integer + string keys)', () => {
        const wire = WowAceSerializer.serialize({ 1: 'a', x: 'b' });
        assert.ok(wire.includes('^T'), 'Expected wire to contain ^T, got: ' + wire);
        assert.ok(wire.includes('^t'), 'Expected wire to contain ^t, got: ' + wire);
    });
});

describe('I. Array Detection', () => {
    test('I54: sequential 1-based keys → array', () => {
        const input = { 1: 'a', 2: 'b', 3: 'c' };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result[1], 'a');
        assert.deepStrictEqual(result[2], 'b');
        assert.deepStrictEqual(result[3], 'c');
    });
    test('I55: non-sequential keys → object', () => {
        const input = { 1: 'a', 3: 'c' };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result[1], 'a');
        assert.deepStrictEqual(result[3], 'c');
    });
    test('I56: string keys → object', () => {
        const input = { x: 1, y: 2 };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result['x'], 1);
        assert.deepStrictEqual(result['y'], 2);
    });
    test('I57: single element', () => {
        const input = { 1: 'only' };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result[1], 'only');
    });
    test('I58: empty table → empty', () => {
        const input = {  };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, {});
    });
});

describe('J. Framing', () => {
    test('J59: output starts with ^1 and ends with ^^', () => {
        const wire = WowAceSerializer.serialize('hello');
        assert.ok(wire.startsWith('^1'), `Expected to start with ^1, got: ${wire}`);
        assert.ok(wire.endsWith('^^'), `Expected to end with ^^, got: ${wire}`);
    });
    test('J62: control chars stripped from input', () => {
        const result = new WowAceDeserializer('^1\x09\x0a^Shello\x0d\x0a^^').deserialize();
        assert.deepStrictEqual(result, 'hello');
    });
});

describe('K. Error Handling', () => {
    test('J60: missing ^1 prefix → error', () => {
        assert.throws(() => {
            new WowAceDeserializer('^Shello^^').deserialize();
        });
    });
    test('K64: empty string → error', () => {
        assert.throws(() => {
            new WowAceDeserializer('').deserialize();
        });
    });
    test('K65: missing ^^ terminator → error', () => {
        assert.throws(() => {
            new WowAceDeserializer('^1^Shello').deserialize();
        });
    });
});

describe('L. Round-trips', () => {
    test('L66: plain ASCII string', () => {
        const input = 'hello world test';
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('L67: all special chars', () => {
        const input = [0, 1, 30, 31, 32, 94, 126, 127].map(b => String.fromCharCode(b)).join('');
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('L68: integer', () => {
        const input = 12345;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('L69: float', () => {
        const input = 3.14;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('L70: boolean', () => {
        {
            const input = true;
            const wire = WowAceSerializer.serialize(input);
            const result = new WowAceDeserializer(wire).deserialize();
            assert.deepStrictEqual(result, input);
        }
        {
            const input = false;
            const wire = WowAceSerializer.serialize(input);
            const result = new WowAceDeserializer(wire).deserialize();
            assert.deepStrictEqual(result, input);
        }
    });
    test('L71: nil', () => {
        const input = null;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('L72: nested table/array', () => {
        const input = { 1: 1, 2: { 1: 2, 2: 3 } };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result[1], 1);
    });
    test('L73: mixed-type table', () => {
        const input = { n: 42, f: 3.14, b: true, s: 'hello' };
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result['n'], 42);
        assert.deepStrictEqual(result['f'], 3.14);
        assert.deepStrictEqual(result['b'], true);
        assert.deepStrictEqual(result['s'], 'hello');
    });
});

describe('L2. Fixture Wire-Format Tests', () => {
    test('L74: simple array of two strings — exact wire', () => {
        const wire = WowAceSerializer.serialize({ 1: 'a', 2: 'b' });
        assert.strictEqual(wire, '^1^T^N1^Sa^N2^Sb^t^^');
    });
    test('L75: simple array of two strings — deserialize', () => {
        const result = new WowAceDeserializer('^1^T^N1^Sa^N2^Sb^t^^').deserialize();
        assert.deepStrictEqual(result, { 1: 'a', 2: 'b' });
    });
    test('L76: array of three mixed values — exact wire', () => {
        const wire = WowAceSerializer.serialize({ 1: 'hello', 2: 42, 3: true });
        assert.strictEqual(wire, '^1^T^N1^Shello^N2^N42^N3^B^t^^');
    });
    test('L77: array of three mixed values — deserialize', () => {
        const result = new WowAceDeserializer('^1^T^N1^Shello^N2^N42^N3^B^t^^').deserialize();
        assert.deepStrictEqual(result, { 1: 'hello', 2: 42, 3: true });
    });
    test('L78: nested array — exact wire', () => {
        const wire = WowAceSerializer.serialize({ 1: { 1: 'a', 2: 'b' }, 2: 'c' });
        assert.strictEqual(wire, '^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^');
    });
    test('L79: nested array — deserialize', () => {
        const result = new WowAceDeserializer('^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^').deserialize();
        assert.deepStrictEqual(result, { 1: { 1: 'a', 2: 'b' }, 2: 'c' });
    });
    test('L80: array with null values — exact wire', () => {
        const wire = WowAceSerializer.serialize({ 1: null, 2: null, 3: null, 4: 'test' });
        assert.strictEqual(wire, '^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^');
    });
    test('L81: array with null values — deserialize', () => {
        const result = new WowAceDeserializer('^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^').deserialize();
        assert.deepStrictEqual(result, { 1: null, 2: null, 3: null, 4: 'test' });
    });
    test('L82: nested structure from protocol spec — deserialize only', () => {
        const result = new WowAceDeserializer('^1^T^Shello^Sworld^Stest^N123^Snested^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^t^^').deserialize();
        assert.deepStrictEqual(result, { hello: 'world', test: 123, nested: { 1: null, 2: null, 3: null, 4: 'test' } });
    });
    test('L83: mixed table string and integer keys — deserialize only', () => {
        const result = new WowAceDeserializer('^1^T^Shello^Sworld^Sn^N42^t^^').deserialize();
        assert.deepStrictEqual(result, { hello: 'world', n: 42 });
    });
});

describe('M. Float wire format consistency', () => {
    test('M84: 3.14 uses ^N path (not ^F)', () => {
        const wire = WowAceSerializer.serialize(3.14);
        assert.ok(wire.includes('^N3.14'), 'Expected wire to contain ^N3.14, got: ' + wire);
    });
    test('M85: very small float 1e-10 uses ^N path', () => {
        const wire = WowAceSerializer.serialize(1e-10);
        assert.ok(wire.includes('^N'), 'Expected wire to contain ^N, got: ' + wire);
    });
    test('M86: 0.5 uses ^N path', () => {
        const wire = WowAceSerializer.serialize(0.5);
        assert.ok(wire.includes('^N0.5'), 'Expected wire to contain ^N0.5, got: ' + wire);
    });
    test('M87: extreme float 2.2250738585072014e-308 round-trips correctly', () => {
        const input = 2.2250738585072014e-308;
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('M88: extreme float 2.2250738585072014e-308 uses ^F path (%.14g loses precision)', () => {
        const wire = WowAceSerializer.serialize(2.2250738585072014e-308);
        assert.ok(wire.includes('^F'), 'Expected wire to contain ^F, got: ' + wire);
    });
});

describe('N. Escape edge cases', () => {
    test('N88a: invalid escape ~> (ord 62, would produce negative byte) is rejected', () => {
        assert.throws(() => {
            new WowAceDeserializer('^1^S~>^^').deserialize();
        });
    });
    test('N88b: invalid escape ~# (ord 35, would produce negative byte) is rejected', () => {
        assert.throws(() => {
            new WowAceDeserializer('^1^S~#^^').deserialize();
        });
    });
    test('N88c: all control bytes 0x01-0x1D round-trip correctly', () => {
        const input = Array.from({ length: 29 }, (_, i) => String.fromCharCode(i + 1)).join('');
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('N89: all escapable bytes combined in one string round-trip', () => {
        const input = [0, 1, 10, 29, 30, 31, 32, 94, 126, 127].map(b => String.fromCharCode(b)).join('');
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
    test('N90: high bytes 0x80-0xFF pass through unescaped', () => {
        const input = Array.from({ length: 128 }, (_, i) => String.fromCharCode(i + 128)).join('');
        const wire = WowAceSerializer.serialize(input);
        const result = new WowAceDeserializer(wire).deserialize();
        assert.deepStrictEqual(result, input);
    });
});

