// Auto-generated by testing/generate-tests.py — DO NOT EDIT
import { test, describe, expect } from "bun:test";
import WowCbor from "../lib/WowCbor.js";
import Pipeline from "../lib/Pipeline.js";
import { encode } from "cbor-x";

describe("A. Round-trip", () => {
  test("A1: string value", () => {
    const input = "hello world";
    expect(WowCbor.decode(WowCbor.encode(input))).toBe(input);
  });
  test("A2: integer value", () => {
    const input = 42;
    expect(WowCbor.decode(WowCbor.encode(input))).toBe(input);
  });
  test("A3: boolean true", () => {
    const input = true;
    expect(WowCbor.decode(WowCbor.encode(input))).toBe(input);
  });
  test("A4: null value", () => {
    const input = null;
    expect(WowCbor.decode(WowCbor.encode(input))).toBe(input);
  });
  test("A5: string-keyed object", () => {
    const input = { key: "value", num: 7 };
    const result = WowCbor.decode(WowCbor.encode(input));
    expect(result["key"]).toBe("value");
    expect(result["num"]).toBe(7);
  });
  test("A6: array", () => {
    const input = ["a", "b", "c"];
    expect(WowCbor.decode(WowCbor.encode(input))).toEqual(input);
  });
});

describe("B. Byte string conversion", () => {
  test("B1: byte string is converted to UTF-8 string", () => {
    const bytes = Buffer.from("hello", "utf8");
    const cbor = Buffer.concat([Buffer.from([0x40 + bytes.length]), bytes]);
    const result = WowCbor.decode(cbor);
    expect(result).toBe("hello");
  });
  test("B2: nested byte string in object is converted", () => {
    const raw = encode({ key: Buffer.from("world", "utf8") });
    const result = WowCbor.decode(raw);
    expect(result.key).toBe("world");
  });
  test("B3: byte strings in list are converted", () => {
    const raw = encode([Buffer.from("a", "utf8"), Buffer.from("b", "utf8")]);
    const result = WowCbor.decode(raw);
    expect(result).toEqual(["a", "b"]);
  });
});

describe("C. Array detection", () => {
  test("C1: sequential 1-based int keys converted to array", () => {
    const m = new Map([
      [1, "a"],
      [2, "b"],
      [3, "c"],
    ]);
    const raw = encode(m);
    const result = WowCbor.decode(raw);
    expect(result).toEqual(["a", "b", "c"]);
  });
  test("C2: non-sequential int keys stay as object", () => {
    const m = new Map([
      [1, "a"],
      [3, "c"],
    ]);
    const raw = encode(m);
    const result = WowCbor.decode(raw);
    expect(Array.isArray(result)).toBe(false);
  });
  test("C3: string-keyed object stays as object", () => {
    const input = { a: 1, b: 2 };
    const result = WowCbor.decode(WowCbor.encode(input));
    expect(Array.isArray(result)).toBe(false);
    expect(result.a).toBe(1);
    expect(result.b).toBe(2);
  });
});

describe("D. Plater v2 prefix", () => {
  test("D1: encodes with !PLATER:2! prefix", () => {
    const enc = Pipeline.encode({
      addon: "plater",
      version: 2,
      data: { x: 1 },
      metadata: null,
    });
    expect(enc.startsWith("!PLATER:2!")).toBe(true);
  });
  test("D2: decodes !PLATER:2! to plater v2", () => {
    const enc = Pipeline.encode({
      addon: "plater",
      version: 2,
      data: { x: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("plater");
    expect(dec.version).toBe(2);
  });
  test("D3: Plater v2 round-trip preserves data", () => {
    const data = { profile: "Default", enabled: true, level: 5 };
    const enc = Pipeline.encode({
      addon: "plater",
      version: 2,
      data,
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.data.profile).toBe("Default");
    expect(dec.data.enabled).toBe(true);
    expect(dec.data.level).toBe(5);
  });
  test("D4: !PLATER:2! is detected before ! catch-all", () => {
    const enc = Pipeline.encode({
      addon: "plater",
      version: 2,
      data: "test",
      metadata: null,
    });
    expect(enc.startsWith("!PLATER:2!")).toBe(true);
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("plater");
    expect(dec.version).toBe(2);
  });
});
