// Auto-generated by scripts/generate-tests.py — DO NOT EDIT
'use strict';
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const WowCbor = require('../lib/WowCbor');
const Pipeline = require('../lib/Pipeline');
const { encode } = require('cbor-x');

describe('A. Round-trip', () => {
    test('A1: string value', () => {
        const input = 'hello world';
        assert.strictEqual(WowCbor.decode(WowCbor.encode(input)), input);
    });
    test('A2: integer value', () => {
        const input = 42;
        assert.strictEqual(WowCbor.decode(WowCbor.encode(input)), input);
    });
    test('A3: boolean true', () => {
        const input = true;
        assert.strictEqual(WowCbor.decode(WowCbor.encode(input)), input);
    });
    test('A4: null value', () => {
        const input = null;
        assert.strictEqual(WowCbor.decode(WowCbor.encode(input)), input);
    });
    test('A5: string-keyed object', () => {
        const input = { key: 'value', num: 7 };
        const result = WowCbor.decode(WowCbor.encode(input));
        assert.strictEqual(result['key'], 'value');
        assert.strictEqual(result['num'], 7);
    });
    test('A6: array', () => {
        const input = ['a', 'b', 'c'];
        assert.deepStrictEqual(WowCbor.decode(WowCbor.encode(input)), input);
    });
});

describe('B. Byte string conversion', () => {
    test('B1: byte string is converted to UTF-8 string', () => {
        const bytes = Buffer.from('hello', 'utf8');
        const cbor = Buffer.concat([Buffer.from([0x40 + bytes.length]), bytes]);
        const result = WowCbor.decode(cbor);
        assert.strictEqual(result, 'hello');
    });
    test('B2: nested byte string in object is converted', () => {
        const raw = encode({ key: Buffer.from('world', 'utf8') });
        const result = WowCbor.decode(raw);
        assert.strictEqual(result.key, 'world');
    });
    test('B3: byte strings in list are converted', () => {
        const raw = encode([Buffer.from('a', 'utf8'), Buffer.from('b', 'utf8')]);
        const result = WowCbor.decode(raw);
        assert.deepStrictEqual(result, ['a', 'b']);
    });
});

describe('C. Array detection', () => {
    test('C1: sequential 1-based int keys converted to array', () => {
        const m = new Map([[1, 'a'], [2, 'b'], [3, 'c']]);
        const raw = encode(m);
        const result = WowCbor.decode(raw);
        assert.deepStrictEqual(result, ['a', 'b', 'c']);
    });
    test('C2: non-sequential int keys stay as object', () => {
        const m = new Map([[1, 'a'], [3, 'c']]);
        const raw = encode(m);
        const result = WowCbor.decode(raw);
        assert.ok(!Array.isArray(result));
    });
    test('C3: string-keyed object stays as object', () => {
        const input = { a: 1, b: 2 };
        const result = WowCbor.decode(WowCbor.encode(input));
        assert.ok(!Array.isArray(result));
        assert.strictEqual(result.a, 1);
        assert.strictEqual(result.b, 2);
    });
});

describe('D. Plater v2 prefix', () => {
    test('D1: encodes with !PLATER:2! prefix', () => {
        const enc = Pipeline.encode({ addon: 'plater', version: 2, data: { x: 1 }, metadata: null });
        assert.ok(enc.startsWith('!PLATER:2!'));
    });
    test('D2: decodes !PLATER:2! to plater v2', () => {
        const enc = Pipeline.encode({ addon: 'plater', version: 2, data: { x: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'plater');
        assert.strictEqual(dec.version, 2);
    });
    test('D3: Plater v2 round-trip preserves data', () => {
        const data = { profile: 'Default', enabled: true, level: 5 };
        const enc = Pipeline.encode({ addon: 'plater', version: 2, data, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.data.profile, 'Default');
        assert.strictEqual(dec.data.enabled, true);
        assert.strictEqual(dec.data.level, 5);
    });
    test('D4: !PLATER:2! is detected before ! catch-all', () => {
        const enc = Pipeline.encode({ addon: 'plater', version: 2, data: 'test', metadata: null });
        assert.ok(enc.startsWith('!PLATER:2!'));
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'plater');
        assert.strictEqual(dec.version, 2);
    });
});

