// Auto-generated by scripts/generate-tests.py — DO NOT EDIT
'use strict';
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { LibSerializeDeserialize, LibSerializeSerialize } = require('../lib/LibSerialize');

function ser(...args) { return LibSerializeSerialize.serialize(...args); }
function de(buf) { return LibSerializeDeserialize.deserialize(buf); }
function roundtrip(v) { return de(ser(v)); }

describe('A. Nil', () => {
    test('A01: serialize nil produces non-empty string', () => {
        const wire = ser(null);
        assert.ok(wire.length > 0);
    });
    test('A02: nil round-trips to nil', () => {
        const result = roundtrip(null);
        assert.strictEqual(result, null);
    });
    test('A03: Deserialize of serialized nil returns ok=true and nil value', () => {
        const result = roundtrip(null);
        assert.strictEqual(result, null);
    });
});

describe('B. Integer encoding (small embedded)', () => {
    test('B01: zero round-trips correctly (embedded 1-byte)', () => {
        const input = 0;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B02: positive small int 1 round-trips correctly', () => {
        const input = 1;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B03: small int 127 round-trips correctly (embedded 1-byte max)', () => {
        const input = 127;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B04: small negative -1 round-trips correctly (embedded 2-byte)', () => {
        const input = -1;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B05: small negative -4095 round-trips correctly (embedded 2-byte near max)', () => {
        const input = -4095;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B06: positive 128 round-trips correctly (embedded 2-byte)', () => {
        const input = 128;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('B07: positive 4095 round-trips correctly (embedded 2-byte max)', () => {
        const input = 4095;
        assert.deepStrictEqual(roundtrip(input), input);
    });
});

describe('C. Integer encoding (multi-byte)', () => {
    test('C01: 16-bit positive 4096 round-trips correctly', () => {
        const input = 4096;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C02: 16-bit positive max 65535 round-trips correctly', () => {
        const input = 65535;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C03: 16-bit negative -4096 round-trips correctly', () => {
        const input = -4096;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C04: 24-bit positive 65536 round-trips correctly', () => {
        const input = 65536;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C05: 24-bit positive max 16777215 round-trips correctly', () => {
        const input = 16777215;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C06: 32-bit positive 16777216 round-trips correctly', () => {
        const input = 16777216;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C07: 32-bit positive max 4294967295 round-trips correctly', () => {
        const input = 4294967295;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C08: 64-bit positive 4294967296 round-trips correctly', () => {
        const input = 4294967296;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('C09: large negative -65536 round-trips correctly', () => {
        const input = -65536;
        assert.deepStrictEqual(roundtrip(input), input);
    });
});

describe('D. Float encoding', () => {
    test('D01: float 3.14 round-trips correctly', () => {
        const input = 3.14;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('D02: float 0.1 round-trips correctly', () => {
        const input = 0.1;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('D03: float -99.99 round-trips correctly', () => {
        const input = -99.99;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('D04: float 1e-10 round-trips correctly', () => {
        const input = 1e-10;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('D05: float 0.5 round-trips correctly', () => {
        const input = 0.5;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
    test('D06: positive infinity round-trips correctly', () => {
        const input = Infinity;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('D07: negative infinity round-trips correctly', () => {
        const input = -Infinity;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('D08: max exact double integer 2^53 (9007199254740992) round-trips correctly', () => {
        const input = 9007199254740992;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('D09: float 1.5 round-trips correctly (floatstr short path)', () => {
        const input = 1.5;
        const result = roundtrip(input);
        assert.ok(Math.abs(result - input) < 1e-10, `Expected ${input}, got ${result}`);
    });
});

describe('E. Boolean', () => {
    test('E01: true round-trips correctly', () => {
        const input = true;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('E02: false round-trips correctly', () => {
        const input = false;
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('E03: true and false produce distinct serializations', () => {
        const wires = [];
        wires.push(ser(true).toString('hex'));
        wires.push(ser(false).toString('hex'));
        const unique = new Set(wires);
        assert.strictEqual(unique.size, wires.length, 'Expected all serializations to be distinct');
    });
});

describe('F. String encoding (embedded)', () => {
    test('F01: empty string round-trips correctly', () => {
        const input = '';
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('F02: single char string round-trips correctly', () => {
        const input = 'a';
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('F03: two char string round-trips correctly', () => {
        const input = 'ab';
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('F04: short 5-char string round-trips correctly', () => {
        const input = 'hello';
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('F05: 15-char string (max embedded) round-trips correctly', () => {
        const input = '123456789012345';
        assert.deepStrictEqual(roundtrip(input), input);
    });
});

describe('G. String encoding (length-prefixed)', () => {
    test('G01: 16-char string (STR_8 path) round-trips correctly', () => {
        const input = '1234567890123456';
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('G02: long 100-char string round-trips correctly', () => {
        const input = 'x'.repeat(100);
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('G03: string with all 256 byte values round-trips correctly', () => {
        const input = Array.from({ length: 256 }, (_, i) => String.fromCharCode(i + 0)).join('');
        assert.deepStrictEqual(roundtrip(input), input);
    });
});

describe('H. String refs', () => {
    test('H01: repeated string in table round-trips with correct values', () => {
        const input = { a: 'hello world', b: 'hello world' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['a'], 'hello world');
        assert.deepStrictEqual(result['b'], 'hello world');
    });
    test('H02: string repeated 5 times in array round-trips with correct values', () => {
        const input = { 1: 'shared_key', 2: 'shared_key', 3: 'shared_key', 4: 'shared_key', 5: 'shared_key' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'shared_key');
        assert.deepStrictEqual(result[2], 'shared_key');
        assert.deepStrictEqual(result[3], 'shared_key');
        assert.deepStrictEqual(result[4], 'shared_key');
        assert.deepStrictEqual(result[5], 'shared_key');
    });
    test('H03: short strings (<=2 bytes) not tracked as refs but still round-trip correctly', () => {
        const input = { a: 'x', b: 'x', c: 'xy', d: 'xy' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['a'], 'x');
        assert.deepStrictEqual(result['b'], 'x');
        assert.deepStrictEqual(result['c'], 'xy');
        assert.deepStrictEqual(result['d'], 'xy');
    });
});

describe('I. Empty and small tables', () => {
    test('I01: empty table round-trips to empty table', () => {
        const result = roundtrip({  });
        assert.deepStrictEqual(result, {});
    });
    test('I02: table with 1 key-value pair round-trips correctly', () => {
        const input = { a: 1 };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['a'], 1);
    });
    test('I03: table with 15 entries (embedded max) round-trips all values correctly', () => {
        const input = { k1: 1, k2: 2, k3: 3, k4: 4, k5: 5, k6: 6, k7: 7, k8: 8, k9: 9, k10: 10, k11: 11, k12: 12, k13: 13, k14: 14, k15: 15 };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['k1'], 1);
        assert.deepStrictEqual(result['k2'], 2);
        assert.deepStrictEqual(result['k3'], 3);
        assert.deepStrictEqual(result['k4'], 4);
        assert.deepStrictEqual(result['k5'], 5);
        assert.deepStrictEqual(result['k6'], 6);
        assert.deepStrictEqual(result['k7'], 7);
        assert.deepStrictEqual(result['k8'], 8);
        assert.deepStrictEqual(result['k9'], 9);
        assert.deepStrictEqual(result['k10'], 10);
        assert.deepStrictEqual(result['k11'], 11);
        assert.deepStrictEqual(result['k12'], 12);
        assert.deepStrictEqual(result['k13'], 13);
        assert.deepStrictEqual(result['k14'], 14);
        assert.deepStrictEqual(result['k15'], 15);
    });
});

describe('J. Arrays', () => {
    test('J01: single-element array round-trips correctly', () => {
        const input = { 1: 'only' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'only');
    });
    test('J02: simple array [a, b, c] round-trips correctly', () => {
        const input = { 1: 'a', 2: 'b', 3: 'c' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'a');
        assert.deepStrictEqual(result[2], 'b');
        assert.deepStrictEqual(result[3], 'c');
    });
    test('J03: integer array [10, 20, 30, 40, 50] round-trips correctly', () => {
        const input = { 1: 10, 2: 20, 3: 30, 4: 40, 5: 50 };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 10);
        assert.deepStrictEqual(result[2], 20);
        assert.deepStrictEqual(result[3], 30);
        assert.deepStrictEqual(result[4], 40);
        assert.deepStrictEqual(result[5], 50);
    });
    test('J04: mixed-type array [str, 42, true, false] round-trips correctly', () => {
        const input = { 1: 'str', 2: 42, 3: true, 4: false };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'str');
        assert.deepStrictEqual(result[2], 42);
        assert.deepStrictEqual(result[3], true);
        assert.deepStrictEqual(result[4], false);
    });
    test('J05: 16-element array (ARRAY_8 path) round-trips correctly', () => {
        const input = { 1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60, 7: 70, 8: 80, 9: 90, 10: 100, 11: 110, 12: 120, 13: 130, 14: 140, 15: 150, 16: 160 };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 10);
        assert.deepStrictEqual(result[2], 20);
        assert.deepStrictEqual(result[3], 30);
        assert.deepStrictEqual(result[4], 40);
        assert.deepStrictEqual(result[5], 50);
        assert.deepStrictEqual(result[6], 60);
        assert.deepStrictEqual(result[7], 70);
        assert.deepStrictEqual(result[8], 80);
        assert.deepStrictEqual(result[9], 90);
        assert.deepStrictEqual(result[10], 100);
        assert.deepStrictEqual(result[11], 110);
        assert.deepStrictEqual(result[12], 120);
        assert.deepStrictEqual(result[13], 130);
        assert.deepStrictEqual(result[14], 140);
        assert.deepStrictEqual(result[15], 150);
        assert.deepStrictEqual(result[16], 160);
    });
});

describe('K. Mixed tables', () => {
    test('K01: mixed table with integer and string keys round-trips correctly', () => {
        const input = { 1: 'first', 2: 'second', x: 'extra' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'first');
        assert.deepStrictEqual(result[2], 'second');
        assert.deepStrictEqual(result['x'], 'extra');
    });
    test('K02: mixed table with various value types round-trips correctly', () => {
        const input = { 1: 'arr1', 2: 'arr2', key: 99, flag: true };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'arr1');
        assert.deepStrictEqual(result[2], 'arr2');
        assert.deepStrictEqual(result['key'], 99);
        assert.deepStrictEqual(result['flag'], true);
    });
    test('K03: nested table round-trips inner values correctly', () => {
        const input = { inner: { x: 1, y: 2 } };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['inner'], { x: 1, y: 2 });
    });
    test('K04: deeply nested table round-trips leaf value correctly', () => {
        const input = { a: { b: { c: { d: 42 } } } };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['a'], { b: { c: { d: 42 } } });
    });
});

describe('L. Table refs', () => {
    test('L01: shared sub-table round-trips with correct values in both references', () => {
        const input = { a: { value: 99 }, b: { value: 99 } };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['a'], { value: 99 });
        assert.deepStrictEqual(result['b'], { value: 99 });
    });
    test('L02: deserialized shared table refs point to the same object (mutation test)', () => {
        assert.ok(true, 'ref_identity test — Lua-specific');
    });
});

describe('M. Variadic Serialize/Deserialize', () => {
    test('M01: serialize multiple values (1, hello, true) deserializes all correctly', () => {
        assert.deepStrictEqual(roundtrip(1), 1);
        assert.deepStrictEqual(roundtrip('hello'), 'hello');
        assert.deepStrictEqual(roundtrip(true), true);
    });
    test('M02: serialize values with nil in middle (1, nil, 3) deserializes all correctly', () => {
        assert.deepStrictEqual(roundtrip(1), 1);
        assert.strictEqual(roundtrip(null), null);
        assert.deepStrictEqual(roundtrip(3), 3);
    });
});

describe('N. Error handling', () => {
    test('N01: deserializing corrupt data returns a boolean result (ok field)', () => {
        const wire = Buffer.from('not valid data \xff', 'binary');
        let threw = false;
        try {
            de(wire);
        } catch(e) {
            threw = true;
        }
        if (!threw) {
            // Some implementations return error as value rather than throwing
            assert.ok(true);
        }
    });
    test('N02: IsSerializableType returns true for nil, number, string, boolean, table', () => {
        // IsSerializableType not exposed in JS — skip
        assert.ok(true);
    });
    test('N03: IsSerializableType returns false for functions', () => {
        // IsSerializableType not exposed in JS — skip
        assert.ok(true);
    });
});

describe('O. Round-trips (comprehensive)', () => {
    test('O01: complex nested structure round-trips all fields correctly', () => {
        const input = { name: 'test', values: { 1: 1, 2: 2, 3: 3 }, meta: { active: true, count: 0 } };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['name'], 'test');
        assert.deepStrictEqual(result['meta'], { active: true, count: 0 });
    });
    test('O02: table with boolean keys round-trips correctly', () => {
        const input = { 1: 'yes', 0: 'no' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1], 'yes');
        assert.deepStrictEqual(result[0], 'no');
    });
    test('O03: table with float key 1.5 round-trips correctly', () => {
        const input = { 1.5: 'fractional' };
        const result = roundtrip(input);
        assert.deepStrictEqual(result[1.5], 'fractional');
    });
    test('O04: string with embedded null bytes round-trips correctly', () => {
        const input = [97, 0, 98, 0, 99].map(b => String.fromCharCode(b)).join('');
        assert.deepStrictEqual(roundtrip(input), input);
    });
    test('O05: all 256 byte values in a string round-trip correctly', () => {
        const input = Array.from({ length: 256 }, (_, i) => String.fromCharCode(i + 0)).join('');
        assert.deepStrictEqual(roundtrip(input), input);
    });
});

describe('P. Mixed table + table ref integrity', () => {
    test('P01: shared mixed table ref — both keys see array and hash portions', () => {
        const wire = Buffer.from('012612621e1529326b65793276616c1261e802', 'hex');
        const result = de(wire);
        assert.deepStrictEqual(result['a'], { 1: 10, 2: 20, key: 'val' });
        assert.deepStrictEqual(result['b'], { 1: 10, 2: 20, key: 'val' });
    });
    test('P02: mixed table then plain table then refs to both — ref indices correct', () => {
        const wire = Buffer.from('0146527265665f6d1ec9840c426e616d65526d69786564527265665f7026127905127803126de8021270e803', 'hex');
        const result = de(wire);
        assert.deepStrictEqual(result['m'], { 1: 100, 2: 200, name: 'mixed' });
        assert.deepStrictEqual(result['p'], { x: 1, y: 2 });
        assert.deepStrictEqual(result['ref_m'], { 1: 100, 2: 200, name: 'mixed' });
        assert.deepStrictEqual(result['ref_p'], { x: 1, y: 2 });
    });
    test('P03: mixed table followed by second table — roundtrip preserves all', () => {
        const input = { first: { 1: 'x', 2: 'y', name: 'mixed1' }, second: { 1: 'a', 2: 'b', name: 'mixed2' } };
        const result = roundtrip(input);
        assert.deepStrictEqual(result['first'], { 1: 'x', 2: 'y', name: 'mixed1' });
        assert.deepStrictEqual(result['second'], { 1: 'a', 2: 'b', name: 'mixed2' });
    });
});

describe('Q. Numeric key type preservation', () => {
    test('Q01: Lua-serialized array [a,b,c] deserializes with correct values', () => {
        const wire = Buffer.from('013a126112621263', 'hex');
        const result = de(wire);
        assert.strictEqual(typeof result, 'object');
        assert.deepStrictEqual(result[1], 'a');
        assert.deepStrictEqual(result[2], 'b');
        assert.deepStrictEqual(result[3], 'c');
    });
    test('Q02: Lua-serialized mixed int+string keys deserialize correctly', () => {
        const wire = Buffer.from('011e526669727374627365636f6e64426e616d654274657374', 'hex');
        const result = de(wire);
        assert.deepStrictEqual(result[1], 'first');
        assert.deepStrictEqual(result[2], 'second');
        assert.deepStrictEqual(result['name'], 'test');
    });
    test('Q03: Lua-serialized table has integer keys not string keys', () => {
        const wire = Buffer.from('011e526669727374627365636f6e64426e616d654274657374', 'hex');
        const result = de(wire);
        const keys = Object.keys(result);
        assert.ok(keys.includes('1'), 'Expected integer key 1 (as string property)');
        assert.ok(keys.includes('2'), 'Expected integer key 2 (as string property)');
        assert.ok(keys.includes('name'), 'Expected string key name');
        assert.strictEqual(typeof result[1] !== 'undefined', true, 'Key 1 accessible via numeric index');
        assert.strictEqual(typeof result[2] !== 'undefined', true, 'Key 2 accessible via numeric index');
    });
    test('Q04: mixed integer and string keys roundtrip with correct key types', () => {
        const input = { 1: 'first', 2: 'second', name: 'test' };
        const result = roundtrip(input);
        assert.ok(1 in result, 'Expected integer key 1 present after roundtrip');
        assert.ok(2 in result, 'Expected integer key 2 present after roundtrip');
        assert.ok('name' in result, 'Expected string key name present after roundtrip');
    });
    test('Q05: integer-keyed table serializes as array not table-with-string-keys', () => {
        const wire = ser({ 1: 'a', 2: 'b' });
        assert.strictEqual(Buffer.from(wire).toString('hex'), '012a12611262');
    });
});

describe('R. Variadic round-trip verification', () => {
    test('R01: single value variadic round-trip', () => {
        assert.deepStrictEqual(roundtrip(42), 42);
    });
    test('R02: four mixed-type values variadic round-trip', () => {
        assert.deepStrictEqual(roundtrip('hello'), 'hello');
        assert.deepStrictEqual(roundtrip(42), 42);
        assert.deepStrictEqual(roundtrip(true), true);
        assert.ok(Math.abs(roundtrip(3.14) - 3.14) < 1e-10);
    });
    test('R03: variadic with nil at start and end', () => {
        assert.strictEqual(roundtrip(null), null);
        assert.deepStrictEqual(roundtrip('hello'), 'hello');
        assert.strictEqual(roundtrip(null), null);
    });
});

describe('S. Nil wire format', () => {
    test('S01: Lua-serialized nil is exactly 01 00', () => {
        const wire = ser(null);
        assert.strictEqual(Buffer.from(wire).toString('hex'), '0100');
    });
});

