// Auto-generated by testing/generate-tests.py — DO NOT EDIT
import { test, describe, expect } from "bun:test";
import {
  LibSerializeDeserialize,
  LibSerializeSerialize,
} from "../lib/LibSerialize.js";

function ser(data: unknown): Buffer {
  return LibSerializeSerialize.serialize(data);
}
function de(buf: Buffer | Uint8Array | string): unknown {
  return LibSerializeDeserialize.deserialize(buf);
}
function roundtrip(v: unknown): unknown {
  return de(ser(v));
}

describe("A. Nil", () => {
  test("A01: serialize nil produces non-empty string", () => {
    const wire = ser(null);
    expect(wire.length > 0).toBe(true);
  });
  test("A02: nil round-trips to nil", () => {
    const result = roundtrip(null);
    expect(result).toBe(null);
  });
  test("A03: Deserialize of serialized nil returns ok=true and nil value", () => {
    const result = roundtrip(null);
    expect(result).toBe(null);
  });
});

describe("B. Integer encoding (small embedded)", () => {
  test("B01: zero round-trips correctly (embedded 1-byte)", () => {
    const input = 0;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B02: positive small int 1 round-trips correctly", () => {
    const input = 1;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B03: small int 127 round-trips correctly (embedded 1-byte max)", () => {
    const input = 127;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B04: small negative -1 round-trips correctly (embedded 2-byte)", () => {
    const input = -1;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B05: small negative -4095 round-trips correctly (embedded 2-byte near max)", () => {
    const input = -4095;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B06: positive 128 round-trips correctly (embedded 2-byte)", () => {
    const input = 128;
    expect(roundtrip(input)).toEqual(input);
  });
  test("B07: positive 4095 round-trips correctly (embedded 2-byte max)", () => {
    const input = 4095;
    expect(roundtrip(input)).toEqual(input);
  });
});

describe("C. Integer encoding (multi-byte)", () => {
  test("C01: 16-bit positive 4096 round-trips correctly", () => {
    const input = 4096;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C02: 16-bit positive max 65535 round-trips correctly", () => {
    const input = 65535;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C03: 16-bit negative -4096 round-trips correctly", () => {
    const input = -4096;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C04: 24-bit positive 65536 round-trips correctly", () => {
    const input = 65536;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C05: 24-bit positive max 16777215 round-trips correctly", () => {
    const input = 16777215;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C06: 32-bit positive 16777216 round-trips correctly", () => {
    const input = 16777216;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C07: 32-bit positive max 4294967295 round-trips correctly", () => {
    const input = 4294967295;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C08: 64-bit positive 4294967296 round-trips correctly", () => {
    const input = 4294967296;
    expect(roundtrip(input)).toEqual(input);
  });
  test("C09: large negative -65536 round-trips correctly", () => {
    const input = -65536;
    expect(roundtrip(input)).toEqual(input);
  });
});

describe("D. Float encoding", () => {
  test("D01: float 3.14 round-trips correctly", () => {
    const input = 3.14;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("D02: float 0.1 round-trips correctly", () => {
    const input = 0.1;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("D03: float -99.99 round-trips correctly", () => {
    const input = -99.99;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("D04: float 1e-10 round-trips correctly", () => {
    const input = 1e-10;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("D05: float 0.5 round-trips correctly", () => {
    const input = 0.5;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
  test("D06: positive infinity round-trips correctly", () => {
    const input = Infinity;
    expect(roundtrip(input)).toEqual(input);
  });
  test("D07: negative infinity round-trips correctly", () => {
    const input = -Infinity;
    expect(roundtrip(input)).toEqual(input);
  });
  test("D08: max exact double integer 2^53 (9007199254740992) round-trips correctly", () => {
    const input = 9007199254740992;
    expect(roundtrip(input)).toEqual(input);
  });
  test("D09: float 1.5 round-trips correctly (floatstr short path)", () => {
    const input = 1.5;
    const result = roundtrip(input);
    expect(Math.abs(result - input)).toBeLessThan(1e-10);
  });
});

describe("E. Boolean", () => {
  test("E01: true round-trips correctly", () => {
    const input = true;
    expect(roundtrip(input)).toEqual(input);
  });
  test("E02: false round-trips correctly", () => {
    const input = false;
    expect(roundtrip(input)).toEqual(input);
  });
  test("E03: true and false produce distinct serializations", () => {
    const wires = [];
    wires.push(ser(true).toString("hex"));
    wires.push(ser(false).toString("hex"));
    const unique = new Set(wires);
    expect(unique.size).toBe(wires.length);
  });
});

describe("F. String encoding (embedded)", () => {
  test("F01: empty string round-trips correctly", () => {
    const input = "";
    expect(roundtrip(input)).toEqual(input);
  });
  test("F02: single char string round-trips correctly", () => {
    const input = "a";
    expect(roundtrip(input)).toEqual(input);
  });
  test("F03: two char string round-trips correctly", () => {
    const input = "ab";
    expect(roundtrip(input)).toEqual(input);
  });
  test("F04: short 5-char string round-trips correctly", () => {
    const input = "hello";
    expect(roundtrip(input)).toEqual(input);
  });
  test("F05: 15-char string (max embedded) round-trips correctly", () => {
    const input = "123456789012345";
    expect(roundtrip(input)).toEqual(input);
  });
});

describe("G. String encoding (length-prefixed)", () => {
  test("G01: 16-char string (STR_8 path) round-trips correctly", () => {
    const input = "1234567890123456";
    expect(roundtrip(input)).toEqual(input);
  });
  test("G02: long 100-char string round-trips correctly", () => {
    const input = "x".repeat(100);
    expect(roundtrip(input)).toEqual(input);
  });
  test("G03: string with all 256 byte values round-trips correctly", () => {
    const input = Array.from({ length: 256 }, (_, i) =>
      String.fromCharCode(i + 0),
    ).join("");
    expect(roundtrip(input)).toEqual(input);
  });
});

describe("H. String refs", () => {
  test("H01: repeated string in table round-trips with correct values", () => {
    const input = { a: "hello world", b: "hello world" };
    const result = roundtrip(input);
    expect(result["a"]).toEqual("hello world");
    expect(result["b"]).toEqual("hello world");
  });
  test("H02: string repeated 5 times in array round-trips with correct values", () => {
    const input = {
      1: "shared_key",
      2: "shared_key",
      3: "shared_key",
      4: "shared_key",
      5: "shared_key",
    };
    const result = roundtrip(input);
    expect(result[1]).toEqual("shared_key");
    expect(result[2]).toEqual("shared_key");
    expect(result[3]).toEqual("shared_key");
    expect(result[4]).toEqual("shared_key");
    expect(result[5]).toEqual("shared_key");
  });
  test("H03: short strings (<=2 bytes) not tracked as refs but still round-trip correctly", () => {
    const input = { a: "x", b: "x", c: "xy", d: "xy" };
    const result = roundtrip(input);
    expect(result["a"]).toEqual("x");
    expect(result["b"]).toEqual("x");
    expect(result["c"]).toEqual("xy");
    expect(result["d"]).toEqual("xy");
  });
});

describe("I. Empty and small tables", () => {
  test("I01: empty table round-trips to empty table", () => {
    const result = roundtrip({});
    expect(result).toEqual({});
  });
  test("I02: table with 1 key-value pair round-trips correctly", () => {
    const input = { a: 1 };
    const result = roundtrip(input);
    expect(result["a"]).toEqual(1);
  });
  test("I03: table with 15 entries (embedded max) round-trips all values correctly", () => {
    const input = {
      k1: 1,
      k2: 2,
      k3: 3,
      k4: 4,
      k5: 5,
      k6: 6,
      k7: 7,
      k8: 8,
      k9: 9,
      k10: 10,
      k11: 11,
      k12: 12,
      k13: 13,
      k14: 14,
      k15: 15,
    };
    const result = roundtrip(input);
    expect(result["k1"]).toEqual(1);
    expect(result["k2"]).toEqual(2);
    expect(result["k3"]).toEqual(3);
    expect(result["k4"]).toEqual(4);
    expect(result["k5"]).toEqual(5);
    expect(result["k6"]).toEqual(6);
    expect(result["k7"]).toEqual(7);
    expect(result["k8"]).toEqual(8);
    expect(result["k9"]).toEqual(9);
    expect(result["k10"]).toEqual(10);
    expect(result["k11"]).toEqual(11);
    expect(result["k12"]).toEqual(12);
    expect(result["k13"]).toEqual(13);
    expect(result["k14"]).toEqual(14);
    expect(result["k15"]).toEqual(15);
  });
});

describe("J. Arrays", () => {
  test("J01: single-element array round-trips correctly", () => {
    const input = { 1: "only" };
    const result = roundtrip(input);
    expect(result[1]).toEqual("only");
  });
  test("J02: simple array [a, b, c] round-trips correctly", () => {
    const input = { 1: "a", 2: "b", 3: "c" };
    const result = roundtrip(input);
    expect(result[1]).toEqual("a");
    expect(result[2]).toEqual("b");
    expect(result[3]).toEqual("c");
  });
  test("J03: integer array [10, 20, 30, 40, 50] round-trips correctly", () => {
    const input = { 1: 10, 2: 20, 3: 30, 4: 40, 5: 50 };
    const result = roundtrip(input);
    expect(result[1]).toEqual(10);
    expect(result[2]).toEqual(20);
    expect(result[3]).toEqual(30);
    expect(result[4]).toEqual(40);
    expect(result[5]).toEqual(50);
  });
  test("J04: mixed-type array [str, 42, true, false] round-trips correctly", () => {
    const input = { 1: "str", 2: 42, 3: true, 4: false };
    const result = roundtrip(input);
    expect(result[1]).toEqual("str");
    expect(result[2]).toEqual(42);
    expect(result[3]).toEqual(true);
    expect(result[4]).toEqual(false);
  });
  test("J05: 16-element array (ARRAY_8 path) round-trips correctly", () => {
    const input = {
      1: 10,
      2: 20,
      3: 30,
      4: 40,
      5: 50,
      6: 60,
      7: 70,
      8: 80,
      9: 90,
      10: 100,
      11: 110,
      12: 120,
      13: 130,
      14: 140,
      15: 150,
      16: 160,
    };
    const result = roundtrip(input);
    expect(result[1]).toEqual(10);
    expect(result[2]).toEqual(20);
    expect(result[3]).toEqual(30);
    expect(result[4]).toEqual(40);
    expect(result[5]).toEqual(50);
    expect(result[6]).toEqual(60);
    expect(result[7]).toEqual(70);
    expect(result[8]).toEqual(80);
    expect(result[9]).toEqual(90);
    expect(result[10]).toEqual(100);
    expect(result[11]).toEqual(110);
    expect(result[12]).toEqual(120);
    expect(result[13]).toEqual(130);
    expect(result[14]).toEqual(140);
    expect(result[15]).toEqual(150);
    expect(result[16]).toEqual(160);
  });
});

describe("K. Mixed tables", () => {
  test("K01: mixed table with integer and string keys round-trips correctly", () => {
    const input = { 1: "first", 2: "second", x: "extra" };
    const result = roundtrip(input);
    expect(result[1]).toEqual("first");
    expect(result[2]).toEqual("second");
    expect(result["x"]).toEqual("extra");
  });
  test("K02: mixed table with various value types round-trips correctly", () => {
    const input = { 1: "arr1", 2: "arr2", key: 99, flag: true };
    const result = roundtrip(input);
    expect(result[1]).toEqual("arr1");
    expect(result[2]).toEqual("arr2");
    expect(result["key"]).toEqual(99);
    expect(result["flag"]).toEqual(true);
  });
  test("K03: nested table round-trips inner values correctly", () => {
    const input = { inner: { x: 1, y: 2 } };
    const result = roundtrip(input);
    expect(result["inner"]).toEqual({ x: 1, y: 2 });
  });
  test("K04: deeply nested table round-trips leaf value correctly", () => {
    const input = { a: { b: { c: { d: 42 } } } };
    const result = roundtrip(input);
    expect(result["a"]).toEqual({ b: { c: { d: 42 } } });
  });
});

describe("L. Table refs", () => {
  test("L01: shared sub-table round-trips with correct values in both references", () => {
    const input = { a: { value: 99 }, b: { value: 99 } };
    const result = roundtrip(input);
    expect(result["a"]).toEqual({ value: 99 });
    expect(result["b"]).toEqual({ value: 99 });
  });
  test("L02: deserialized shared table refs point to the same object (mutation test)", () => {
    expect(true).toBe(true);
  });
});

describe("M. Variadic Serialize/Deserialize", () => {
  test("M01: serialize multiple values (1, hello, true) deserializes all correctly", () => {
    expect(roundtrip(1)).toEqual(1);
    expect(roundtrip("hello")).toEqual("hello");
    expect(roundtrip(true)).toEqual(true);
  });
  test("M02: serialize values with nil in middle (1, nil, 3) deserializes all correctly", () => {
    expect(roundtrip(1)).toEqual(1);
    expect(roundtrip(null)).toBe(null);
    expect(roundtrip(3)).toEqual(3);
  });
});

describe("N. Error handling", () => {
  test("N01: deserializing corrupt data returns a boolean result (ok field)", () => {
    const wire = Buffer.from("not valid data \xff", "binary");
    let threw = false;
    try {
      de(wire);
    } catch (e) {
      threw = true;
    }
    if (!threw) {
      // Some implementations return error as value rather than throwing
      expect(true).toBe(true);
    }
  });
  test("N02: IsSerializableType returns true for nil, number, string, boolean, table", () => {
    // IsSerializableType not exposed in JS — skip
    expect(true).toBe(true);
  });
  test("N03: IsSerializableType returns false for functions", () => {
    // IsSerializableType not exposed in JS — skip
    expect(true).toBe(true);
  });
});

describe("O. Round-trips (comprehensive)", () => {
  test("O01: complex nested structure round-trips all fields correctly", () => {
    const input = {
      name: "test",
      values: { 1: 1, 2: 2, 3: 3 },
      meta: { active: true, count: 0 },
    };
    const result = roundtrip(input);
    expect(result["name"]).toEqual("test");
    expect(result["meta"]).toEqual({ active: true, count: 0 });
  });
  test("O02: table with boolean keys round-trips correctly", () => {
    const input = { 1: "yes", 0: "no" };
    const result = roundtrip(input);
    expect(result[1]).toEqual("yes");
    expect(result[0]).toEqual("no");
  });
  test("O03: table with float key 1.5 round-trips correctly", () => {
    const input = { 1.5: "fractional" };
    const result = roundtrip(input);
    expect(result[1.5]).toEqual("fractional");
  });
  test("O04: string with embedded null bytes round-trips correctly", () => {
    const input = [97, 0, 98, 0, 99]
      .map((b) => String.fromCharCode(b))
      .join("");
    expect(roundtrip(input)).toEqual(input);
  });
  test("O05: all 256 byte values in a string round-trip correctly", () => {
    const input = Array.from({ length: 256 }, (_, i) =>
      String.fromCharCode(i + 0),
    ).join("");
    expect(roundtrip(input)).toEqual(input);
  });
});

describe("P. Mixed table + table ref integrity", () => {
  test("P01: shared mixed table ref — both keys see array and hash portions", () => {
    const wire = Buffer.from("012612621e1529326b65793276616c1261e802", "hex");
    const result = de(wire);
    expect(result["a"]).toEqual({ 1: 10, 2: 20, key: "val" });
    expect(result["b"]).toEqual({ 1: 10, 2: 20, key: "val" });
  });
  test("P02: mixed table then plain table then refs to both — ref indices correct", () => {
    const wire = Buffer.from(
      "0146527265665f6d1ec9840c426e616d65526d69786564527265665f7026127905127803126de8021270e803",
      "hex",
    );
    const result = de(wire);
    expect(result["m"]).toEqual({ 1: 100, 2: 200, name: "mixed" });
    expect(result["p"]).toEqual({ x: 1, y: 2 });
    expect(result["ref_m"]).toEqual({ 1: 100, 2: 200, name: "mixed" });
    expect(result["ref_p"]).toEqual({ x: 1, y: 2 });
  });
  test("P03: mixed table followed by second table — roundtrip preserves all", () => {
    const input = {
      first: { 1: "x", 2: "y", name: "mixed1" },
      second: { 1: "a", 2: "b", name: "mixed2" },
    };
    const result = roundtrip(input);
    expect(result["first"]).toEqual({ 1: "x", 2: "y", name: "mixed1" });
    expect(result["second"]).toEqual({ 1: "a", 2: "b", name: "mixed2" });
  });
});

describe("Q. Numeric key type preservation", () => {
  test("Q01: Lua-serialized array [a,b,c] deserializes with correct values", () => {
    const wire = Buffer.from("013a126112621263", "hex");
    const result = de(wire);
    expect(typeof result).toBe("object");
    expect(result[1]).toEqual("a");
    expect(result[2]).toEqual("b");
    expect(result[3]).toEqual("c");
  });
  test("Q02: Lua-serialized mixed int+string keys deserialize correctly", () => {
    const wire = Buffer.from(
      "011e526669727374627365636f6e64426e616d654274657374",
      "hex",
    );
    const result = de(wire);
    expect(result[1]).toEqual("first");
    expect(result[2]).toEqual("second");
    expect(result["name"]).toEqual("test");
  });
  test("Q03: Lua-serialized table has integer keys not string keys", () => {
    const wire = Buffer.from(
      "011e526669727374627365636f6e64426e616d654274657374",
      "hex",
    );
    const result = de(wire);
    const keys = Object.keys(result);
    expect(keys.includes("1")).toBe(true);
    expect(keys.includes("2")).toBe(true);
    expect(keys.includes("name")).toBe(true);
    expect(typeof result[1] !== "undefined").toBe(true);
    expect(typeof result[2] !== "undefined").toBe(true);
  });
  test("Q04: mixed integer and string keys roundtrip with correct key types", () => {
    const input = { 1: "first", 2: "second", name: "test" };
    const result = roundtrip(input);
    expect(1 in result).toBe(true);
    expect(2 in result).toBe(true);
    expect("name" in result).toBe(true);
  });
  test("Q05: integer-keyed table serializes as array not table-with-string-keys", () => {
    const wire = ser({ 1: "a", 2: "b" });
    expect(Buffer.from(wire).toString("hex")).toBe("012a12611262");
  });
});

describe("R. Variadic round-trip verification", () => {
  test("R01: single value variadic round-trip", () => {
    expect(roundtrip(42)).toEqual(42);
  });
  test("R02: four mixed-type values variadic round-trip", () => {
    expect(roundtrip("hello")).toEqual("hello");
    expect(roundtrip(42)).toEqual(42);
    expect(roundtrip(true)).toEqual(true);
    expect(Math.abs(roundtrip(3.14) - 3.14)).toBeLessThan(1e-10);
  });
  test("R03: variadic with nil at start and end", () => {
    expect(roundtrip(null)).toBe(null);
    expect(roundtrip("hello")).toEqual("hello");
    expect(roundtrip(null)).toBe(null);
  });
});

describe("S. Nil wire format", () => {
  test("S01: Lua-serialized nil is exactly 01 00", () => {
    const wire = ser(null);
    expect(Buffer.from(wire).toString("hex")).toBe("0100");
  });
});
