// Auto-generated by testing/generate-tests.py — DO NOT EDIT
'use strict';
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const Pipeline = require('../lib/Pipeline');

describe('A. Prefix encoding', () => {
    test('A1: WA v1 uses ! prefix', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 1, data: 'x', metadata: null });
        assert.ok(enc.startsWith('!'), `Expected ! prefix, got: ${enc.slice(0, 10)}`);
        assert.ok(!enc.startsWith('!WA:2!'));
        assert.ok(!enc.startsWith('!E1!'));
    });
    test('A2: ElvUI uses !E1! prefix', () => {
        const enc = Pipeline.encode({ addon: 'elvui', version: 1, data: 'x', metadata: null });
        assert.ok(enc.startsWith('!E1!'), `Expected !E1! prefix, got: ${enc.slice(0, 10)}`);
    });
    test('A3: legacy (v0) uses no prefix', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 0, data: 'x', metadata: null });
        assert.ok(!enc.startsWith('!'));
    });
    test('A4: WA v2 uses !WA:2! prefix', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 2, data: { a: 1 }, metadata: null });
        assert.ok(enc.startsWith('!WA:2!'), `Expected !WA:2! prefix, got: ${enc.slice(0, 10)}`);
    });
});

describe('B. Prefix detection', () => {
    test('B1: !E1! detected as elvui v1', () => {
        const enc = Pipeline.encode({ addon: 'elvui', version: 1, data: { a: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'elvui');
        assert.strictEqual(dec.version, 1);
    });
    test('B2: ! detected as weakauras v1', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 1, data: { a: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'weakauras');
        assert.strictEqual(dec.version, 1);
    });
    test('B3: no prefix detected as weakauras v0 (legacy)', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 0, data: { a: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'weakauras');
        assert.strictEqual(dec.version, 0);
    });
    test('B4: !WA:2! detected as weakauras v2', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 2, data: { a: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.strictEqual(dec.addon, 'weakauras');
        assert.strictEqual(dec.version, 2);
    });
});

describe('C. ExportResult structure', () => {
    test('C1: decode returns all four fields', () => {
        const enc = Pipeline.encode({ addon: 'weakauras', version: 1, data: { x: 1 }, metadata: null });
        const dec = Pipeline.decode(enc);
        assert.ok('addon'    in dec, 'missing addon');
        assert.ok('version'  in dec, 'missing version');
        assert.ok('data'     in dec, 'missing data');
        assert.ok('metadata' in dec, 'missing metadata');
    });
});

describe('D. Round-trips', () => {
    test('D1: WA v1 string', () => {
        const orig = { addon: 'weakauras', version: 1, data: 'hello', metadata: null };
        const dec = Pipeline.decode(Pipeline.encode(orig));
        assert.strictEqual(dec.data, 'hello');
        assert.strictEqual(dec.addon, 'weakauras');
        assert.strictEqual(dec.version, 1);
        assert.strictEqual(dec.metadata, null);
    });
    test('D2: WA v1 table', () => {
        const data = { key: 'value', num: 42 };
        const dec = Pipeline.decode(Pipeline.encode({ addon: 'weakauras', version: 1, data, metadata: null }));
        assert.deepStrictEqual(dec.data['key'], 'value');
        assert.deepStrictEqual(dec.data['num'], 42);
    });
    test('D3: WA v1 array', () => {
        const data = { 1: 'a', 2: 'b', 3: 'c' };
        const dec = Pipeline.decode(Pipeline.encode({ addon: 'weakauras', version: 1, data, metadata: null }));
        assert.deepStrictEqual(dec.data, data);
    });
    test('D4: WA v1 nested table', () => {
        const data = { outer: { inner: 99 }, list: { 1: 1, 2: 2 } };
        const dec = Pipeline.decode(Pipeline.encode({ addon: 'weakauras', version: 1, data, metadata: null }));
        assert.strictEqual(dec.data.outer.inner, 99);
        assert.deepStrictEqual(dec.data.list, { 1: 1, 2: 2 });
    });
    test('D5: legacy v0 round-trip', () => {
        const data = { flag: true, n: -5 };
        const dec = Pipeline.decode(Pipeline.encode({ addon: 'weakauras', version: 0, data, metadata: null }));
        assert.deepStrictEqual(dec.data['flag'], true);
        assert.deepStrictEqual(dec.data['n'], -5);
    });
    test('D6: WA v2 round-trip', () => {
        const data = { key: 'v2data', num: 7 };
        const dec = Pipeline.decode(Pipeline.encode({ addon: 'weakauras', version: 2, data, metadata: null }));
        assert.deepStrictEqual(dec.data['key'], 'v2data');
        assert.deepStrictEqual(dec.data['num'], 7);
    });
});

describe('E. ElvUI metadata', () => {
    test('E1: round-trip preserves metadata profileType and profileKey', () => {
        const metadata = { profileType: 'profile', profileKey: 'Default' };
        const orig = { addon: 'elvui', version: 1, data: { setting: 1 }, metadata };
        const dec = Pipeline.decode(Pipeline.encode(orig));
        assert.strictEqual(dec.addon, 'elvui');
        assert.deepStrictEqual(dec.metadata, metadata);
        assert.strictEqual(dec.data.setting, 1);
    });
    test('E2: ElvUI without metadata gives null metadata after decode', () => {
        const orig = { addon: 'elvui', version: 1, data: { a: 1 }, metadata: null };
        const dec = Pipeline.decode(Pipeline.encode(orig));
        assert.strictEqual(dec.metadata, null);
    });
});

