// Auto-generated by testing/generate-tests.py — DO NOT EDIT
import { test, describe, expect } from "bun:test";
import Pipeline from "../lib/Pipeline.js";

describe("A. Prefix encoding", () => {
  test("A1: WA v1 uses ! prefix", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 1,
      data: "x",
      metadata: null,
    });
    expect(enc.startsWith("!")).toBe(true);
    expect(enc.startsWith("!WA:2!")).toBe(false);
    expect(enc.startsWith("!E1!")).toBe(false);
  });
  test("A2: ElvUI uses !E1! prefix", () => {
    const enc = Pipeline.encode({
      addon: "elvui",
      version: 1,
      data: "x",
      metadata: null,
    });
    expect(enc.startsWith("!E1!")).toBe(true);
  });
  test("A3: legacy (v0) uses no prefix", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 0,
      data: "x",
      metadata: null,
    });
    expect(enc.startsWith("!")).toBe(false);
  });
  test("A4: WA v2 uses !WA:2! prefix", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 2,
      data: { a: 1 },
      metadata: null,
    });
    expect(enc.startsWith("!WA:2!")).toBe(true);
  });
});

describe("B. Prefix detection", () => {
  test("B1: !E1! detected as elvui v1", () => {
    const enc = Pipeline.encode({
      addon: "elvui",
      version: 1,
      data: { a: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("elvui");
    expect(dec.version).toBe(1);
  });
  test("B2: ! detected as weakauras v1", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 1,
      data: { a: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("weakauras");
    expect(dec.version).toBe(1);
  });
  test("B3: no prefix detected as weakauras v0 (legacy)", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 0,
      data: { a: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("weakauras");
    expect(dec.version).toBe(0);
  });
  test("B4: !WA:2! detected as weakauras v2", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 2,
      data: { a: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect(dec.addon).toBe("weakauras");
    expect(dec.version).toBe(2);
  });
});

describe("C. ExportResult structure", () => {
  test("C1: decode returns all four fields", () => {
    const enc = Pipeline.encode({
      addon: "weakauras",
      version: 1,
      data: { x: 1 },
      metadata: null,
    });
    const dec = Pipeline.decode(enc);
    expect("addon" in dec).toBe(true);
    expect("version" in dec).toBe(true);
    expect("data" in dec).toBe(true);
    expect("metadata" in dec).toBe(true);
  });
});

describe("D. Round-trips", () => {
  test("D1: WA v1 string", () => {
    const orig = {
      addon: "weakauras",
      version: 1,
      data: "hello",
      metadata: null,
    };
    const dec = Pipeline.decode(Pipeline.encode(orig));
    expect(dec.data).toBe("hello");
    expect(dec.addon).toBe("weakauras");
    expect(dec.version).toBe(1);
    expect(dec.metadata).toBe(null);
  });
  test("D2: WA v1 table", () => {
    const data = { key: "value", num: 42 };
    const dec = Pipeline.decode(
      Pipeline.encode({ addon: "weakauras", version: 1, data, metadata: null }),
    );
    expect(dec.data["key"]).toEqual("value");
    expect(dec.data["num"]).toEqual(42);
  });
  test("D3: WA v1 array", () => {
    const data = { 1: "a", 2: "b", 3: "c" };
    const dec = Pipeline.decode(
      Pipeline.encode({ addon: "weakauras", version: 1, data, metadata: null }),
    );
    expect(dec.data).toEqual(data);
  });
  test("D4: WA v1 nested table", () => {
    const data = { outer: { inner: 99 }, list: { 1: 1, 2: 2 } };
    const dec = Pipeline.decode(
      Pipeline.encode({ addon: "weakauras", version: 1, data, metadata: null }),
    );
    expect(dec.data.outer.inner).toBe(99);
    expect(dec.data.list).toEqual({ 1: 1, 2: 2 });
  });
  test("D5: legacy v0 round-trip", () => {
    const data = { flag: true, n: -5 };
    const dec = Pipeline.decode(
      Pipeline.encode({ addon: "weakauras", version: 0, data, metadata: null }),
    );
    expect(dec.data["flag"]).toEqual(true);
    expect(dec.data["n"]).toEqual(-5);
  });
  test("D6: WA v2 round-trip", () => {
    const data = { key: "v2data", num: 7 };
    const dec = Pipeline.decode(
      Pipeline.encode({ addon: "weakauras", version: 2, data, metadata: null }),
    );
    expect(dec.data["key"]).toEqual("v2data");
    expect(dec.data["num"]).toEqual(7);
  });
});

describe("E. ElvUI metadata", () => {
  test("E1: round-trip preserves metadata profileType and profileKey", () => {
    const metadata = { profileType: "profile", profileKey: "Default" };
    const orig = { addon: "elvui", version: 1, data: { setting: 1 }, metadata };
    const dec = Pipeline.decode(Pipeline.encode(orig));
    expect(dec.addon).toBe("elvui");
    expect(dec.metadata).toEqual(metadata);
    expect(dec.data.setting).toBe(1);
  });
  test("E2: ElvUI without metadata gives null metadata after decode", () => {
    const orig = { addon: "elvui", version: 1, data: { a: 1 }, metadata: null };
    const dec = Pipeline.decode(Pipeline.encode(orig));
    expect(dec.metadata).toBe(null);
  });
});
