# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/azerite/all/azerite.rbi
#
# azerite-0.1.0

module Azerite
end
class Azerite::LuaDeflateNative
end
