# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rbs/all/rbs.rbi
#
# rbs-4.0.2

module RBS
  def self.logger; end
  def self.logger_level; end
  def self.logger_level=(level); end
  def self.logger_output; end
  def self.logger_output=(val); end
  def self.print_warning; end
end
module RBS::MethodNameHelper
  def method_name_string; end
end
class RBS::BaseError < StandardError
end
class RBS::LoadingError < RBS::BaseError
end
class RBS::DefinitionError < RBS::BaseError
end
module RBS::DetailedMessageable
  def detailed_message(highlight: nil, **); end
end
class RBS::ParsingError < RBS::BaseError
  def error_message; end
  def initialize(location, error_message, token_type); end
  def location; end
  def token_type; end
  include RBS::DetailedMessageable
end
class RBS::InvalidTypeApplicationError < RBS::DefinitionError
  def args; end
  def initialize(type_name:, args:, params:, location:); end
  def location; end
  def params; end
  def self.check!(type_name:, args:, params:, location:); end
  def self.check2!(env:, type_name:, args:, location:); end
  def type_name; end
  def type_params; end
end
class RBS::RecursiveAncestorError < RBS::DefinitionError
  def ancestors; end
  def initialize(ancestors:, location:); end
  def location; end
  def self.check!(self_ancestor, ancestors:, location:); end
end
class RBS::NoTypeFoundError < RBS::DefinitionError
  def initialize(type_name:, location:); end
  def location; end
  def self.check!(type_name, env:, location:); end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::NoSuperclassFoundError < RBS::DefinitionError
  def initialize(type_name:, location:); end
  def location; end
  def self.check!(type_name, env:, location:); end
  def type_name; end
end
class RBS::InheritModuleError < RBS::DefinitionError
  def initialize(super_decl); end
  def location; end
  def self.check!(super_decl, env:); end
  def super_decl; end
  include RBS::DetailedMessageable
end
class RBS::NoSelfTypeFoundError < RBS::DefinitionError
  def initialize(type_name:, location:); end
  def location; end
  def self.check!(self_type, env:); end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::NoMixinFoundError < RBS::DefinitionError
  def initialize(type_name:, member:); end
  def location; end
  def member; end
  def self.check!(type_name, env:, member:); end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::DuplicatedMethodDefinitionError < RBS::DefinitionError
  def initialize(type:, method_name:, members:); end
  def location; end
  def members; end
  def method_name; end
  def other_locations; end
  def qualified_method_name; end
  def type; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::DuplicatedInterfaceMethodDefinitionError < RBS::DefinitionError
  def initialize(type:, method_name:, member:); end
  def location; end
  def member; end
  def method_name; end
  def qualified_method_name; end
  def type; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::VariableDuplicationError < RBS::DefinitionError
  def initialize(type_name:, variable_name:, location:); end
  def location; end
  def type_name; end
  def variable_name; end
  include RBS::DetailedMessageable
end
class RBS::InstanceVariableDuplicationError < RBS::VariableDuplicationError
  def kind; end
end
class RBS::ClassInstanceVariableDuplicationError < RBS::VariableDuplicationError
  def kind; end
end
class RBS::UnknownMethodAliasError < RBS::DefinitionError
  def aliased_name; end
  def initialize(type_name:, original_name:, aliased_name:, location:); end
  def location; end
  def original_name; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::SuperclassMismatchError < RBS::DefinitionError
  def entry; end
  def initialize(name:, entry:); end
  def name; end
end
class RBS::InvalidOverloadMethodError < RBS::DefinitionError
  def initialize(type_name:, method_name:, kind:, members:); end
  def kind; end
  def location; end
  def members; end
  def method_name; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::GenericParameterMismatchError < RBS::LoadingError
  def decl; end
  def initialize(name:, decl:, location: nil); end
  def name; end
end
class RBS::DuplicatedDeclarationError < RBS::LoadingError
  def decls; end
  def initialize(name, *decls); end
  def name; end
end
class RBS::InvalidVarianceAnnotationError < RBS::DefinitionError
  def initialize(type_name:, param:, location:); end
  def location; end
  def param; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::RecursiveAliasDefinitionError < RBS::DefinitionError
  def defs; end
  def initialize(type:, defs:); end
  def location; end
  def type; end
  include RBS::DetailedMessageable
end
class RBS::MixinClassError < RBS::DefinitionError
  def initialize(type_name:, member:); end
  def location; end
  def member; end
  def member_name(member); end
  def mixin_name; end
  def self.check!(type_name:, env:, member:); end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::RecursiveTypeAliasError < RBS::BaseError
  def alias_names; end
  def initialize(alias_names:, location:); end
  def location; end
  def name; end
  include RBS::DetailedMessageable
end
class RBS::NonregularTypeAliasError < RBS::BaseError
  def diagnostic; end
  def initialize(diagnostic:, location:); end
  def location; end
  include RBS::DetailedMessageable
end
class RBS::CyclicTypeParameterBound < RBS::BaseError
  def initialize(type_name:, method_name:, params:, location:); end
  def location; end
  def method_name; end
  def params; end
  def type_name; end
  include RBS::DetailedMessageable
end
class RBS::InconsistentClassModuleAliasError < RBS::BaseError
  def alias_entry; end
  def initialize(entry); end
  def location; end
  include RBS::DetailedMessageable
end
class RBS::CyclicClassAliasDefinitionError < RBS::BaseError
  def alias_entry; end
  def initialize(entry); end
  def location; end
  include RBS::DetailedMessageable
end
class RBS::TypeParamDefaultReferenceError < RBS::DefinitionError
  def initialize(type_param, location:); end
  def location; end
  def self.check!(type_params); end
  def type_param; end
  include RBS::DetailedMessageable
end
class RBS::Buffer
  def absolute_position(position); end
  def content; end
  def detach; end
  def initialize(content:, name: nil, parent: nil); end
  def inspect; end
  def last_position; end
  def line_count; end
  def lines; end
  def loc_to_pos(loc); end
  def name; end
  def parent; end
  def parent_buffer; end
  def parent_position(position); end
  def pos_to_loc(pos); end
  def ranges; end
  def rbs_location(location, loc2 = nil); end
  def sub_buffer(lines:); end
  def top_buffer; end
end
class RBS::Namespace
  def +(other); end
  def ==(other); end
  def absolute!; end
  def absolute?; end
  def append(component); end
  def ascend; end
  def empty?; end
  def eql?(other); end
  def hash; end
  def initialize(path:, absolute:); end
  def parent; end
  def path; end
  def relative!; end
  def relative?; end
  def self.empty; end
  def self.parse(string); end
  def self.root; end
  def split; end
  def to_s; end
  def to_type_name; end
end
class RBS::TypeName
  def +(other); end
  def ==(other); end
  def absolute!; end
  def absolute?; end
  def alias?; end
  def class?; end
  def eql?(other); end
  def hash; end
  def initialize(namespace:, name:); end
  def interface?; end
  def kind; end
  def name; end
  def namespace; end
  def relative!; end
  def self.parse(string); end
  def split; end
  def to_json(state = nil); end
  def to_namespace; end
  def to_s; end
  def with_prefix(namespace); end
end
module RBS::Types
end
module RBS::Types::NoFreeVariables
  def free_variables(set = nil); end
end
module RBS::Types::NoSubst
  def sub(s); end
end
module RBS::Types::NoTypeName
  def map_type_name(&); end
end
module RBS::Types::EmptyEachType
  def each_type; end
  def map_type(&block); end
end
module RBS::Types::Bases
end
class RBS::Types::Bases::Base
  def ==(other); end
  def eql?(other); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(location:); end
  def location; end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def with_nonreturn_void?; end
  include RBS::Types::EmptyEachType
  include RBS::Types::NoFreeVariables
  include RBS::Types::NoSubst
  include RBS::Types::NoTypeName
end
class RBS::Types::Bases::Bool < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Void < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Any < RBS::Types::Bases::Base
  def initialize(location:, todo: nil); end
  def to_s(level = nil); end
end
class RBS::Types::Bases::Nil < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Top < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Bottom < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Self < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Instance < RBS::Types::Bases::Base
  def sub(s); end
end
class RBS::Types::Bases::Class < RBS::Types::Bases::Base
end
class RBS::Types::Variable
  def ==(other); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(name:, location:); end
  def location; end
  def name; end
  def self.build(v); end
  def self.fresh(v = nil); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def with_nonreturn_void?; end
  include RBS::Types::EmptyEachType
  include RBS::Types::NoTypeName
end
module RBS::Types::Application
  def ==(other); end
  def args; end
  def each_type(&block); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def name; end
  def to_s(level = nil); end
  def with_nonreturn_void?; end
end
class RBS::Types::ClassSingleton
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(name:, location:, args: nil); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  include RBS::Types::Application
end
class RBS::Types::Interface
  def initialize(name:, args:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  include RBS::Types::Application
end
class RBS::Types::ClassInstance
  def initialize(name:, args:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  include RBS::Types::Application
end
class RBS::Types::Alias
  def initialize(name:, args:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  include RBS::Types::Application
end
class RBS::Types::Tuple
  def ==(other); end
  def each_type(&block); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(types:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def types; end
  def with_nonreturn_void?; end
end
class RBS::Types::Record
  def ==(other); end
  def all_fields; end
  def each_type(&block); end
  def eql?(other); end
  def fields; end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(location:, all_fields: nil, fields: nil); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def optional_fields; end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def with_nonreturn_void?; end
end
class RBS::Types::Optional
  def ==(other); end
  def each_type; end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(type:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def type; end
  def with_nonreturn_void?; end
end
class RBS::Types::Union
  def ==(other); end
  def each_type(&block); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(types:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def types; end
  def with_nonreturn_void?; end
end
class RBS::Types::Intersection
  def ==(other); end
  def each_type(&block); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(types:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def types; end
  def with_nonreturn_void?; end
end
class RBS::Types::Function
  def ==(other); end
  def amap(array, &block); end
  def drop_head; end
  def drop_tail; end
  def each_param(&block); end
  def each_type; end
  def empty?; end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_keyword?; end
  def has_self_type?; end
  def hash; end
  def hmapv(hash, &block); end
  def initialize(required_positionals:, optional_positionals:, rest_positionals:, trailing_positionals:, required_keywords:, optional_keywords:, rest_keywords:, return_type:); end
  def map_type(&block); end
  def map_type_name(&block); end
  def optional_keywords; end
  def optional_positionals; end
  def param_to_s; end
  def required_keywords; end
  def required_positionals; end
  def rest_keywords; end
  def rest_positionals; end
  def return_to_s; end
  def return_type; end
  def self.empty(return_type); end
  def sub(s); end
  def to_json(state = nil); end
  def trailing_positionals; end
  def update(required_positionals: nil, optional_positionals: nil, rest_positionals: nil, trailing_positionals: nil, required_keywords: nil, optional_keywords: nil, rest_keywords: nil, return_type: nil); end
  def with_nonreturn_void?; end
  def with_return_type(type); end
end
class RBS::Types::Function::Param
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(type:, name:, location: nil); end
  def location; end
  def map_type(&block); end
  def name; end
  def to_json(state = nil); end
  def to_s; end
  def type; end
end
class RBS::Types::UntypedFunction
  def ==(other); end
  def each_param(&block); end
  def each_type(&block); end
  def empty?; end
  def eql?(other); end
  def free_variables(acc = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(return_type:); end
  def map_type(&block); end
  def map_type_name(&block); end
  def param_to_s; end
  def return_to_s; end
  def return_type; end
  def sub(subst); end
  def to_json(state = nil); end
  def update(return_type: nil); end
  def with_nonreturn_void?; end
  def with_return_type(ty); end
end
class RBS::Types::Block
  def ==(other); end
  def initialize(type:, required:, location: nil, self_type: nil); end
  def location; end
  def map_type(&block); end
  def required; end
  def self_type; end
  def sub(s); end
  def to_json(state = nil); end
  def type; end
end
module RBS::Types::SelfTypeBindingHelper
  def self.self_type_binding_to_s(t); end
  def self_type_binding_to_s(t); end
end
class RBS::Types::Proc
  def ==(other); end
  def block; end
  def each_type(&block); end
  def eql?(other); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(location:, type:, block:, self_type: nil); end
  def location; end
  def map_type(&block); end
  def map_type_name(&block); end
  def self_type; end
  def sub(s); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def type; end
  def with_nonreturn_void?; end
end
class RBS::Types::Literal
  def ==(other); end
  def eql?(other); end
  def has_classish_type?; end
  def has_self_type?; end
  def hash; end
  def initialize(literal:, location:); end
  def literal; end
  def location; end
  def self.unescape_string(string, is_double_quote); end
  def to_json(state = nil); end
  def to_s(level = nil); end
  def with_nonreturn_void?; end
  include RBS::Types::EmptyEachType
  include RBS::Types::NoFreeVariables
  include RBS::Types::NoSubst
  include RBS::Types::NoTypeName
end
class RBS::MethodType
  def ==(other); end
  def block; end
  def each_type(&block); end
  def free_variables(set = nil); end
  def has_classish_type?; end
  def has_self_type?; end
  def initialize(type_params:, type:, block:, location:); end
  def location; end
  def map_type(&block); end
  def map_type_bound(&block); end
  def sub(s); end
  def to_json(state = nil); end
  def to_s; end
  def type; end
  def type_param_names; end
  def type_params; end
  def update(type_params: nil, type: nil, block: nil, location: nil); end
  def with_nonreturn_void?; end
end
module RBS::FileFinder
  def self.each_file(path, skip_hidden:, immediate: nil, &block); end
end
module RBS::AST
end
class RBS::AST::TypeParam
  def ==(other); end
  def default_type; end
  def eql?(other); end
  def hash; end
  def initialize(name:, variance:, upper_bound:, lower_bound:, location:, default_type: nil, unchecked: nil); end
  def location; end
  def lower_bound; end
  def lower_bound_type; end
  def map_type(&block); end
  def name; end
  def self.application(params, args); end
  def self.normalize_args(params, args); end
  def self.rename(params, new_names:); end
  def self.resolve_variables(params); end
  def self.subst_var(vars, type); end
  def self.validate(type_params); end
  def to_json(state = nil); end
  def to_s; end
  def unchecked!(value = nil); end
  def unchecked?; end
  def upper_bound; end
  def upper_bound_type; end
  def variance; end
end
module RBS::AST::Directives
end
class RBS::AST::Directives::Base
end
class RBS::AST::Directives::Use < RBS::AST::Directives::Base
  def clauses; end
  def initialize(clauses:, location:); end
  def location; end
end
class RBS::AST::Directives::Use::SingleClause
  def initialize(type_name:, new_name:, location:); end
  def location; end
  def new_name; end
  def type_name; end
end
class RBS::AST::Directives::Use::WildcardClause
  def initialize(namespace:, location:); end
  def location; end
  def namespace; end
end
class RBS::AST::Directives::ResolveTypeNames < RBS::AST::Directives::Base
  def initialize(value:, location:); end
  def location; end
  def value; end
end
module RBS::AST::Declarations
end
class RBS::AST::Declarations::Base
end
module RBS::AST::Declarations::NestedDeclarationHelper
  def each_decl; end
  def each_member; end
end
module RBS::AST::Declarations::MixinHelper
  def each_mixin(&block); end
end
class RBS::AST::Declarations::Class < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type_params:, super_class:, members:, annotations:, location:, comment:); end
  def location; end
  def members; end
  def name; end
  def super_class; end
  def to_json(state = nil); end
  def type_params; end
  def update(name: nil, type_params: nil, super_class: nil, members: nil, annotations: nil, location: nil, comment: nil); end
  include RBS::AST::Declarations::MixinHelper
  include RBS::AST::Declarations::NestedDeclarationHelper
end
class RBS::AST::Declarations::Class::Super
  def ==(other); end
  def args; end
  def eql?(other); end
  def hash; end
  def initialize(name:, args:, location:); end
  def location; end
  def name; end
  def to_json(state = nil); end
end
class RBS::AST::Declarations::Module < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type_params:, members:, self_types:, annotations:, location:, comment:); end
  def location; end
  def members; end
  def name; end
  def self_types; end
  def to_json(state = nil); end
  def type_params; end
  def update(name: nil, type_params: nil, members: nil, self_types: nil, annotations: nil, location: nil, comment: nil); end
  include RBS::AST::Declarations::MixinHelper
  include RBS::AST::Declarations::NestedDeclarationHelper
end
class RBS::AST::Declarations::Module::Self
  def ==(other); end
  def args; end
  def eql?(other); end
  def hash; end
  def initialize(name:, args:, location:); end
  def location; end
  def name; end
  def to_json(state = nil); end
  def to_s; end
end
class RBS::AST::Declarations::Interface < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type_params:, members:, annotations:, location:, comment:); end
  def location; end
  def members; end
  def name; end
  def to_json(state = nil); end
  def type_params; end
  def update(name: nil, type_params: nil, members: nil, annotations: nil, location: nil, comment: nil); end
  include RBS::AST::Declarations::MixinHelper
end
class RBS::AST::Declarations::TypeAlias < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type_params:, type:, annotations:, location:, comment:); end
  def location; end
  def name; end
  def to_json(state = nil); end
  def type; end
  def type_params; end
end
class RBS::AST::Declarations::Constant < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type:, location:, comment:, annotations: nil); end
  def location; end
  def name; end
  def to_json(state = nil); end
  def type; end
end
class RBS::AST::Declarations::Global < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type:, location:, comment:, annotations: nil); end
  def location; end
  def name; end
  def to_json(state = nil); end
  def type; end
end
class RBS::AST::Declarations::AliasDecl < RBS::AST::Declarations::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(new_name:, old_name:, location:, comment:, annotations: nil); end
  def location; end
  def new_name; end
  def old_name; end
end
class RBS::AST::Declarations::ClassAlias < RBS::AST::Declarations::AliasDecl
  def to_json(state = nil); end
end
class RBS::AST::Declarations::ModuleAlias < RBS::AST::Declarations::AliasDecl
  def to_json(state = nil); end
end
module RBS::AST::Members
end
class RBS::AST::Members::Base
end
class RBS::AST::Members::MethodDefinition < RBS::AST::Members::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, kind:, overloads:, annotations:, location:, comment:, overloading:, visibility:); end
  def instance?; end
  def kind; end
  def location; end
  def name; end
  def overloading; end
  def overloading?; end
  def overloads; end
  def singleton?; end
  def to_json(state = nil); end
  def update(name: nil, kind: nil, overloads: nil, annotations: nil, location: nil, comment: nil, overloading: nil, visibility: nil); end
  def visibility; end
end
class RBS::AST::Members::MethodDefinition::Overload
  def ==(other); end
  def annotations; end
  def eql?(other); end
  def hash; end
  def initialize(method_type:, annotations:); end
  def method_type; end
  def sub(subst); end
  def to_json(state = nil); end
  def update(annotations: nil, method_type: nil); end
end
module RBS::AST::Members::Var
  def ==(other); end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type:, location:, comment:); end
  def location; end
  def name; end
  def type; end
end
class RBS::AST::Members::InstanceVariable < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Var
end
class RBS::AST::Members::ClassInstanceVariable < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Var
end
class RBS::AST::Members::ClassVariable < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Var
end
module RBS::AST::Members::Mixin
  def ==(other); end
  def annotations; end
  def args; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, args:, annotations:, location:, comment:); end
  def location; end
  def name; end
end
class RBS::AST::Members::Include < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Mixin
end
class RBS::AST::Members::Extend < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Mixin
end
class RBS::AST::Members::Prepend < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Mixin
end
module RBS::AST::Members::Attribute
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type:, ivar_name:, kind:, annotations:, location:, comment:, visibility: nil); end
  def ivar_name; end
  def kind; end
  def location; end
  def name; end
  def type; end
  def update(name: nil, type: nil, ivar_name: nil, kind: nil, annotations: nil, location: nil, comment: nil, visibility: nil); end
  def visibility; end
end
class RBS::AST::Members::AttrReader < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Attribute
end
class RBS::AST::Members::AttrAccessor < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Attribute
end
class RBS::AST::Members::AttrWriter < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::Attribute
end
module RBS::AST::Members::LocationOnly
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(location:); end
  def location; end
end
class RBS::AST::Members::Public < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::LocationOnly
end
class RBS::AST::Members::Private < RBS::AST::Members::Base
  def to_json(state = nil); end
  include RBS::AST::Members::LocationOnly
end
class RBS::AST::Members::Alias < RBS::AST::Members::Base
  def ==(other); end
  def annotations; end
  def comment; end
  def eql?(other); end
  def hash; end
  def initialize(new_name:, old_name:, kind:, annotations:, location:, comment:); end
  def instance?; end
  def kind; end
  def location; end
  def new_name; end
  def old_name; end
  def singleton?; end
  def to_json(state = nil); end
end
class RBS::AST::Annotation
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(string:, location:); end
  def location; end
  def string; end
  def to_json(state = nil); end
end
class RBS::AST::Visitor
  def visit(node); end
  def visit_all(nodes); end
  def visit_declaration_class(node); end
  def visit_declaration_constant(node); end
  def visit_declaration_global(node); end
  def visit_declaration_interface(node); end
  def visit_declaration_module(node); end
  def visit_declaration_type_alias(node); end
  def visit_member_alias(node); end
  def visit_member_attr_accessor(node); end
  def visit_member_attr_reader(node); end
  def visit_member_attr_writer(node); end
  def visit_member_class_instance_variable(node); end
  def visit_member_class_variable(node); end
  def visit_member_extend(node); end
  def visit_member_include(node); end
  def visit_member_instance_variable(node); end
  def visit_member_method_definition(node); end
  def visit_member_prepend(node); end
  def visit_member_private(node); end
  def visit_member_public(node); end
end
module RBS::AST::Ruby
end
class RBS::AST::Ruby::CommentBlock
  def as_comment; end
  def comment_buffer; end
  def comments; end
  def each_paragraph(variables, &block); end
  def end_line; end
  def initialize(source_buffer, comments); end
  def leading?; end
  def leading_annotation?(index); end
  def line_location(start_line, end_line); end
  def line_starts; end
  def location; end
  def name; end
  def offsets; end
  def parse_annotation_lines(start_line, end_line, variables); end
  def self.build(buffer, comments); end
  def start_line; end
  def text(comment_index); end
  def trailing?; end
  def trailing_annotation(variables); end
  def yield_annotation(start_line, end_line, current_line, variables, &block); end
  def yield_paragraph(start_line, current_line, variables, &block); end
end
class RBS::AST::Ruby::CommentBlock::AnnotationSyntaxError < Struct
  def error; end
  def error=(_); end
  def location; end
  def location=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
end
module RBS::AST::Ruby::Helpers
end
module RBS::AST::Ruby::Helpers::ConstantHelper
  def constant_as_type_name(node); end
  def self.constant_as_type_name(node); end
end
module RBS::AST::Ruby::Helpers::LocationHelper
  def rbs_location(location); end
end
module RBS::AST::Ruby::Annotations
end
class RBS::AST::Ruby::Annotations::Base
  def buffer; end
  def initialize(location, prefix_location); end
  def location; end
  def prefix_location; end
end
class RBS::AST::Ruby::Annotations::NodeTypeAssertion < RBS::AST::Ruby::Annotations::Base
  def initialize(location:, prefix_location:, type:); end
  def map_type_name; end
  def type; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::AliasAnnotation < RBS::AST::Ruby::Annotations::Base
  def initialize(location:, prefix_location:, keyword_location:, type_name:, type_name_location:); end
  def keyword_location; end
  def map_type_name; end
  def type_name; end
  def type_name_location; end
end
class RBS::AST::Ruby::Annotations::ClassAliasAnnotation < RBS::AST::Ruby::Annotations::AliasAnnotation
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::ModuleAliasAnnotation < RBS::AST::Ruby::Annotations::AliasAnnotation
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::ColonMethodTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def annotations; end
  def initialize(location:, prefix_location:, annotations:, method_type:); end
  def map_type_name; end
  def method_type; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::MethodTypesAnnotation < RBS::AST::Ruby::Annotations::Base
  def dot3_location; end
  def initialize(location:, prefix_location:, overloads:, vertical_bar_locations:, dot3_location:); end
  def map_type_name(&block); end
  def overloads; end
  def type_fingerprint; end
  def vertical_bar_locations; end
end
class RBS::AST::Ruby::Annotations::SkipAnnotation < RBS::AST::Ruby::Annotations::Base
  def comment_location; end
  def initialize(location:, prefix_location:, skip_location:, comment_location:); end
  def skip_location; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::ReturnTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, return_location:, colon_location:, return_type:, comment_location:); end
  def map_type_name(&block); end
  def return_location; end
  def return_type; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::TypeApplicationAnnotation < RBS::AST::Ruby::Annotations::Base
  def close_bracket_location; end
  def comma_locations; end
  def initialize(location:, prefix_location:, type_args:, close_bracket_location:, comma_locations:); end
  def map_type_name(&block); end
  def type_args; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::InstanceVariableAnnotation < RBS::AST::Ruby::Annotations::Base
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, ivar_name:, ivar_name_location:, colon_location:, type:, comment_location:); end
  def ivar_name; end
  def ivar_name_location; end
  def map_type_name(&block); end
  def type; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::ParamTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, name_location:, colon_location:, param_type:, comment_location:); end
  def map_type_name(&block); end
  def name_location; end
  def param_type; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::SplatParamTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, star_location:, name_location:, colon_location:, param_type:, comment_location:); end
  def map_type_name(&block); end
  def name_location; end
  def param_type; end
  def star_location; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::DoubleSplatParamTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, star2_location:, name_location:, colon_location:, param_type:, comment_location:); end
  def map_type_name(&block); end
  def name_location; end
  def param_type; end
  def star2_location; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Annotations::BlockParamTypeAnnotation < RBS::AST::Ruby::Annotations::Base
  def ampersand_location; end
  def colon_location; end
  def comment_location; end
  def initialize(location:, prefix_location:, ampersand_location:, name_location:, colon_location:, question_location:, type_location:, type:, comment_location:); end
  def map_type_name(&block); end
  def name; end
  def name_location; end
  def optional?; end
  def question_location; end
  def required?; end
  def type; end
  def type_fingerprint; end
  def type_location; end
end
module RBS::AST::Ruby::Declarations
end
class RBS::AST::Ruby::Declarations::Base
  def buffer; end
  def initialize(buffer); end
  include RBS::AST::Ruby::Helpers::ConstantHelper
  include RBS::AST::Ruby::Helpers::LocationHelper
end
class RBS::AST::Ruby::Declarations::ClassDecl < RBS::AST::Ruby::Declarations::Base
  def class_name; end
  def each_decl(&block); end
  def initialize(buffer, name, node, super_class); end
  def location; end
  def members; end
  def name_location; end
  def node; end
  def super_class; end
  def type_fingerprint; end
  def type_params; end
end
class RBS::AST::Ruby::Declarations::ClassDecl::SuperClass
  def args; end
  def initialize(type_name_location, operator_location, type_name, type_annotation); end
  def location; end
  def name; end
  def operator_location; end
  def type_annotation; end
  def type_args; end
  def type_fingerprint; end
  def type_name; end
  def type_name_location; end
end
class RBS::AST::Ruby::Declarations::ModuleDecl < RBS::AST::Ruby::Declarations::Base
  def each_decl(&block); end
  def initialize(buffer, name, node); end
  def location; end
  def members; end
  def module_name; end
  def name_location; end
  def node; end
  def self_types; end
  def type_fingerprint; end
  def type_params; end
end
class RBS::AST::Ruby::Declarations::ConstantDecl < RBS::AST::Ruby::Declarations::Base
  def comment; end
  def constant_name; end
  def initialize(buffer, constant_name, node, leading_comment, type_annotation); end
  def leading_comment; end
  def location; end
  def name_location; end
  def node; end
  def type; end
  def type_annotation; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Declarations::ClassModuleAliasDecl < RBS::AST::Ruby::Declarations::Base
  def annotation; end
  def comment; end
  def infered_old_name; end
  def initialize(buffer, node, new_name, infered_old_name, leading_comment, annotation); end
  def leading_comment; end
  def location; end
  def name_location; end
  def new_name; end
  def node; end
  def old_name; end
  def type_fingerprint; end
end
module RBS::AST::Ruby::Members
end
class RBS::AST::Ruby::Members::Base
  def buffer; end
  def initialize(buffer); end
  include RBS::AST::Ruby::Helpers::LocationHelper
end
class RBS::AST::Ruby::Members::MethodTypeAnnotation
  def empty?; end
  def initialize(type_annotations:); end
  def map_type_name(&block); end
  def overloading?; end
  def overloads; end
  def self.build(leading_block, trailing_block, variables, node); end
  def type_annotations; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Members::MethodTypeAnnotation::DocStyle
  def all_param_annotations; end
  def block; end
  def block=(arg0); end
  def initialize; end
  def map_type_name(&block); end
  def method_type; end
  def optional_keywords; end
  def optional_positionals; end
  def required_keywords; end
  def required_positionals; end
  def rest_keywords; end
  def rest_keywords=(arg0); end
  def rest_positionals; end
  def rest_positionals=(arg0); end
  def return_type_annotation; end
  def return_type_annotation=(arg0); end
  def self.build(param_type_annotations, return_type_annotation, node); end
  def trailing_positionals; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Members::DefMember < RBS::AST::Ruby::Members::Base
  def annotations; end
  def initialize(buffer, name, node, method_type, leading_comment); end
  def leading_comment; end
  def location; end
  def method_type; end
  def name; end
  def name_location; end
  def node; end
  def overloading?; end
  def overloads; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Members::MixinMember < RBS::AST::Ruby::Members::Base
  def annotation; end
  def initialize(buffer, node, module_name, annotation); end
  def location; end
  def module_name; end
  def name_location; end
  def node; end
  def type_args; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Members::IncludeMember < RBS::AST::Ruby::Members::MixinMember
end
class RBS::AST::Ruby::Members::ExtendMember < RBS::AST::Ruby::Members::MixinMember
end
class RBS::AST::Ruby::Members::PrependMember < RBS::AST::Ruby::Members::MixinMember
end
class RBS::AST::Ruby::Members::AttributeMember < RBS::AST::Ruby::Members::Base
  def initialize(buffer, node, name_nodes, leading_comment, type_annotation); end
  def leading_comment; end
  def location; end
  def name_locations; end
  def name_nodes; end
  def names; end
  def node; end
  def type; end
  def type_annotation; end
  def type_fingerprint; end
end
class RBS::AST::Ruby::Members::AttrReaderMember < RBS::AST::Ruby::Members::AttributeMember
end
class RBS::AST::Ruby::Members::AttrWriterMember < RBS::AST::Ruby::Members::AttributeMember
end
class RBS::AST::Ruby::Members::AttrAccessorMember < RBS::AST::Ruby::Members::AttributeMember
end
class RBS::AST::Ruby::Members::InstanceVariableMember < RBS::AST::Ruby::Members::Base
  def annotation; end
  def initialize(buffer, annotation); end
  def location; end
  def name; end
  def type; end
  def type_fingerprint; end
end
module RBS::Source
end
class RBS::Source::RBS
  def buffer; end
  def declarations; end
  def directives; end
  def each_declaration_type_name(names, decl, &block); end
  def each_type_name(&block); end
  def initialize(buffer, directives, decls); end
end
class RBS::Source::Ruby
  def buffer; end
  def declarations; end
  def diagnostics; end
  def each_declaration_type_name(names, decl, &block); end
  def each_type_name(&block); end
  def initialize(buffer, prism, declarations, diagnostics); end
  def prism_result; end
end
class RBS::InlineParser
  def self.parse(buffer, prism); end
end
class RBS::InlineParser::Result
  def buffer; end
  def declarations; end
  def diagnostics; end
  def initialize(buffer, prism); end
  def prism_result; end
  def type_fingerprint; end
end
module RBS::InlineParser::Diagnostic
end
class RBS::InlineParser::Diagnostic::Base
  def initialize(location, message); end
  def location; end
  def message; end
end
class RBS::InlineParser::Diagnostic::NotImplementedYet < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::NonConstantClassName < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::NonConstantModuleName < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::NonConstantSuperClassName < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::TopLevelMethodDefinition < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::TopLevelAttributeDefinition < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::NonConstantConstantDeclaration < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::UnusedInlineAnnotation < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::AnnotationSyntaxError < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::MixinMultipleArguments < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::MixinNonConstantModule < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::AttributeNonSymbolName < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Diagnostic::ClassModuleAliasDeclarationMissingTypeName < RBS::InlineParser::Diagnostic::Base
end
class RBS::InlineParser::Parser < Prism::Visitor
  def buffer; end
  def comments; end
  def current_module!; end
  def current_module; end
  def diagnostics; end
  def initialize(result); end
  def insert_declaration(decl); end
  def module_nesting; end
  def parse_attribute_call(node); end
  def parse_constant_declaration(node); end
  def parse_mixin_call(node); end
  def parse_super_class(super_class_expr, inheritance_operator_loc); end
  def push_module_nesting(mod); end
  def report_unused_annotation(*annotations); end
  def report_unused_block(block); end
  def result; end
  def skip_node?(node); end
  def visit_call_node(node); end
  def visit_class_node(node); end
  def visit_constant_path_write_node(node); end
  def visit_constant_write_node(node); end
  def visit_def_node(node); end
  def visit_module_node(node); end
  include RBS::AST::Ruby::Helpers::ConstantHelper
  include RBS::AST::Ruby::Helpers::LocationHelper
end
class RBS::InlineParser::CommentAssociation
  def associated_blocks; end
  def blocks; end
  def each_enclosed_block(node); end
  def each_unassociated_block; end
  def end_line_map; end
  def initialize(blocks); end
  def leading_block!(node); end
  def leading_block(node); end
  def self.build(buffer, result); end
  def start_line_map; end
  def trailing_block!(node); end
  def trailing_block(node); end
end
class RBS::InlineParser::CommentAssociation::Reference
  def associate!; end
  def associated?; end
  def block; end
  def initialize(block, association); end
end
class RBS::Environment
  def absolute_type(resolver, map, type, context:); end
  def absolute_type_name(resolver, map, type_name, context:); end
  def add_source(source); end
  def append_context(context, decl); end
  def buffers; end
  def class_alias?(name); end
  def class_alias_decls; end
  def class_decl?(name); end
  def class_decls; end
  def class_entry(type_name, normalized: nil); end
  def constant_decl?(name); end
  def constant_decls; end
  def constant_entry(type_name, normalized: nil); end
  def constant_name?(name); end
  def declarations; end
  def each_rbs_source(&block); end
  def each_ruby_source(&block); end
  def global_decls; end
  def initialize; end
  def initialize_copy(other); end
  def insert_rbs_decl(decl, context:, namespace:); end
  def insert_ruby_decl(decl, context:, namespace:); end
  def inspect; end
  def interface_decls; end
  def interface_name?(name); end
  def module_alias?(name); end
  def module_class_entry(type_name, normalized: nil); end
  def module_decl?(name); end
  def module_entry(type_name, normalized: nil); end
  def module_name?(name); end
  def normalize_module_name!(name); end
  def normalize_module_name(name); end
  def normalize_module_name?(name); end
  def normalize_type_name!(name); end
  def normalize_type_name(name); end
  def normalize_type_name?(name); end
  def normalized_class_entry(type_name); end
  def normalized_module_class_entry(type_name); end
  def normalized_module_entry(type_name); end
  def normalized_type_name!(name); end
  def normalized_type_name?(type_name); end
  def resolve_declaration(resolver, map, decl, context:, prefix:); end
  def resolve_member(resolver, map, member, context:); end
  def resolve_method_type(resolver, map, type, context:); end
  def resolve_ruby_decl(resolver, decl, context:, prefix:); end
  def resolve_ruby_member(resolver, member, context:); end
  def resolve_signature(resolver, table, dirs, decls, only: nil); end
  def resolve_type_names(only: nil); end
  def resolve_type_params(resolver, map, params, context:); end
  def resolver_context(*nesting); end
  def self.from_loader(loader); end
  def sources; end
  def type_alias_decls; end
  def type_alias_name?(name); end
  def type_name?(name); end
  def unload(paths); end
  def validate_type_params; end
end
class RBS::Environment::SingleEntry
  def context; end
  def decl; end
  def initialize(name:, decl:, context:); end
  def name; end
end
class RBS::Environment::ModuleAliasEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::ClassAliasEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::InterfaceEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::TypeAliasEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::ConstantEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::GlobalEntry < RBS::Environment::SingleEntry
end
class RBS::Environment::UseMap
  def build_map(clause); end
  def initialize(table:); end
  def resolve(type_name); end
  def resolve?(type_name); end
  def use_dirs; end
end
class RBS::Environment::UseMap::Table
  def children; end
  def compute_children; end
  def initialize; end
  def known_types; end
end
class RBS::Environment::ClassEntry
  def <<(context_decl); end
  def context_decls; end
  def each_decl(&block); end
  def empty?; end
  def initialize(name); end
  def name; end
  def primary_decl; end
  def type_params; end
  def validate_type_params; end
end
class RBS::Environment::ModuleEntry
  def <<(context_decl); end
  def context_decls; end
  def each_decl(&block); end
  def empty?; end
  def initialize(name); end
  def name; end
  def primary_decl; end
  def self_types; end
  def type_params; end
  def validate_type_params; end
end
class RBS::EnvironmentLoader
  def add(path: nil, library: nil, version: nil, resolve_dependencies: nil); end
  def add_collection(lockfile); end
  def core_root; end
  def dirs; end
  def each_dir; end
  def each_signature; end
  def has_library?(library:, version:); end
  def initialize(core_root: nil, repository: nil); end
  def libs; end
  def load(env:); end
  def repository; end
  def resolve_dependencies(library:, version:); end
  def self.gem_sig_path(name, version); end
  include RBS::FileFinder
end
class RBS::EnvironmentLoader::UnknownLibraryError < StandardError
  def initialize(lib:); end
  def library; end
end
class Anonymous_Struct_1 < Struct
  def name; end
  def name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def version; end
  def version=(_); end
end
class RBS::EnvironmentLoader::Library < Anonymous_Struct_1
end
module RBS::BuiltinNames
end
class RBS::BuiltinNames::Name
  def initialize(name:); end
  def instance_type(*args); end
  def instance_type?(type); end
  def name; end
  def self.define(name, namespace: nil); end
  def singleton_type; end
  def singleton_type?(type); end
  def to_s; end
end
class RBS::Definition
  def ancestors; end
  def class?; end
  def class_type?; end
  def class_variables; end
  def each_type(&block); end
  def entry; end
  def initialize(type_name:, entry:, self_type:, ancestors:); end
  def instance_type?; end
  def instance_variables; end
  def interface?; end
  def interface_type?; end
  def map_method_type(&block); end
  def methods; end
  def module?; end
  def self_type; end
  def sub(s); end
  def type_name; end
  def type_params; end
  def type_params_decl; end
end
class RBS::Definition::Variable
  def declared_in; end
  def initialize(parent_variable:, type:, declared_in:, source:); end
  def parent_variable; end
  def source; end
  def sub(s); end
  def type; end
end
class RBS::Definition::Method
  def ==(other); end
  def accessibility; end
  def alias_member; end
  def alias_of; end
  def annotations; end
  def comments; end
  def defined_in; end
  def defs; end
  def eql?(other); end
  def extra_annotations; end
  def hash; end
  def implemented_in; end
  def initialize(super_method:, defs:, accessibility:, alias_of:, annotations: nil, alias_member: nil); end
  def map_method_type(&block); end
  def map_type(&block); end
  def map_type_bound(&block); end
  def members; end
  def method_types; end
  def private?; end
  def public?; end
  def sub(s); end
  def super_method; end
  def update(super_method: nil, defs: nil, accessibility: nil, alias_of: nil, annotations: nil, alias_member: nil); end
end
class RBS::Definition::Method::TypeDef
  def ==(other); end
  def annotations; end
  def comment; end
  def defined_in; end
  def each_annotation(&block); end
  def eql?(other); end
  def hash; end
  def implemented_in; end
  def initialize(type:, member:, defined_in:, implemented_in:, overload_annotations: nil); end
  def member; end
  def member_annotations; end
  def overload?; end
  def overload_annotations; end
  def type; end
  def update(type: nil, member: nil, defined_in: nil, implemented_in: nil); end
end
module RBS::Definition::Ancestor
end
class RBS::Definition::Ancestor::Instance
  def ==(other); end
  def args; end
  def eql?(other); end
  def hash; end
  def initialize(name:, args:, source:); end
  def name; end
  def source; end
end
class RBS::Definition::Ancestor::Singleton
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(name:); end
  def name; end
end
class RBS::Definition::InstanceAncestors
  def ancestors; end
  def apply(args, env:, location:); end
  def initialize(type_name:, params:, ancestors:); end
  def params; end
  def type_name; end
end
class RBS::Definition::SingletonAncestors
  def ancestors; end
  def initialize(type_name:, ancestors:); end
  def type_name; end
end
class RBS::DefinitionBuilder
  def ancestor_builder; end
  def build_instance(type_name); end
  def build_interface(type_name); end
  def build_singleton(type_name); end
  def build_singleton0(type_name); end
  def define_instance(definition, type_name, subst, define_class_vars:); end
  def define_interface(definition, type_name, subst); end
  def define_method(methods, definition, method, subst, self_type_methods, defined_in:, implemented_in: nil); end
  def ensure_namespace!(namespace, location:); end
  def env; end
  def expand_alias(type_name); end
  def expand_alias1(type_name); end
  def expand_alias2(type_name, args); end
  def import_methods(definition, module_name, module_methods, interfaces_methods, subst, self_type_methods); end
  def initialize(env:, ancestor_builder: nil, method_builder: nil); end
  def insert_variable(type_name, variables, name:, type:, source:); end
  def instance_cache; end
  def interface_cache; end
  def interface_methods(interface_ancestors); end
  def method_builder; end
  def singleton0_cache; end
  def singleton_cache; end
  def source_location(source, decl); end
  def special_accessibility(is_instance, method_name); end
  def tapp_subst(name, args); end
  def try_cache(type_name, cache:); end
  def update(env:, except:, ancestor_builder:); end
  def validate_params_with(type_params, result:); end
  def validate_type_name(name, location); end
  def validate_type_params(definition, ancestors:, methods:); end
  def validate_type_presence(type); end
  def validate_variable(var); end
end
class RBS::DefinitionBuilder::AncestorBuilder
  def env; end
  def fill_ancestor_source(ancestor, name:, source:, &block); end
  def initialize(env:); end
  def instance_ancestors(type_name, building_ancestors: nil); end
  def instance_ancestors_cache; end
  def interface_ancestors(type_name, building_ancestors: nil); end
  def interface_ancestors_cache; end
  def mixin_ancestors(entry, type_name, included_modules:, included_interfaces:, extended_modules:, prepended_modules:, extended_interfaces:); end
  def mixin_ancestors0(decl, type_name, align_params:, included_modules:, included_interfaces:, extended_modules:, prepended_modules:, extended_interfaces:); end
  def one_instance_ancestors(type_name); end
  def one_instance_ancestors_cache; end
  def one_interface_ancestors(type_name); end
  def one_interface_ancestors_cache; end
  def one_singleton_ancestors(type_name); end
  def one_singleton_ancestors_cache; end
  def singleton_ancestors(type_name, building_ancestors: nil); end
  def singleton_ancestors_cache; end
  def validate_super_class!(type_name, entry); end
end
class RBS::DefinitionBuilder::AncestorBuilder::OneAncestors
  def each_ancestor(&block); end
  def each_extended_interface(&block); end
  def each_extended_module(&block); end
  def each_included_interface(&block); end
  def each_included_module(&block); end
  def each_prepended_module(&block); end
  def each_self_type(&block); end
  def extended_interfaces; end
  def extended_modules; end
  def included_interfaces; end
  def included_modules; end
  def initialize(type_name:, params:, super_class:, self_types:, included_modules:, included_interfaces:, prepended_modules:, extended_modules:, extended_interfaces:); end
  def params; end
  def prepended_modules; end
  def self.class_instance(type_name:, params:, super_class:); end
  def self.interface(type_name:, params:); end
  def self.module_instance(type_name:, params:); end
  def self.singleton(type_name:, super_class:); end
  def self_types; end
  def super_class; end
  def type_name; end
end
class RBS::DefinitionBuilder::MethodBuilder
  def build_alias(methods, type, member:); end
  def build_attribute(methods, type, member:, accessibility:); end
  def build_instance(type_name); end
  def build_interface(type_name); end
  def build_method(methods, type, member:, accessibility:); end
  def build_ruby_attribute(methods, type, member:, accessibility:); end
  def build_singleton(type_name); end
  def each_rbs_member_with_accessibility(members, accessibility: nil); end
  def env; end
  def initialize(env:); end
  def instance_methods; end
  def interface_methods; end
  def singleton_methods; end
  def update(env:, except:); end
end
class RBS::DefinitionBuilder::MethodBuilder::Methods
  def each; end
  def initialize(type:); end
  def methods; end
  def type; end
  def validate!; end
end
class Anonymous_Struct_2 < Struct
  def accessibilities; end
  def accessibilities=(_); end
  def name; end
  def name=(_); end
  def originals; end
  def originals=(_); end
  def overloads; end
  def overloads=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type; end
  def type=(_); end
end
class RBS::DefinitionBuilder::MethodBuilder::Methods::Definition < Anonymous_Struct_2
  def accessibility; end
  def original; end
  def self.empty(name:, type:); end
end
class RBS::DefinitionBuilder::MethodBuilder::Methods::Sorter
  def initialize(methods); end
  def methods; end
  def tsort_each_child(defn); end
  def tsort_each_node(&block); end
  include TSort
end
class RBS::Diff
  def build_builder(env); end
  def build_env(path); end
  def build_methods(path); end
  def constant_to_s(constant); end
  def definition_method_to_s(key, kind, definition_method); end
  def each_diff(&block); end
  def each_diff_constants(before_constant_children, after_constant_children); end
  def each_diff_methods(kind, before_methods, after_methods); end
  def initialize(type_name:, library_options:, after_path: nil, before_path: nil, detail: nil); end
end
class RBS::VarianceCalculator
  def builder; end
  def env; end
  def function(type, result:, context:); end
  def in_inherit(name:, args:, variables:); end
  def in_method_type(method_type:, variables:); end
  def in_type_alias(name:); end
  def initialize(builder:); end
  def negate(variance); end
  def type(type, result:, context:); end
end
class RBS::VarianceCalculator::Result
  def compatible?(var, with_annotation:); end
  def contravariant(x); end
  def covariant(x); end
  def each(&block); end
  def include?(name); end
  def incompatible?(params); end
  def initialize(variables:); end
  def invariant(x); end
  def result; end
end
class RBS::Substitution
  def +(other); end
  def [](ty); end
  def add(from:, to:); end
  def apply(ty); end
  def empty?; end
  def initialize; end
  def instance_type; end
  def instance_type=(arg0); end
  def mapping; end
  def self.build(variables, types, instance_type: nil, &block); end
  def without(*vars); end
end
class RBS::Constant
  def ==(other); end
  def entry; end
  def eql?(other); end
  def hash; end
  def initialize(name:, type:, entry:); end
  def name; end
  def type; end
end
module RBS::Resolver
end
class RBS::Resolver::ConstantResolver
  def builder; end
  def child_constants_cache; end
  def children(module_name); end
  def constants(context); end
  def constants_from_ancestors(module_name, constants:); end
  def constants_from_context(context, constants:); end
  def constants_itself(context, constants:); end
  def context_constants_cache; end
  def initialize(builder:); end
  def load_child_constants(name); end
  def load_context_constants(context); end
  def resolve(name, context:); end
  def resolve_child(module_name, name); end
  def table; end
end
class RBS::Resolver::ConstantResolver::Table
  def children(name); end
  def children_table; end
  def constant(name); end
  def constant_of_constant(name, entry); end
  def constant_of_module(name, entry); end
  def constants_table; end
  def initialize(environment); end
  def toplevel; end
end
class RBS::Resolver::TypeNameResolver
  def aliased_name?(type_name); end
  def aliases; end
  def all_names; end
  def cache; end
  def has_type_name?(full_name); end
  def initialize(all_names, aliases); end
  def normalize_namespace(type_name, rhs, context, visited); end
  def resolve(type_name, context:); end
  def resolve_head_namespace(head, context); end
  def resolve_namespace(type_name, context:); end
  def resolve_namespace0(type_name, context, visited); end
  def resolve_type_name(type_name, context); end
  def self.build(env); end
  def try_cache(query); end
end
class RBS::AST::Comment
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(string:, location:); end
  def location; end
  def string; end
  def to_json(state = nil); end
end
class RBS::Writer
  def attribute(kind, attr); end
  def format_annotation(annotation); end
  def indent(size = nil); end
  def indentation; end
  def initialize(out:); end
  def method_name(name); end
  def name_and_args(name, args); end
  def name_and_params(name, params); end
  def out; end
  def prefix; end
  def preserve!(preserve: nil); end
  def preserve?; end
  def preserve_empty_line(prev, decl); end
  def put_lines(lines, leading_spaces:); end
  def puts(string = nil); end
  def write(contents); end
  def write_annotation(annotations); end
  def write_comment(comment); end
  def write_decl(decl); end
  def write_def(member); end
  def write_loc_source(located); end
  def write_member(member); end
  def write_use_directive(dir); end
end
module RBS::Prototype
end
module RBS::Prototype::Helpers
  def any_node?(node, nodes: nil, &block); end
  def args_from_node(args_node); end
  def block_from_body(node); end
  def each_child(node, &block); end
  def each_node(nodes); end
  def keyword_hash?(node); end
  def parse_comments(string, include_trailing:); end
  def symbol_literal_node?(node); end
  def untyped; end
end
class RBS::Prototype::RBI
  def call_node?(node, name:, receiver: nil, args: nil); end
  def const_to_name(node); end
  def current_module!; end
  def current_module; end
  def current_namespace; end
  def decls; end
  def each_arg(array, &block); end
  def each_child(node); end
  def initialize; end
  def join_comments(nodes, comments); end
  def last_sig; end
  def method_type(args_node, type_node, variables:, overloads:); end
  def modules; end
  def nested_name(name); end
  def node_to_hash(node); end
  def parse(string); end
  def parse_params(args_node, args, method_type, variables:, overloads:); end
  def pop_sig; end
  def proc_type?(type_node); end
  def process(node, comments:, outer: nil); end
  def push_class(name, super_class, comment:); end
  def push_module(name, comment:); end
  def push_sig(node); end
  def type_of(type_node, variables:); end
  def type_of0(type_node, variables:); end
  include RBS::Prototype::Helpers
end
class RBS::Prototype::RB
  def block_type(node); end
  def body_type(node); end
  def const_to_name!(node, context: nil); end
  def const_to_name(node, context:); end
  def current_accessibility(decls, index = nil); end
  def decls; end
  def find_def_index_by_name(decls, name); end
  def function_return_type_from_body(node); end
  def function_type_from_body(node, def_name); end
  def if_unless_type(node); end
  def initialize; end
  def is_accessibility?(decl); end
  def literal_to_symbol(node); end
  def literal_to_type(node); end
  def node_type(node, default: nil); end
  def param_type(node, default: nil); end
  def parse(string); end
  def private; end
  def process(node, decls:, comments:, context:); end
  def process_children(node, decls:, comments:, context:); end
  def public; end
  def range_element_type(types); end
  def remove_unnecessary_accessibility_methods!(decls); end
  def sort_members!(decls); end
  def source_decls; end
  def toplevel_members; end
  def types_to_union_type(types); end
  include RBS::Prototype::Helpers
end
class Anonymous_Struct_3 < Struct
  def in_def; end
  def in_def=(_); end
  def module_function; end
  def module_function=(_); end
  def namespace; end
  def namespace=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def singleton; end
  def singleton=(_); end
end
class RBS::Prototype::RB::Context < Anonymous_Struct_3
  def attribute_kind; end
  def enter_namespace(namespace); end
  def method_kind; end
  def self.initial(namespace: nil); end
  def update(module_function: nil, singleton: nil, in_def: nil); end
end
class RBS::Prototype::Runtime
  def block_from_ast_of(method); end
  def builder; end
  def can_alias?(mod, method); end
  def decls; end
  def each_mixined_module(type_name, mod); end
  def each_mixined_module_one(type_name, mod); end
  def ensure_outer_module_declarations(mod); end
  def env; end
  def generate_class(mod); end
  def generate_constants(mod, decls); end
  def generate_methods(mod, module_name, members); end
  def generate_mixin(mod, decl, type_name, type_name_absolute); end
  def generate_module(mod); end
  def generate_super_class(mod); end
  def initialize(patterns:, env:, merge:, todo: nil, owners_included: nil); end
  def merge; end
  def merge_rbs(module_name, members, instance: nil, singleton: nil); end
  def method_type(method); end
  def outline; end
  def outline=(arg0); end
  def owners_included; end
  def parse(file); end
  def patterns; end
  def target?(const); end
  def target_method?(mod, instance: nil, singleton: nil); end
  def todo; end
  def todo_object; end
  def type_args(type_name); end
  def type_params(mod); end
  include RBS::Prototype::Helpers
  include RBS::Prototype::Runtime::Helpers
end
module RBS::Prototype::Runtime::Helpers
  def const_name!(const); end
  def const_name(const); end
  def only_name(mod); end
  def to_type_name(name, full_name: nil); end
  def untyped; end
end
class RBS::Prototype::Runtime::ValueObjectBase
  def build_decl; end
  def build_member_accessors(ast_members_class); end
  def build_s_members; end
  def initialize(target_class); end
  include RBS::Prototype::Runtime::Helpers
end
class RBS::Prototype::Runtime::StructGenerator < RBS::Prototype::Runtime::ValueObjectBase
  def add_decl_members(decl); end
  def build_overload_for_keyword_arguments; end
  def build_overload_for_positional_arguments; end
  def build_s_keyword_init_p; end
  def build_s_new; end
  def build_super_class; end
  def self.generatable?(target); end
end
class RBS::Prototype::Runtime::DataGenerator < RBS::Prototype::Runtime::ValueObjectBase
  def add_decl_members(decl); end
  def build_s_new; end
  def build_super_class; end
  def self.generatable?(target); end
end
module RBS::Prototype::Runtime::Reflection
  def self.constants_of(mod, inherit = nil); end
  def self.object_class(value); end
end
class RBS::Prototype::Runtime::Todo
  def initialize(builder:); end
  def mixin_decls(type_name); end
  def skip_constant?(module_name:, name:); end
  def skip_instance_method?(module_name:, method:, accessibility:); end
  def skip_mixin?(type_name:, module_name:, mixin_class:); end
  def skip_singleton_method?(module_name:, method:, accessibility:); end
end
class RBS::Prototype::NodeUsage
  def calculate(node, conditional:); end
  def conditional_nodes; end
  def each_conditional_node(&block); end
  def initialize(node); end
  include RBS::Prototype::Helpers
end
class RBS::EnvironmentWalker
  def builder; end
  def each_type_name(type, &block); end
  def each_type_node(type, &block); end
  def env; end
  def initialize(env:); end
  def only_ancestors!(only = nil); end
  def only_ancestors?; end
  def tsort_each_child(node, &block); end
  def tsort_each_node(&block); end
  include TSort
end
class RBS::EnvironmentWalker::InstanceNode < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type_name; end
  def type_name=(_); end
end
class RBS::EnvironmentWalker::SingletonNode < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type_name; end
  def type_name=(_); end
end
class RBS::EnvironmentWalker::TypeNameNode < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type_name; end
  def type_name=(_); end
end
class RBS::Vendorer
  def clean!; end
  def copy!; end
  def ensure_dir; end
  def initialize(vendor_dir:, loader:); end
  def loader; end
  def vendor_dir; end
end
class RBS::Validator
  def absolute_type(type, context:, &block); end
  def definition_builder; end
  def env; end
  def initialize(env:, resolver: nil); end
  def resolver; end
  def type_alias_dependency; end
  def type_alias_regularity; end
  def validate_class_alias(entry:); end
  def validate_method_definition(method_def, type_name:); end
  def validate_type(type, context:); end
  def validate_type_alias(entry:); end
  def validate_type_params(params, type_name:, location:, method_name: nil); end
  def validate_variable(var); end
end
class RBS::Factory
  def type_name(string); end
end
class RBS::Repository
  def add(dir); end
  def dirs; end
  def gems; end
  def initialize(no_stdlib: nil); end
  def lookup(gem, version); end
  def lookup_path(gem, version); end
  def self.default; end
  def self.find_best_version(version, candidates); end
end
class RBS::Repository::GemRBS
  def empty?; end
  def find_best_version(version); end
  def initialize(name:); end
  def latest_version; end
  def load!; end
  def name; end
  def oldest_version; end
  def paths; end
  def version_names; end
  def versions; end
end
class RBS::Repository::VersionPath < Struct
  def gem; end
  def gem=(_); end
  def path; end
  def path=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def version; end
  def version=(_); end
end
class RBS::Subtractor
  def absolute_typename(name, context:); end
  def access_modifier?(decl); end
  def call(minuend = nil, context: nil); end
  def cvar_exist?(owner, name); end
  def each_member(owner, &block); end
  def filter_members(decl, context:); end
  def filter_redundant_access_modifiers(decls); end
  def initialize(minuend, subtrahend); end
  def ivar_exist?(owner, name, kind); end
  def member_exist?(owner, member, context:); end
  def method_exist?(owner, method_name, kind); end
  def mixin_exist?(owner, mixin, context:); end
  def typename_candidates(name, context:); end
  def update_decl(decl, members:); end
end
class RBS::AncestorGraph
  def ancestor_builder; end
  def build; end
  def build_ancestors(node, ancestors); end
  def children; end
  def each_ancestor(node, yielded: nil, &block); end
  def each_child(node, &block); end
  def each_descendant(node, yielded: nil, &block); end
  def each_parent(node, &block); end
  def env; end
  def initialize(env:, ancestor_builder: nil); end
  def parents; end
  def register(parent:, child:); end
end
class RBS::AncestorGraph::InstanceNode < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type_name; end
  def type_name=(_); end
end
class RBS::AncestorGraph::SingletonNode < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type_name; end
  def type_name=(_); end
end
class RBS::Locator
  def buffer; end
  def decls; end
  def dirs; end
  def find(line:, column:); end
  def find2(line:, column:); end
  def find_in_decl(pos, decl:, array:); end
  def find_in_directive(pos, dir, array); end
  def find_in_loc(pos, location:, array:); end
  def find_in_member(pos, member:, array:); end
  def find_in_method_type(pos, method_type:, array:); end
  def find_in_type(pos, type:, array:); end
  def find_in_type_param(pos, type_param:, array:); end
  def initialize(buffer:, dirs:, decls:); end
  def test_loc(pos, location:); end
end
class RBS::TypeAliasDependency
  def build_dependencies; end
  def circular_definition?(alias_name); end
  def dependencies; end
  def dependencies_of(name); end
  def dependency(start, vertex, nested = nil); end
  def direct_dependencies; end
  def direct_dependencies_of(name); end
  def direct_dependency(type, result = nil); end
  def env; end
  def initialize(env:); end
  def transitive_closure; end
end
class RBS::TypeAliasRegularity
  def build_alias_type(name); end
  def builder; end
  def compatible_args?(args1, args2); end
  def diagnostics; end
  def each_alias_type(type, &block); end
  def each_mutual_alias_defs(&block); end
  def env; end
  def initialize(env:); end
  def nonregular?(type_name); end
  def self.validate(env:); end
  def validate; end
  def validate_alias_type(alias_type, names, types); end
end
class RBS::TypeAliasRegularity::Diagnostic
  def initialize(type_name:, nonregular_type:); end
  def nonregular_type; end
  def type_name; end
end
class RBS::CLI
end
class RBS::CLI::ColoredIO
  def are_colors_disabled?; end
  def are_colors_supported?; end
  def can_display_colors?; end
  def initialize(stdout:); end
  def puts(*, **, &); end
  def puts_green(string); end
  def puts_red(string); end
  def stdout; end
end
module RBS::Collection
end
module RBS::Collection::Sources
  def self.from_config_entry(source_entry, base_directory:); end
end
module RBS::Collection::Sources::Base
  def dependencies_of(name, version); end
end
class RBS::Collection::Sources::Git
  def _install(dest:, name:, version:); end
  def commit_hash?; end
  def cp_r(src, dest); end
  def format_config_entry(name, version); end
  def gem_repo_dir; end
  def gems_versions; end
  def git(*cmd, **opt); end
  def git?(*cmd, **opt); end
  def git_dir; end
  def has?(name, version); end
  def initialize(name:, revision:, remote:, repo_dir:); end
  def install(dest:, name:, version:, stdout:); end
  def load_metadata(dir:); end
  def manifest_of(name, version); end
  def metadata_content(name:, version:); end
  def name; end
  def need_to_fetch?(revision); end
  def remote; end
  def repo_dir; end
  def resolved_revision; end
  def revision; end
  def setup!; end
  def sh!(*cmd, **opt); end
  def to_lockfile; end
  def versions(name); end
  def write_metadata(dir:, name:, version:); end
  include RBS::Collection::Sources::Base
end
class RBS::Collection::Sources::Git::CommandError < StandardError
end
class RBS::Collection::Sources::Stdlib
  def has?(name, version); end
  def install(dest:, name:, version:, stdout:); end
  def lookup(name, version); end
  def manifest_of(name, version); end
  def self.allocate; end
  def self.new(*, **); end
  def to_lockfile; end
  def versions(name); end
  extend Singleton::SingletonClassMethods
  include RBS::Collection::Sources::Base
  include Singleton
end
class RBS::Collection::Sources::Rubygems
  def gem_sig_path(name, version); end
  def has?(name, version); end
  def install(dest:, name:, version:, stdout:); end
  def manifest_of(name, version); end
  def self.allocate; end
  def self.new(*, **); end
  def to_lockfile; end
  def versions(name); end
  extend Singleton::SingletonClassMethods
  include RBS::Collection::Sources::Base
  include Singleton
end
class RBS::Collection::Sources::Local
  def _install(src, dst); end
  def full_path; end
  def has?(name, version); end
  def initialize(path:, base_directory:); end
  def install(dest:, name:, version:, stdout:); end
  def manifest_of(name, version); end
  def path; end
  def to_lockfile; end
  def versions(name); end
  include RBS::Collection::Sources::Base
end
class RBS::Collection::Config
  def config_path; end
  def data; end
  def gem(gem_name); end
  def gems; end
  def initialize(data, config_path:); end
  def repo_path; end
  def repo_path_data; end
  def self.find_config_path; end
  def self.from_path(path); end
  def self.generate_lockfile(config_path:, definition:, with_lockfile: nil); end
  def self.to_lockfile_path(config_path); end
  def sources; end
end
class RBS::Collection::Config::CollectionNotAvailable < StandardError
  def initialize; end
end
class RBS::Collection::Config::Lockfile
  def check_rbs_availability!; end
  def fullpath; end
  def gemfile_lock_fullpath; end
  def gemfile_lock_path; end
  def gems; end
  def initialize(lockfile_path:, path:, gemfile_lock_path:); end
  def library_data(lib); end
  def lockfile_dir; end
  def lockfile_path; end
  def path; end
  def self.from_lockfile(lockfile_path:, data:); end
  def sources; end
  def to_lockfile; end
end
class RBS::Collection::Config::LockfileGenerator
  def assign_gem(name:, version:, skip: nil); end
  def assign_stdlib(name:, from_gem: nil); end
  def config; end
  def definition; end
  def existing_lockfile; end
  def find_best_version(version:, versions:); end
  def find_source(name:); end
  def gem_entries; end
  def gem_hash; end
  def generate; end
  def initialize(config:, definition:, with_lockfile:); end
  def lockfile; end
  def self.generate(config:, definition:, with_lockfile: nil); end
  def validate_gemfile_lock_path!(lock:, gemfile_lock_path:); end
end
class RBS::Collection::Config::LockfileGenerator::GemfileLockMismatchError < StandardError
  def initialize(expected:, actual:); end
  def message; end
end
class RBS::Collection::Installer
  def initialize(lockfile_path:, stdout: nil); end
  def install_from_lockfile; end
  def lockfile; end
  def stdout; end
end
class RBS::Collection::Cleaner
  def clean; end
  def initialize(lockfile_path:); end
  def lock; end
  def needed?(gem_name, version); end
end
class RBS::Location
  def ==(other); end
  def [](arg0); end
  def _add_optional_child(arg0, arg1, arg2); end
  def _add_optional_no_child(arg0); end
  def _add_required_child(arg0, arg1, arg2); end
  def _end_pos; end
  def _optional_keys; end
  def _required_keys; end
  def _start_pos; end
  def add_optional_child(name, range); end
  def add_required_child(name, range); end
  def aref(arg0); end
  def buffer; end
  def each_optional_key(&block); end
  def each_required_key(&block); end
  def end_column; end
  def end_line; end
  def end_loc; end
  def end_pos; end
  def initialize(arg0, arg1, arg2); end
  def initialize_copy(arg0); end
  def inspect; end
  def key?(name); end
  def local_location; end
  def local_source; end
  def name; end
  def optional_key?(name); end
  def range; end
  def required_key?(name); end
  def self.new(buffer_ = nil, start_pos_ = nil, end_pos_ = nil, buffer: nil, start_pos: nil, end_pos: nil); end
  def self.to_string(location, default: nil); end
  def source; end
  def start_column; end
  def start_line; end
  def start_loc; end
  def start_pos; end
  def to_json(state = nil); end
  def to_s; end
end
class RBS::Parser
  def self._lex(arg0, arg1); end
  def self._parse_inline_leading_annotation(arg0, arg1, arg2, arg3); end
  def self._parse_inline_trailing_annotation(arg0, arg1, arg2, arg3); end
  def self._parse_method_type(arg0, arg1, arg2, arg3, arg4); end
  def self._parse_signature(arg0, arg1, arg2); end
  def self._parse_type(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7); end
  def self._parse_type_params(arg0, arg1, arg2, arg3); end
  def self.buffer(source); end
  def self.byte_range(char_range, content); end
  def self.lex(source); end
  def self.magic_comment(buf); end
  def self.parse_inline_leading_annotation(source, range, variables: nil); end
  def self.parse_inline_trailing_annotation(source, range, variables: nil); end
  def self.parse_method_type(source, range: nil, byte_range: nil, variables: nil, require_eof: nil); end
  def self.parse_signature(source); end
  def self.parse_type(source, range: nil, byte_range: nil, variables: nil, require_eof: nil, void_allowed: nil, self_allowed: nil, classish_allowed: nil); end
  def self.parse_type_params(source, module_type_params: nil); end
end
class RBS::Parser::LexResult
  def buffer; end
  def initialize(buffer:, value:); end
  def value; end
end
class RBS::Parser::Token
  def comment?; end
  def initialize(type:, location:); end
  def location; end
  def type; end
  def value; end
end
