# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tapioca/all/tapioca.rbi
#
# tapioca-0.18.0

module Tapioca
end
class Tapioca::Error < StandardError
end
