# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tsort/all/tsort.rbi
#
# tsort-0.2.0

module TSort
  def each_strongly_connected_component(&block); end
  def each_strongly_connected_component_from(node, id_map = nil, stack = nil, &block); end
  def self.each_strongly_connected_component(each_node, each_child); end
  def self.each_strongly_connected_component_from(node, each_child, id_map = nil, stack = nil); end
  def self.strongly_connected_components(each_node, each_child); end
  def self.tsort(each_node, each_child); end
  def self.tsort_each(each_node, each_child); end
  def strongly_connected_components; end
  def tsort; end
  def tsort_each(&block); end
  def tsort_each_child(node); end
  def tsort_each_node; end
end
class TSort::Cyclic < StandardError
end
