# Auto-generated by scripts/generate-tests.py — DO NOT EDIT
"""Tests for WowAceSerializer."""

import math
import re
import pytest
from wow_serialization.ace_serializer import WowAce, WowAceDeserializer, WowAceSerializer


@pytest.fixture
def ser():
    return WowAceSerializer().serialize


@pytest.fixture
def de():
    return WowAceDeserializer().deserialize


@pytest.fixture
def ace():
    return WowAce()


def describe_AceSerializer():

    def describe_a_string_escaping():
        def it_A1_nul_0x00(ser, de):
            """A1: NUL (0x00) → ~@"""
            wire = ser(chr(0))
            assert '~@' in wire

        def it_A2a_control_0x01_a(ser, de):
            """A2a: control 0x01 → ~A"""
            wire = ser(chr(1))
            assert '~A' in wire

        def it_A2b_control_0x0a_lf_j(ser, de):
            """A2b: control 0x0A (LF) → ~J"""
            wire = ser(chr(10))
            assert '~J' in wire

        def it_A2c_control_0x1d(ser, de):
            """A2c: control 0x1D → ~]"""
            wire = ser(chr(29))
            assert '~]' in wire

        def it_A3_byte_30_0x1e_z_special_case(ser, de):
            """A3: byte 30 (0x1E) → ~z (special case)"""
            wire = ser(chr(30))
            assert '~z' in wire

        def it_A4_byte_31_0x1f(ser, de):
            """A4: byte 31 (0x1F) → ~_"""
            wire = ser(chr(31))
            assert '~_' in wire

        def it_A5_space_0x20(ser, de):
            """A5: space (0x20) → ~`"""
            wire = ser(' ')
            assert '~`' in wire

        def it_A6_caret_0x5e(ser, de):
            """A6: caret ^ (0x5E) → ~}"""
            wire = ser('^')
            assert '~}' in wire

        def it_A7_tilde_0x7e(ser, de):
            """A7: tilde ~ (0x7E) → ~|"""
            wire = ser('~')
            assert '~|' in wire

        def it_A8_del_0x7f(ser, de):
            """A8: DEL (0x7F) → ~{"""
            wire = ser(chr(127))
            assert '~{' in wire

        def it_A9_single_pass_no_double_escaping(ser, de):
            """A9: single-pass — no double-escaping"""
            wire = ser(''.join(chr(b) for b in [94, 126, 127]))
            assert '~}' in wire
            assert '~|' in wire
            assert '~{' in wire

        def it_A10_printable_ascii_passes_through(ser, de):
            """A10: printable ASCII passes through"""
            wire = ser('hello')
            assert '^Shello' in wire


    def describe_b_string_unescaping():
        def it_B11_nul_0x00(ser, de):
            """B11: ~@ → NUL (0x00)"""
            result = de('^1^S~@^^')
            assert result == chr(0)

        def it_B12a_a_chr_1(ser, de):
            """B12a: ~A → chr(1)"""
            result = de('^1^S~A^^')
            assert result == chr(1)

        def it_B12b_j_chr_10(ser, de):
            """B12b: ~J → chr(10)"""
            result = de('^1^S~J^^')
            assert result == chr(10)

        def it_B13_z_byte_30_0x1e(ser, de):
            """B13: ~z → byte 30 (0x1E)"""
            result = de('^1^S~z^^')
            assert result == chr(30)

        def it_B14_del_0x7f(ser, de):
            """B14: ~{ → DEL (0x7F)"""
            result = de('^1^S~{^^')
            assert result == chr(127)

        def it_B15_tilde(ser, de):
            """B15: ~| → tilde (~)"""
            result = de('^1^S~|^^')
            assert result == '~'

        def it_B16_caret(ser, de):
            """B16: ~} → caret (^)"""
            result = de('^1^S~}^^')
            assert result == '^'

        def it_B17_round_trip_all_escapable_bytes(ser, de):
            """B17: round-trip all escapable bytes"""
            input_val = ''.join(chr(b) for b in [0, 1, 10, 29, 30, 31, 32, 94, 127, 126])
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val


    def describe_c_number_serialization():
        def it_C18_positive_integer_n42(ser, de):
            """C18: positive integer → ^N42"""
            wire = ser(42)
            assert '^N42' in wire

        def it_C19_negative_integer_n_42(ser, de):
            """C19: negative integer → ^N-42"""
            wire = ser(-42)
            assert '^N-42' in wire

        def it_C20_zero_n0(ser, de):
            """C20: zero → ^N0"""
            wire = ser(0)
            assert '^N0' in wire

        def it_C21_large_integer(ser, de):
            """C21: large integer"""
            wire = ser(1000000)
            assert '^N1000000' in wire

        def it_C22_non_integer_float_uses_n_tonumber_tostring_check(ser, de):
            """C22: non-integer float uses ^N (tonumber/tostring check)"""
            wire = ser(3.14)
            assert '^N3.14' in wire

        def it_C23_3_14_exact_wire_format(ser, de):
            """C23: 3.14 exact wire format"""
            wire = ser(3.14)
            assert wire == '^1^N3.14^^'

        def it_C24a_0_1_wire_format(ser, de):
            """C24a: 0.1 wire format"""
            wire = ser(0.1)
            assert wire == '^1^N0.1^^'

        def it_C24b_99_99_wire_format(ser, de):
            """C24b: -99.99 wire format"""
            wire = ser(-99.99)
            assert wire == '^1^N-99.99^^'

        def it_C24c_1e_10_wire_format(ser, de):
            """C24c: 1e-10 wire format"""
            wire = ser(1e-10)
            assert wire == '^1^N1e-10^^'

        def it_C25_positive_infinity_n1_inf_or_ninf(ser, de):
            """C25: positive infinity → ^N1.#INF or ^Ninf"""
            wire = ser(math.inf)
            candidates = ["1.#INF", "inf"]
            assert any(c in wire for c in candidates), f"Expected wire to contain one of {candidates}, got: {wire}"

        def it_C26_negative_infinity_n_1_inf_or_n_inf(ser, de):
            """C26: negative infinity → ^N-1.#INF or ^N-inf"""
            wire = ser(-math.inf)
            candidates = ["-1.#INF", "-inf"]
            assert any(c in wire for c in candidates), f"Expected wire to contain one of {candidates}, got: {wire}"


    def describe_d_number_deserialization():
        def it_D27_n42_42(ser, de):
            """D27: ^N42 → 42"""
            result = de('^1^N42^^')
            assert result == 42

        def it_D28_n_42_42(ser, de):
            """D28: ^N-42 → -42"""
            result = de('^1^N-42^^')
            assert result == -42

        def it_D29_n3_14_3_14(ser, de):
            """D29: ^N3.14 → 3.14"""
            result = de('^1^N3.14^^')
            assert abs(result - 3.14) < 1e-10

        def it_D30_n1_inf_infinity(ser, de):
            """D30: ^N1.#INF → Infinity"""
            result = de('^1^N1.#INF^^')
            assert result == math.inf

        def it_D31_n_1_inf_infinity(ser, de):
            """D31: ^N-1.#INF → -Infinity"""
            result = de('^1^N-1.#INF^^')
            assert result == -math.inf

        def it_D32_ninf_infinity_alternate(ser, de):
            """D32: ^Ninf → Infinity (alternate)"""
            result = de('^1^Ninf^^')
            assert result == math.inf

        def it_D33_n_inf_infinity_alternate(ser, de):
            """D33: ^N-inf → -Infinity (alternate)"""
            result = de('^1^N-inf^^')
            assert result == -math.inf

        def it_D34_f_m_f_e_correct_float(ser, de):
            """D34: ^F<m>^f<e> → correct float"""
            result = de('^1^F4503599627370496^f-53^^')
            assert abs(result - 0.5) < 1e-10


    def describe_e_float_round_trips():
        def it_E35_round_trip_3_14(ser, de):
            """E35: round-trip 3.14"""
            input_val = 3.14
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E36_round_trip_0_1(ser, de):
            """E36: round-trip 0.1"""
            input_val = 0.1
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E37_round_trip_123_456(ser, de):
            """E37: round-trip 123.456"""
            input_val = 123.456
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E38_round_trip_99_99(ser, de):
            """E38: round-trip -99.99"""
            input_val = -99.99
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E39_round_trip_1e_10(ser, de):
            """E39: round-trip 1e-10"""
            input_val = 1e-10
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E40_round_trip_very_small_float_min_normal(ser, de):
            """E40: round-trip very small float (min normal)"""
            input_val = 2.2250738585072014e-308
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_E41_round_trip_very_large_float(ser, de):
            """E41: round-trip very large float"""
            input_val = 1.7976931348623157e+308
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10


    def describe_f_boolean():
        def it_F42_true_b(ser, de):
            """F42: true → ^B"""
            wire = ser(True)
            assert '^B' in wire

        def it_F43_false_b(ser, de):
            """F43: false → ^b"""
            wire = ser(False)
            assert '^b' in wire

        def it_F44_b_true(ser, de):
            """F44: ^B → true"""
            result = de('^1^B^^')
            assert result == True

        def it_F45_b_false(ser, de):
            """F45: ^b → false"""
            result = de('^1^b^^')
            assert result == False


    def describe_g_nil():
        def it_G46_nil_z(ser, de):
            """G46: nil → ^Z"""
            wire = ser(None)
            assert '^Z' in wire

        def it_G47_z_nil(ser, de):
            """G47: ^Z → nil"""
            result = de('^1^Z^^')
            assert result == None


    def describe_h_table_serialization():
        def it_H48_empty_table_t_t(ser, de):
            """H48: empty table → ^T^t"""
            wire = ser({  })
            assert '^T^t' in wire

        def it_H49_single_string_key_value_pair(ser, de):
            """H49: single string key-value pair"""
            wire = ser({ 'a': 1 })
            assert '^T' in wire
            assert '^Sa' in wire
            assert '^N1' in wire
            assert '^t' in wire

        def it_H50_multiple_key_value_pairs(ser, de):
            """H50: multiple key-value pairs"""
            wire = ser({ 'a': 1, 'b': 2 })
            assert '^T' in wire
            assert '^t' in wire

        def it_H51_nested_table(ser, de):
            """H51: nested table"""
            wire = ser({ 'inner': { 'x': 1 } })
            count = wire.count('^T')
            assert count == 2

        def it_H52_array_1_based_integer_keys(ser, de):
            """H52: array → 1-based integer keys"""
            wire = ser(['a', 'b', 'c'])
            assert '^N1' in wire
            assert '^Sa' in wire
            assert '^N2' in wire
            assert '^Sb' in wire
            assert '^N3' in wire
            assert '^Sc' in wire

        def it_H53_mixed_table_integer_string_keys(ser, de):
            """H53: mixed table (integer + string keys)"""
            wire = ser({ 1: 'a', 'x': 'b' })
            assert '^T' in wire
            assert '^t' in wire


    def describe_i_array_detection():
        def it_I54_sequential_1_based_keys_array(ser, de):
            """I54: sequential 1-based keys → array"""
            input_val = { 1: 'a', 2: 'b', 3: 'c' }
            wire = ser(input_val)
            result = de(wire)
            assert result[1] == 'a'
            assert result[2] == 'b'
            assert result[3] == 'c'

        def it_I55_non_sequential_keys_object(ser, de):
            """I55: non-sequential keys → object"""
            input_val = { 1: 'a', 3: 'c' }
            wire = ser(input_val)
            result = de(wire)
            assert result[1] == 'a'
            assert result[3] == 'c'

        def it_I56_string_keys_object(ser, de):
            """I56: string keys → object"""
            input_val = { 'x': 1, 'y': 2 }
            wire = ser(input_val)
            result = de(wire)
            assert result['x'] == 1
            assert result['y'] == 2

        def it_I57_single_element(ser, de):
            """I57: single element"""
            input_val = { 1: 'only' }
            wire = ser(input_val)
            result = de(wire)
            assert result[1] == 'only'

        def it_I58_empty_table_empty(ser, de):
            """I58: empty table → empty"""
            input_val = {  }
            wire = ser(input_val)
            result = de(wire)
            assert result == {}


    def describe_j_framing():
        def it_J59_output_starts_with_1_and_ends_with(ser, de):
            """J59: output starts with ^1 and ends with ^^"""
            wire = ser('hello')
            assert wire.startswith('^1')
            assert wire.endswith('^^')

        def it_J62_control_chars_stripped_from_input(ser, de):
            """J62: control chars stripped from input"""
            result = de("^1\x09\x0a^Shello\x0d\x0a^^")
            assert result == 'hello'


    def describe_k_error_handling():
        def it_J60_missing_1_prefix_error(ser, de):
            """J60: missing ^1 prefix → error"""
            with pytest.raises(Exception):
                de('^Shello^^')

        def it_K64_empty_string_error(ser, de):
            """K64: empty string → error"""
            with pytest.raises(Exception):
                de('')

        def it_K65_missing_terminator_error(ser, de):
            """K65: missing ^^ terminator → error"""
            with pytest.raises(Exception):
                de('^1^Shello')


    def describe_l_round_trips():
        def it_L66_plain_ascii_string(ser, de):
            """L66: plain ASCII string"""
            input_val = 'hello world test'
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_L67_all_special_chars(ser, de):
            """L67: all special chars"""
            input_val = ''.join(chr(b) for b in [0, 1, 30, 31, 32, 94, 126, 127])
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_L68_integer(ser, de):
            """L68: integer"""
            input_val = 12345
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_L69_float(ser, de):
            """L69: float"""
            input_val = 3.14
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_L70_boolean(ser, de):
            """L70: boolean"""
            input_1 = True
            wire_1 = ser(input_1)
            result_1 = de(wire_1)
            assert result_1 == input_1
            input_2 = False
            wire_2 = ser(input_2)
            result_2 = de(wire_2)
            assert result_2 == input_2

        def it_L71_nil(ser, de):
            """L71: nil"""
            input_val = None
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_L72_nested_table_array(ser, de):
            """L72: nested table/array"""
            input_val = { 1: 1, 2: { 1: 2, 2: 3 } }
            wire = ser(input_val)
            result = de(wire)
            assert result[1] == 1

        def it_L73_mixed_type_table(ser, de):
            """L73: mixed-type table"""
            input_val = { 'n': 42, 'f': 3.14, 'b': True, 's': 'hello' }
            wire = ser(input_val)
            result = de(wire)
            assert result['n'] == 42
            assert result['f'] == 3.14
            assert result['b'] == True
            assert result['s'] == 'hello'


    def describe_l2_fixture_wire_format_tests():
        def it_L74_simple_array_of_two_strings_exact_wire(ser, de):
            """L74: simple array of two strings — exact wire"""
            wire = ser({ 1: 'a', 2: 'b' })
            assert wire == '^1^T^N1^Sa^N2^Sb^t^^'

        def it_L75_simple_array_of_two_strings_deserialize(ser, de):
            """L75: simple array of two strings — deserialize"""
            result = de('^1^T^N1^Sa^N2^Sb^t^^')
            assert result == { 1: 'a', 2: 'b' }

        def it_L76_array_of_three_mixed_values_exact_wire(ser, de):
            """L76: array of three mixed values — exact wire"""
            wire = ser({ 1: 'hello', 2: 42, 3: True })
            assert wire == '^1^T^N1^Shello^N2^N42^N3^B^t^^'

        def it_L77_array_of_three_mixed_values_deserialize(ser, de):
            """L77: array of three mixed values — deserialize"""
            result = de('^1^T^N1^Shello^N2^N42^N3^B^t^^')
            assert result == { 1: 'hello', 2: 42, 3: True }

        def it_L78_nested_array_exact_wire(ser, de):
            """L78: nested array — exact wire"""
            wire = ser({ 1: { 1: 'a', 2: 'b' }, 2: 'c' })
            assert wire == '^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^'

        def it_L79_nested_array_deserialize(ser, de):
            """L79: nested array — deserialize"""
            result = de('^1^T^N1^T^N1^Sa^N2^Sb^t^N2^Sc^t^^')
            assert result == { 1: { 1: 'a', 2: 'b' }, 2: 'c' }

        def it_L80_array_with_null_values_exact_wire(ser, de):
            """L80: array with null values — exact wire"""
            wire = ser({ 1: None, 2: None, 3: None, 4: 'test' })
            assert wire == '^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^'

        def it_L81_array_with_null_values_deserialize(ser, de):
            """L81: array with null values — deserialize"""
            result = de('^1^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^^')
            assert result == { 1: None, 2: None, 3: None, 4: 'test' }

        def it_L82_nested_structure_from_protocol_spec_deserialize_only(ser, de):
            """L82: nested structure from protocol spec — deserialize only"""
            result = de('^1^T^Shello^Sworld^Stest^N123^Snested^T^N1^Z^N2^Z^N3^Z^N4^Stest^t^t^^')
            assert result == { 'hello': 'world', 'test': 123, 'nested': { 1: None, 2: None, 3: None, 4: 'test' } }

        def it_L83_mixed_table_string_and_integer_keys_deserialize_only(ser, de):
            """L83: mixed table string and integer keys — deserialize only"""
            result = de('^1^T^Shello^Sworld^Sn^N42^t^^')
            assert result == { 'hello': 'world', 'n': 42 }


    def describe_m_float_wire_format_consistency():
        def it_M84_3_14_uses_n_path_not_f(ser, de):
            """M84: 3.14 uses ^N path (not ^F)"""
            wire = ser(3.14)
            assert '^N3.14' in wire

        def it_M85_very_small_float_1e_10_uses_n_path(ser, de):
            """M85: very small float 1e-10 uses ^N path"""
            wire = ser(1e-10)
            assert '^N' in wire

        def it_M86_0_5_uses_n_path(ser, de):
            """M86: 0.5 uses ^N path"""
            wire = ser(0.5)
            assert '^N0.5' in wire

        def it_M87_extreme_float_2_2250738585072014e_308_round_trips_correctly(ser, de):
            """M87: extreme float 2.2250738585072014e-308 round-trips correctly"""
            input_val = 2.2250738585072014e-308
            wire = ser(input_val)
            result = de(wire)
            assert abs(result - input_val) < 1e-10

        def it_M88_extreme_float_2_2250738585072014e_308_uses_f_path_14g_loses_precision(ser, de):
            """M88: extreme float 2.2250738585072014e-308 uses ^F path (%.14g loses precision)"""
            wire = ser(2.2250738585072014e-308)
            assert '^F' in wire


    def describe_n_escape_edge_cases():
        def it_N88a_invalid_escape_ord_62_would_produce_negative_byte_is_rejected(ser, de):
            """N88a: invalid escape ~> (ord 62, would produce negative byte) is rejected"""
            with pytest.raises(Exception):
                de('^1^S~>^^')

        def it_N88b_invalid_escape_ord_35_would_produce_negative_byte_is_rejected(ser, de):
            """N88b: invalid escape ~# (ord 35, would produce negative byte) is rejected"""
            with pytest.raises(Exception):
                de('^1^S~#^^')

        def it_N88c_all_control_bytes_0x01_0x1d_round_trip_correctly(ser, de):
            """N88c: all control bytes 0x01-0x1D round-trip correctly"""
            input_val = ''.join(chr(i) for i in range(1, 30))
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_N89_all_escapable_bytes_combined_in_one_string_round_trip(ser, de):
            """N89: all escapable bytes combined in one string round-trip"""
            input_val = ''.join(chr(b) for b in [0, 1, 10, 29, 30, 31, 32, 94, 126, 127])
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

        def it_N90_high_bytes_0x80_0xff_pass_through_unescaped(ser, de):
            """N90: high bytes 0x80-0xFF pass through unescaped"""
            input_val = ''.join(chr(i) for i in range(128, 256))
            wire = ser(input_val)
            result = de(wire)
            assert result == input_val

