# Auto-generated by scripts/generate-tests.py — DO NOT EDIT
"""Tests for Pipeline encode/decode."""

import pytest
from wow_serialization.pipeline import Pipeline, ExportResult


def roundtrip(addon, version, data, metadata=None):
    enc = Pipeline.encode(ExportResult(addon=addon, version=version, data=data, metadata=metadata))
    return Pipeline.decode(enc)


def describe_Pipeline():

    def describe_a_prefix_encoding():
        def it_A1_wa_v1_uses_prefix():
            """A1: WA v1 uses ! prefix"""
            enc = Pipeline.encode(ExportResult('weakauras', 1, 'x', None))
            assert enc.startswith('!')
            assert not enc.startswith('!WA:2!')
            assert not enc.startswith('!E1!')

        def it_A2_elvui_uses_e1_prefix():
            """A2: ElvUI uses !E1! prefix"""
            enc = Pipeline.encode(ExportResult('elvui', 1, 'x', None))
            assert enc.startswith('!E1!')

        def it_A3_legacy_v0_uses_no_prefix():
            """A3: legacy (v0) uses no prefix"""
            enc = Pipeline.encode(ExportResult('weakauras', 0, 'x', None))
            assert not enc.startswith('!')

        def it_A4_wa_v2_uses_wa_2_prefix():
            """A4: WA v2 uses !WA:2! prefix"""
            enc = Pipeline.encode(ExportResult('weakauras', 2, { 'a': 1 }, None))
            assert enc.startswith('!WA:2!')


    def describe_b_prefix_detection():
        def it_B1_e1_detected_as_elvui_v1():
            """B1: !E1! detected as elvui v1"""
            dec = roundtrip('elvui', 1, { 'a': 1 })
            assert dec.addon == 'elvui'
            assert dec.version == 1

        def it_B2_detected_as_weakauras_v1():
            """B2: ! detected as weakauras v1"""
            dec = roundtrip('weakauras', 1, { 'a': 1 })
            assert dec.addon == 'weakauras'
            assert dec.version == 1

        def it_B3_no_prefix_detected_as_weakauras_v0_legacy():
            """B3: no prefix detected as weakauras v0 (legacy)"""
            dec = roundtrip('weakauras', 0, { 'a': 1 })
            assert dec.addon == 'weakauras'
            assert dec.version == 0

        def it_B4_wa_2_detected_as_weakauras_v2():
            """B4: !WA:2! detected as weakauras v2"""
            dec = roundtrip('weakauras', 2, { 'a': 1 })
            assert dec.addon == 'weakauras'
            assert dec.version == 2


    def describe_c_exportresult_structure():
        def it_C1_decode_returns_all_four_fields():
            """C1: decode returns all four fields"""
            dec = roundtrip('weakauras', 1, { 'x': 1 })
            assert hasattr(dec, 'addon')
            assert hasattr(dec, 'version')
            assert hasattr(dec, 'data')
            assert hasattr(dec, 'metadata')


    def describe_d_round_trips():
        def it_D1_wa_v1_string():
            """D1: WA v1 string"""
            dec = roundtrip('weakauras', 1, 'hello')
            assert dec.data == 'hello'
            assert dec.addon == 'weakauras'
            assert dec.version == 1
            assert dec.metadata is None

        def it_D2_wa_v1_table():
            """D2: WA v1 table"""
            dec = roundtrip('weakauras', 1, { 'key': 'value', 'num': 42 })
            assert dec.data['key'] == 'value'
            assert dec.data['num'] == 42

        def it_D3_wa_v1_array():
            """D3: WA v1 array"""
            data = { 1: '1', 2: '2', 3: '3' }
            assert roundtrip('weakauras', 1, data).data == data

        def it_D4_wa_v1_nested_table():
            """D4: WA v1 nested table"""
            dec = roundtrip('weakauras', 1, { 'outer': { 'inner': 99 }, 'list': { 1: 1, 2: 2 } })
            assert dec.data['outer']['inner'] == 99
            assert dec.data['list'] == { 1: 1, 2: 2 }

        def it_D5_legacy_v0_round_trip():
            """D5: legacy v0 round-trip"""
            dec = roundtrip('weakauras', 0, { 'flag': True, 'n': -5 })
            assert dec.data['flag'] == True
            assert dec.data['n'] == -5

        def it_D6_wa_v2_round_trip():
            """D6: WA v2 round-trip"""
            dec = roundtrip('weakauras', 2, { 'key': 'v2data', 'num': 7 })
            assert dec.data['key'] == 'v2data'
            assert dec.data['num'] == 7


    def describe_e_elvui_metadata():
        def it_E1_round_trip_preserves_metadata_profiletype_and_profilekey():
            """E1: round-trip preserves metadata profileType and profileKey"""
            metadata = { 'profile_type': 'profile', 'profile_key': 'Default' }
            dec = roundtrip('elvui', 1, { 'setting': 1 }, metadata)
            assert dec.addon == 'elvui'
            assert dec.metadata['profile_type'] == 'profile'
            assert dec.metadata['profile_key'] == 'Default'
            assert dec.data['setting'] == 1

        def it_E2_elvui_without_metadata_gives_null_metadata_after_decode():
            """E2: ElvUI without metadata gives null metadata after decode"""
            dec = roundtrip('elvui', 1, { 'a': 1 }, None)
            assert dec.metadata is None

