# Auto-generated by testing/generate-tests.py — DO NOT EDIT
"""Tests for LibSerialize serialize/deserialize."""

import math
import pytest
from azerite.lib_serialize import deserialize, serialize


def roundtrip(obj):
    return deserialize(serialize(obj))


def describe_LibSerialize():

    def describe_a_nil():
        def it_A01_serialize_nil_produces_non_empty_string():
            """A01: serialize nil produces non-empty string"""
            wire = serialize(None)
            assert len(wire) > 0

        def it_A02_nil_round_trips_to_nil():
            """A02: nil round-trips to nil"""
            result = roundtrip(None)
            assert result is None

        def it_A03_deserialize_of_serialized_nil_returns_ok_true_and_nil_value():
            """A03: Deserialize of serialized nil returns ok=true and nil value"""
            result = roundtrip(None)
            assert result is None


    def describe_b_integer_encoding_small_embedded():
        def it_B01_zero_round_trips_correctly_embedded_1_byte():
            """B01: zero round-trips correctly (embedded 1-byte)"""
            input_val = 0
            assert roundtrip(input_val) == input_val

        def it_B02_positive_small_int_1_round_trips_correctly():
            """B02: positive small int 1 round-trips correctly"""
            input_val = 1
            assert roundtrip(input_val) == input_val

        def it_B03_small_int_127_round_trips_correctly_embedded_1_byte_max():
            """B03: small int 127 round-trips correctly (embedded 1-byte max)"""
            input_val = 127
            assert roundtrip(input_val) == input_val

        def it_B04_small_negative_1_round_trips_correctly_embedded_2_byte():
            """B04: small negative -1 round-trips correctly (embedded 2-byte)"""
            input_val = -1
            assert roundtrip(input_val) == input_val

        def it_B05_small_negative_4095_round_trips_correctly_embedded_2_byte_near_max():
            """B05: small negative -4095 round-trips correctly (embedded 2-byte near max)"""
            input_val = -4095
            assert roundtrip(input_val) == input_val

        def it_B06_positive_128_round_trips_correctly_embedded_2_byte():
            """B06: positive 128 round-trips correctly (embedded 2-byte)"""
            input_val = 128
            assert roundtrip(input_val) == input_val

        def it_B07_positive_4095_round_trips_correctly_embedded_2_byte_max():
            """B07: positive 4095 round-trips correctly (embedded 2-byte max)"""
            input_val = 4095
            assert roundtrip(input_val) == input_val


    def describe_c_integer_encoding_multi_byte():
        def it_C01_16_bit_positive_4096_round_trips_correctly():
            """C01: 16-bit positive 4096 round-trips correctly"""
            input_val = 4096
            assert roundtrip(input_val) == input_val

        def it_C02_16_bit_positive_max_65535_round_trips_correctly():
            """C02: 16-bit positive max 65535 round-trips correctly"""
            input_val = 65535
            assert roundtrip(input_val) == input_val

        def it_C03_16_bit_negative_4096_round_trips_correctly():
            """C03: 16-bit negative -4096 round-trips correctly"""
            input_val = -4096
            assert roundtrip(input_val) == input_val

        def it_C04_24_bit_positive_65536_round_trips_correctly():
            """C04: 24-bit positive 65536 round-trips correctly"""
            input_val = 65536
            assert roundtrip(input_val) == input_val

        def it_C05_24_bit_positive_max_16777215_round_trips_correctly():
            """C05: 24-bit positive max 16777215 round-trips correctly"""
            input_val = 16777215
            assert roundtrip(input_val) == input_val

        def it_C06_32_bit_positive_16777216_round_trips_correctly():
            """C06: 32-bit positive 16777216 round-trips correctly"""
            input_val = 16777216
            assert roundtrip(input_val) == input_val

        def it_C07_32_bit_positive_max_4294967295_round_trips_correctly():
            """C07: 32-bit positive max 4294967295 round-trips correctly"""
            input_val = 4294967295
            assert roundtrip(input_val) == input_val

        def it_C08_64_bit_positive_4294967296_round_trips_correctly():
            """C08: 64-bit positive 4294967296 round-trips correctly"""
            input_val = 4294967296
            assert roundtrip(input_val) == input_val

        def it_C09_large_negative_65536_round_trips_correctly():
            """C09: large negative -65536 round-trips correctly"""
            input_val = -65536
            assert roundtrip(input_val) == input_val


    def describe_d_float_encoding():
        def it_D01_float_3_14_round_trips_correctly():
            """D01: float 3.14 round-trips correctly"""
            input_val = 3.14
            assert abs(roundtrip(input_val) - input_val) < 1e-10

        def it_D02_float_0_1_round_trips_correctly():
            """D02: float 0.1 round-trips correctly"""
            input_val = 0.1
            assert abs(roundtrip(input_val) - input_val) < 1e-10

        def it_D03_float_99_99_round_trips_correctly():
            """D03: float -99.99 round-trips correctly"""
            input_val = -99.99
            assert abs(roundtrip(input_val) - input_val) < 1e-10

        def it_D04_float_1e_10_round_trips_correctly():
            """D04: float 1e-10 round-trips correctly"""
            input_val = 1e-10
            assert abs(roundtrip(input_val) - input_val) < 1e-10

        def it_D05_float_0_5_round_trips_correctly():
            """D05: float 0.5 round-trips correctly"""
            input_val = 0.5
            assert abs(roundtrip(input_val) - input_val) < 1e-10

        def it_D06_positive_infinity_round_trips_correctly():
            """D06: positive infinity round-trips correctly"""
            input_val = math.inf
            assert roundtrip(input_val) == input_val

        def it_D07_negative_infinity_round_trips_correctly():
            """D07: negative infinity round-trips correctly"""
            input_val = -math.inf
            assert roundtrip(input_val) == input_val

        def it_D08_max_exact_double_integer_2_53_9007199254740992_round_trips_correctly():
            """D08: max exact double integer 2^53 (9007199254740992) round-trips correctly"""
            input_val = 9007199254740992
            assert roundtrip(input_val) == input_val

        def it_D09_float_1_5_round_trips_correctly_floatstr_short_path():
            """D09: float 1.5 round-trips correctly (floatstr short path)"""
            input_val = 1.5
            assert abs(roundtrip(input_val) - input_val) < 1e-10


    def describe_e_boolean():
        def it_E01_true_round_trips_correctly():
            """E01: true round-trips correctly"""
            input_val = True
            assert roundtrip(input_val) == input_val

        def it_E02_false_round_trips_correctly():
            """E02: false round-trips correctly"""
            input_val = False
            assert roundtrip(input_val) == input_val

        def it_E03_true_and_false_produce_distinct_serializations():
            """E03: true and false produce distinct serializations"""
            wires = []
            wires.append(serialize(True))
            wires.append(serialize(False))
            assert len(set(wires)) == len(wires), "Expected all serializations to be distinct"


    def describe_f_string_encoding_embedded():
        def it_F01_empty_string_round_trips_correctly():
            """F01: empty string round-trips correctly"""
            input_val = ''
            assert roundtrip(input_val) == input_val

        def it_F02_single_char_string_round_trips_correctly():
            """F02: single char string round-trips correctly"""
            input_val = 'a'
            assert roundtrip(input_val) == input_val

        def it_F03_two_char_string_round_trips_correctly():
            """F03: two char string round-trips correctly"""
            input_val = 'ab'
            assert roundtrip(input_val) == input_val

        def it_F04_short_5_char_string_round_trips_correctly():
            """F04: short 5-char string round-trips correctly"""
            input_val = 'hello'
            assert roundtrip(input_val) == input_val

        def it_F05_15_char_string_max_embedded_round_trips_correctly():
            """F05: 15-char string (max embedded) round-trips correctly"""
            input_val = '123456789012345'
            assert roundtrip(input_val) == input_val


    def describe_g_string_encoding_length_prefixed():
        def it_G01_16_char_string_str_8_path_round_trips_correctly():
            """G01: 16-char string (STR_8 path) round-trips correctly"""
            input_val = '1234567890123456'
            assert roundtrip(input_val) == input_val

        def it_G02_long_100_char_string_round_trips_correctly():
            """G02: long 100-char string round-trips correctly"""
            input_val = 'x'.encode() * 100
            assert roundtrip(input_val) == input_val

        def it_G03_string_with_all_256_byte_values_round_trips_correctly():
            """G03: string with all 256 byte values round-trips correctly"""
            input_val = bytes(range(0, 256))
            assert roundtrip(input_val) == input_val


    def describe_h_string_refs():
        def it_H01_repeated_string_in_table_round_trips_with_correct_values():
            """H01: repeated string in table round-trips with correct values"""
            input_val = { 'a': 'hello world', 'b': 'hello world' }
            result = roundtrip(input_val)
            assert result['a'] == 'hello world'
            assert result['b'] == 'hello world'

        def it_H02_string_repeated_5_times_in_array_round_trips_with_correct_values():
            """H02: string repeated 5 times in array round-trips with correct values"""
            input_val = { 1: 'shared_key', 2: 'shared_key', 3: 'shared_key', 4: 'shared_key', 5: 'shared_key' }
            result = roundtrip(input_val)
            assert result[1] == 'shared_key'
            assert result[2] == 'shared_key'
            assert result[3] == 'shared_key'
            assert result[4] == 'shared_key'
            assert result[5] == 'shared_key'

        def it_H03_short_strings_2_bytes_not_tracked_as_refs_but_still_round_trip_correctly():
            """H03: short strings (<=2 bytes) not tracked as refs but still round-trip correctly"""
            input_val = { 'a': 'x', 'b': 'x', 'c': 'xy', 'd': 'xy' }
            result = roundtrip(input_val)
            assert result['a'] == 'x'
            assert result['b'] == 'x'
            assert result['c'] == 'xy'
            assert result['d'] == 'xy'


    def describe_i_empty_and_small_tables():
        def it_I01_empty_table_round_trips_to_empty_table():
            """I01: empty table round-trips to empty table"""
            result = roundtrip({  })
            assert result == {} or result == []

        def it_I02_table_with_1_key_value_pair_round_trips_correctly():
            """I02: table with 1 key-value pair round-trips correctly"""
            input_val = { 'a': 1 }
            result = roundtrip(input_val)
            assert result['a'] == 1

        def it_I03_table_with_15_entries_embedded_max_round_trips_all_values_correctly():
            """I03: table with 15 entries (embedded max) round-trips all values correctly"""
            input_val = { 'k1': 1, 'k2': 2, 'k3': 3, 'k4': 4, 'k5': 5, 'k6': 6, 'k7': 7, 'k8': 8, 'k9': 9, 'k10': 10, 'k11': 11, 'k12': 12, 'k13': 13, 'k14': 14, 'k15': 15 }
            result = roundtrip(input_val)
            assert result['k1'] == 1
            assert result['k2'] == 2
            assert result['k3'] == 3
            assert result['k4'] == 4
            assert result['k5'] == 5
            assert result['k6'] == 6
            assert result['k7'] == 7
            assert result['k8'] == 8
            assert result['k9'] == 9
            assert result['k10'] == 10
            assert result['k11'] == 11
            assert result['k12'] == 12
            assert result['k13'] == 13
            assert result['k14'] == 14
            assert result['k15'] == 15


    def describe_j_arrays():
        def it_J01_single_element_array_round_trips_correctly():
            """J01: single-element array round-trips correctly"""
            input_val = { 1: 'only' }
            result = roundtrip(input_val)
            assert result[1] == 'only'

        def it_J02_simple_array_a_b_c_round_trips_correctly():
            """J02: simple array [a, b, c] round-trips correctly"""
            input_val = { 1: 'a', 2: 'b', 3: 'c' }
            result = roundtrip(input_val)
            assert result[1] == 'a'
            assert result[2] == 'b'
            assert result[3] == 'c'

        def it_J03_integer_array_10_20_30_40_50_round_trips_correctly():
            """J03: integer array [10, 20, 30, 40, 50] round-trips correctly"""
            input_val = { 1: 10, 2: 20, 3: 30, 4: 40, 5: 50 }
            result = roundtrip(input_val)
            assert result[1] == 10
            assert result[2] == 20
            assert result[3] == 30
            assert result[4] == 40
            assert result[5] == 50

        def it_J04_mixed_type_array_str_42_true_false_round_trips_correctly():
            """J04: mixed-type array [str, 42, true, false] round-trips correctly"""
            input_val = { 1: 'str', 2: 42, 3: True, 4: False }
            result = roundtrip(input_val)
            assert result[1] == 'str'
            assert result[2] == 42
            assert result[3] == True
            assert result[4] == False

        def it_J05_16_element_array_array_8_path_round_trips_correctly():
            """J05: 16-element array (ARRAY_8 path) round-trips correctly"""
            input_val = { 1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60, 7: 70, 8: 80, 9: 90, 10: 100, 11: 110, 12: 120, 13: 130, 14: 140, 15: 150, 16: 160 }
            result = roundtrip(input_val)
            assert result[1] == 10
            assert result[2] == 20
            assert result[3] == 30
            assert result[4] == 40
            assert result[5] == 50
            assert result[6] == 60
            assert result[7] == 70
            assert result[8] == 80
            assert result[9] == 90
            assert result[10] == 100
            assert result[11] == 110
            assert result[12] == 120
            assert result[13] == 130
            assert result[14] == 140
            assert result[15] == 150
            assert result[16] == 160


    def describe_k_mixed_tables():
        def it_K01_mixed_table_with_integer_and_string_keys_round_trips_correctly():
            """K01: mixed table with integer and string keys round-trips correctly"""
            input_val = { 1: 'first', 2: 'second', 'x': 'extra' }
            result = roundtrip(input_val)
            assert result[1] == 'first'
            assert result[2] == 'second'
            assert result['x'] == 'extra'

        def it_K02_mixed_table_with_various_value_types_round_trips_correctly():
            """K02: mixed table with various value types round-trips correctly"""
            input_val = { 1: 'arr1', 2: 'arr2', 'key': 99, 'flag': True }
            result = roundtrip(input_val)
            assert result[1] == 'arr1'
            assert result[2] == 'arr2'
            assert result['key'] == 99
            assert result['flag'] == True

        def it_K03_nested_table_round_trips_inner_values_correctly():
            """K03: nested table round-trips inner values correctly"""
            input_val = { 'inner': { 'x': 1, 'y': 2 } }
            result = roundtrip(input_val)
            assert result['inner'] == { 'x': 1, 'y': 2 }

        def it_K04_deeply_nested_table_round_trips_leaf_value_correctly():
            """K04: deeply nested table round-trips leaf value correctly"""
            input_val = { 'a': { 'b': { 'c': { 'd': 42 } } } }
            result = roundtrip(input_val)
            assert result['a'] == { 'b': { 'c': { 'd': 42 } } }


    def describe_l_table_refs():
        def it_L01_shared_sub_table_round_trips_with_correct_values_in_both_references():
            """L01: shared sub-table round-trips with correct values in both references"""
            input_val = { 'a': { 'value': 99 }, 'b': { 'value': 99 } }
            result = roundtrip(input_val)
            assert result['a'] == { 'value': 99 }
            assert result['b'] == { 'value': 99 }

        def it_L02_deserialized_shared_table_refs_point_to_the_same_object_mutation_test():
            """L02: deserialized shared table refs point to the same object (mutation test)"""
            # Shared table reference identity — Lua-specific
            assert True


    def describe_m_variadic_serialize_deserialize():
        def it_M01_serialize_multiple_values_1_hello_true_deserializes_all_correctly():
            """M01: serialize multiple values (1, hello, true) deserializes all correctly"""
            assert roundtrip(1) == 1
            assert roundtrip('hello') == 'hello'
            assert roundtrip(True) == True

        def it_M02_serialize_values_with_nil_in_middle_1_nil_3_deserializes_all_correctly():
            """M02: serialize values with nil in middle (1, nil, 3) deserializes all correctly"""
            assert roundtrip(1) == 1
            assert roundtrip(None) is None
            assert roundtrip(3) == 3


    def describe_n_error_handling():
        def it_N01_deserializing_corrupt_data_returns_a_boolean_result_ok_field():
            """N01: deserializing corrupt data returns a boolean result (ok field)"""
            wire = "not valid data \xff".encode('latin-1') if isinstance("not valid data \xff", str) else "not valid data \xff"
            try:
                result = deserialize(wire)
                # Some implementations return error as value
            except Exception:
                pass  # Expected

        def it_N02_isserializabletype_returns_true_for_nil_number_string_boolean_table():
            """N02: IsSerializableType returns true for nil, number, string, boolean, table"""
            # IsSerializableType not exposed in Python — skip
            assert True

        def it_N03_isserializabletype_returns_false_for_functions():
            """N03: IsSerializableType returns false for functions"""
            # IsSerializableType not exposed in Python — skip
            assert True


    def describe_o_round_trips_comprehensive():
        def it_O01_complex_nested_structure_round_trips_all_fields_correctly():
            """O01: complex nested structure round-trips all fields correctly"""
            input_val = { 'name': 'test', 'values': { 1: 1, 2: 2, 3: 3 }, 'meta': { 'active': True, 'count': 0 } }
            result = roundtrip(input_val)
            assert result['name'] == 'test'
            assert result['meta'] == { 'active': True, 'count': 0 }

        def it_O02_table_with_boolean_keys_round_trips_correctly():
            """O02: table with boolean keys round-trips correctly"""
            input_val = { 1: 'yes', 0: 'no' }
            result = roundtrip(input_val)
            assert result[1] == 'yes'
            assert result[0] == 'no'

        def it_O03_table_with_float_key_1_5_round_trips_correctly():
            """O03: table with float key 1.5 round-trips correctly"""
            input_val = { 1.5: 'fractional' }
            result = roundtrip(input_val)
            assert result[1.5] == 'fractional'

        def it_O04_string_with_embedded_null_bytes_round_trips_correctly():
            """O04: string with embedded null bytes round-trips correctly"""
            input_val = bytes([97, 0, 98, 0, 99])
            assert roundtrip(input_val) == input_val

        def it_O05_all_256_byte_values_in_a_string_round_trip_correctly():
            """O05: all 256 byte values in a string round-trip correctly"""
            input_val = bytes(range(0, 256))
            assert roundtrip(input_val) == input_val


    def describe_p_mixed_table_table_ref_integrity():
        def it_P01_shared_mixed_table_ref_both_keys_see_array_and_hash_portions():
            """P01: shared mixed table ref — both keys see array and hash portions"""
            wire = bytes.fromhex('012612621e1529326b65793276616c1261e802')
            result = deserialize(wire)
            assert result['a'] == { 1: 10, 2: 20, 'key': 'val' }
            assert result['b'] == { 1: 10, 2: 20, 'key': 'val' }

        def it_P02_mixed_table_then_plain_table_then_refs_to_both_ref_indices_correct():
            """P02: mixed table then plain table then refs to both — ref indices correct"""
            wire = bytes.fromhex('0146527265665f6d1ec9840c426e616d65526d69786564527265665f7026127905127803126de8021270e803')
            result = deserialize(wire)
            assert result['m'] == { 1: 100, 2: 200, 'name': 'mixed' }
            assert result['p'] == { 'x': 1, 'y': 2 }
            assert result['ref_m'] == { 1: 100, 2: 200, 'name': 'mixed' }
            assert result['ref_p'] == { 'x': 1, 'y': 2 }

        def it_P03_mixed_table_followed_by_second_table_roundtrip_preserves_all():
            """P03: mixed table followed by second table — roundtrip preserves all"""
            input_val = { 'first': { 1: 'x', 2: 'y', 'name': 'mixed1' }, 'second': { 1: 'a', 2: 'b', 'name': 'mixed2' } }
            result = roundtrip(input_val)
            assert result['first'] == { 1: 'x', 2: 'y', 'name': 'mixed1' }
            assert result['second'] == { 1: 'a', 2: 'b', 'name': 'mixed2' }


    def describe_q_numeric_key_type_preservation():
        def it_Q01_lua_serialized_array_a_b_c_deserializes_with_correct_values():
            """Q01: Lua-serialized array [a,b,c] deserializes with correct values"""
            wire = bytes.fromhex('013a126112621263')
            result = deserialize(wire)
            assert isinstance(result, dict)
            assert result[1] == 'a'
            assert result[2] == 'b'
            assert result[3] == 'c'

        def it_Q02_lua_serialized_mixed_int_string_keys_deserialize_correctly():
            """Q02: Lua-serialized mixed int+string keys deserialize correctly"""
            wire = bytes.fromhex('011e526669727374627365636f6e64426e616d654274657374')
            result = deserialize(wire)
            assert result[1] == 'first'
            assert result[2] == 'second'
            assert result['name'] == 'test'

        def it_Q03_lua_serialized_table_has_integer_keys_not_string_keys():
            """Q03: Lua-serialized table has integer keys not string keys"""
            wire = bytes.fromhex('011e526669727374627365636f6e64426e616d654274657374')
            result = deserialize(wire)
            assert 1 in result, "Expected integer key 1, not string"
            assert isinstance(list(k for k in result if k == 1)[0], int), "Key 1 should be int type"
            assert 2 in result, "Expected integer key 2, not string"
            assert isinstance(list(k for k in result if k == 2)[0], int), "Key 2 should be int type"
            assert 'name' in result, "Expected string key 'name'"

        def it_Q04_mixed_integer_and_string_keys_roundtrip_with_correct_key_types():
            """Q04: mixed integer and string keys roundtrip with correct key types"""
            input_val = { 1: 'first', 2: 'second', 'name': 'test' }
            result = roundtrip(input_val)
            assert 1 in result, "Expected integer key 1 after roundtrip"
            assert isinstance(list(k for k in result if k == 1)[0], int), "Key 1 should be int after roundtrip"
            assert 2 in result, "Expected integer key 2 after roundtrip"
            assert isinstance(list(k for k in result if k == 2)[0], int), "Key 2 should be int after roundtrip"
            assert 'name' in result, "Expected string key 'name' after roundtrip"

        def it_Q05_integer_keyed_table_serializes_as_array_not_table_with_string_keys():
            """Q05: integer-keyed table serializes as array not table-with-string-keys"""
            wire = serialize({ 1: 'a', 2: 'b' })
            assert wire.hex() == '012a12611262'


    def describe_r_variadic_round_trip_verification():
        def it_R01_single_value_variadic_round_trip():
            """R01: single value variadic round-trip"""
            assert roundtrip(42) == 42

        def it_R02_four_mixed_type_values_variadic_round_trip():
            """R02: four mixed-type values variadic round-trip"""
            assert roundtrip('hello') == 'hello'
            assert roundtrip(42) == 42
            assert roundtrip(True) == True
            assert roundtrip(3.14) == 3.14

        def it_R03_variadic_with_nil_at_start_and_end():
            """R03: variadic with nil at start and end"""
            assert roundtrip(None) is None
            assert roundtrip('hello') == 'hello'
            assert roundtrip(None) is None


    def describe_s_nil_wire_format():
        def it_S01_lua_serialized_nil_is_exactly_01_00():
            """S01: Lua-serialized nil is exactly 01 00"""
            wire = serialize(None)
            assert wire.hex() == '0100'

