# Auto-generated by scripts/generate-tests.py — DO NOT EDIT
"""Tests for WowCbor wrapper."""

import cbor2
import pytest
from wow_serialization.wow_cbor import WowCbor


def describe_WowCbor():

    def describe_a_round_trip():
        def it_A1_string_value():
            """A1: string value"""
            input_val = 'hello world'
            assert WowCbor.decode(WowCbor.encode(input_val)) == input_val

        def it_A2_integer_value():
            """A2: integer value"""
            input_val = 42
            assert WowCbor.decode(WowCbor.encode(input_val)) == input_val

        def it_A3_boolean_true():
            """A3: boolean true"""
            input_val = True
            assert WowCbor.decode(WowCbor.encode(input_val)) is True

        def it_A4_null_value():
            """A4: null value"""
            input_val = None
            assert WowCbor.decode(WowCbor.encode(input_val)) is None

        def it_A5_string_keyed_object():
            """A5: string-keyed object"""
            input_val = { 'key': 'value', 'num': 7 }
            result = WowCbor.decode(WowCbor.encode(input_val))
            assert result['key'] == 'value'
            assert result['num'] == 7

        def it_A6_array():
            """A6: array"""
            input_val = ['a', 'b', 'c']
            assert WowCbor.decode(WowCbor.encode(input_val)) == input_val


    def describe_b_byte_string_conversion():
        def it_B1_byte_string_is_converted_to_utf_8_string():
            """B1: byte string is converted to UTF-8 string"""
            result = WowCbor.decode(cbor2.dumps(b'hello'))
            assert result == 'hello'
            assert isinstance(result, str)

        def it_B2_nested_byte_string_in_object_is_converted():
            """B2: nested byte string in object is converted"""
            result = WowCbor.decode(cbor2.dumps({'key': b'world'}))
            assert result['key'] == 'world'
            assert isinstance(result['key'], str)

        def it_B3_byte_strings_in_list_are_converted():
            """B3: byte strings in list are converted"""
            result = WowCbor.decode(cbor2.dumps([b'a', b'b']))
            assert result == ['a', 'b']


    def describe_c_array_detection():
        def it_C1_sequential_1_based_int_keys_converted_to_array():
            """C1: sequential 1-based int keys converted to array"""
            result = WowCbor.decode(cbor2.dumps({ 1: 'a', 2: 'b', 3: 'c' }))
            assert result == ['a', 'b', 'c']

        def it_C2_non_sequential_int_keys_stay_as_object():
            """C2: non-sequential int keys stay as object"""
            result = WowCbor.decode(cbor2.dumps({ 1: 'a', 3: 'c' }))
            assert isinstance(result, dict)

        def it_C3_string_keyed_object_stays_as_object():
            """C3: string-keyed object stays as object"""
            result = WowCbor.decode(WowCbor.encode({ 'a': 1, 'b': 2 }))
            assert isinstance(result, dict)
            assert result['a'] == 1
            assert result['b'] == 2


    def describe_d_plater_v2_prefix():
        def it_D1_encodes_with_plater_2_prefix():
            """D1: encodes with !PLATER:2! prefix"""
            from wow_serialization.pipeline import Pipeline, ExportResult
            enc = Pipeline.encode(ExportResult(addon='plater', version=2, data={ 'x': 1 }, metadata=None))
            assert enc.startswith('!PLATER:2!')

        def it_D2_decodes_plater_2_to_plater_v2():
            """D2: decodes !PLATER:2! to plater v2"""
            from wow_serialization.pipeline import Pipeline, ExportResult
            enc = Pipeline.encode(ExportResult(addon='plater', version=2, data={ 'x': 1 }, metadata=None))
            dec = Pipeline.decode(enc)
            assert dec.addon == 'plater'
            assert dec.version == 2

        def it_D3_plater_v2_round_trip_preserves_data():
            """D3: Plater v2 round-trip preserves data"""
            from wow_serialization.pipeline import Pipeline, ExportResult
            data = { 'profile': 'Default', 'enabled': True, 'level': 5 }
            enc = Pipeline.encode(ExportResult(addon='plater', version=2, data=data, metadata=None))
            dec = Pipeline.decode(enc)
            assert dec.data['profile'] == 'Default'
            assert dec.data['enabled'] == True
            assert dec.data['level'] == 5

        def it_D4_plater_2_is_detected_before_catch_all():
            """D4: !PLATER:2! is detected before ! catch-all"""
            from wow_serialization.pipeline import Pipeline, ExportResult
            enc = Pipeline.encode(ExportResult(addon='plater', version=2, data='test', metadata=None))
            assert enc.startswith('!PLATER:2!')
            dec = Pipeline.decode(enc)
            assert dec.addon == 'plater'
            assert dec.version == 2

